<?php
$title = 'Nuevo Producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>
<?php

    $form = $this->productoForm;
    $form->setAttribute('action', $this->url('producto', array('action' => 'nuevo')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('idarticulo'));?>
    <div class="input-field col s8">
        <i class="mdi-social-person prefix"></i>
        <?php  echo $this->formText($form->get('articulo_nombre')); ?>
        <?php  echo $this->formLabel($form->get('articulo_nombre'));
        $showError=$this->formElementErrors($form->get('articulo_nombre'));
        if(!empty($showError)):?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php echo $showError; ?>
            </div>
        <?php endif;?>
    </div>
    <div class="input-field col s4">
        <i class="mdi-editor-format-line-spacing prefix"></i>
        <br>
        <select name="idtipo">
            <?php foreach($tipos as $tipo):?>
                <option value='<?php echo $tipo->getIdtipo()?>'><?php echo $tipo->getTipoNombre()?></option>;
            <?php endforeach;?>
        </select>
        <?php  echo $this->formLabel($form->get('idtipo'));

        $showError=$this->formElementErrors($form->get('idtipo'));
        if(!empty($showError)):?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php echo $showError; ?>
            </div>
        <?php endif;?>
    </div>
    <div class="input-field col s12">
        <i class="mdi-editor-border-color prefix"></i>
        <?php  echo $this->formText($form->get('articulo_descripcion')); ?>
        <?php  echo $this->formLabel($form->get('articulo_descripcion'));
        $showError=$this->formElementErrors($form->get('articulo_descripcion'));
        if(!empty($showError)):?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php echo $showError; ?>
            </div>
        <?php endif;?>
    </div>
    <div class="right input-field col s2 offset-s10">
        <?php echo $this->formSubmit($form->get('submit')); ?>

    </div>
    <?php
    //echo $this->formCollection($ArticuloForm);

    echo $this->form()->closeTag();

?>
<script>
$(document).ready(function() {
    $('select').material_select();
});
</script>