<?php
$title = 'Mis ventas';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div>
    <table id="tabla-ventas" class="striped hoverable">
        <thead>
        <tr>
            <th>Fecha</th>
            <th>Tipo de pago</th>
            <th>Status</th>
            <th>¿Venta facturada?</th>
            <th>¿Venta registrada?</th>
            <th>Venta total</th>
            <th>Referencia de pago</th>
            <th>Opciones</th>
        </tr>
        </thead>
        <tbody>
        <?php $direction = 'right'?>
        <?php foreach ($ventas as $ventasEntity) :?>
            <tr>
                <td><?php echo $ventasEntity->getVentaFecha() ?></td>
                <td><?php echo $ventasEntity->getVentaTipodepago() ?></td>
                <td><?php echo $ventasEntity->getVentaStatus() ?></td>
                <td><?php echo $ventasEntity->getVentaFacturada() ?></td>
                <td><?php echo $ventasEntity->getVentaRegistrada() ?></td>
                <td><?php echo $ventasEntity->getVentaTotal() ?></td>
                <td><?php echo $ventasEntity->getVentaReferenciapago() ?></td>
                <td>
                    <a class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href='<?php echo $this->url('venta', array('action'=>'detalles', 'id' => $ventasEntity->getIdventa()))?>'><i class="tiny mdi-image-remove-red-eye"></i></a>
                    &nbsp;&nbsp;
                    <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-venta-".$ventasEntity->getIdventa()?>'><i class="tiny mdi-action-delete"></i></a>
                </td>
            </tr>
            <!-- Delete Modal Structure -->
            <div id="delete-modal-venta-<?php echo $ventasEntity->getIdventa()?>" class="modal">
                <div class="modal-content" id="delete-modal-container">
                    <div class="row" id="delete-modal-header-container">
                        <div class="col s4 offset-s4">
                            <h4><i class="mdi-alert-warning"></i> ATENCION</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <p><?php echo "¿Está seguro que desea eliminar la Venta?: " ?></p>
                            <div class="row">
                                <fieldset>
                                    <legend>Datos Generales</legend>
                                    <div class="col s4">
                                        <div class="label-container">
                                            <label>Fecha:</label>
                                            <p><?php echo $ventasEntity->getVentaFecha();?></p>
                                        </div>
                                        <div class="label-container">
                                            <label>Tipo de pago:</label>
                                            <p><?php echo $ventasEntity->getVentaTipodepago()?></p>
                                        </div>
                                        <div class="label-container">
                                            <label>¿Facturada?:</label>
                                            <p><?php echo $ventasEntity->getVentaFacturada()?></p>
                                        </div>
                                        <div class="label-container">
                                            <label>Total:</label>
                                            <p><?php echo $ventasEntity->getVentaTotal()?></p>
                                        </div>
                                    </div>
                                    <div class="col s4">
                                        <div class="label-container">
                                            <label>Status:</label>
                                            <p><?php echo $ventasEntity->getVentaStatus()?></p>
                                        </div>
                                        <div class="label-container">
                                            <label>Referencia de pago:</label>
                                            <p><?php echo $ventasEntity->getVentaReferenciapago()?></p>
                                        </div>
                                        <div class="label-container">
                                            <label>¿Registrada?:</label>
                                            <p><?php echo $ventasEntity->getVentaRegistrada()?></p>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                    <a href="/venta/eliminar/<?php echo $ventasEntity->getIdventa()?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>

                </div>
            </div>
            <!-- End Delete Modal Structure -->
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.modal-trigger').leanModal();
        $("#tabla-paciente").tablesorter({headers:{5:{sorter:false}}});
        $("#tabla-paciente").filterTable({inputSelector: '#search-container input',minRows:2});
    });
</script>