<?php
$title = 'Registro de productos';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12"> 
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>  
    </form>
</div>
<form action="/productos/registro" method="POST" enctype="multipart/form-data">
    <table id="tabla-articulos" class="table-inputs striped" style="width: 100%">
        <thead>
            
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
</form>
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/accounting.js/0.4.1/accounting.min.js"></script>
<script>
    $(document).ready(function(){
        
        function isNumberKey(evt)
         {
            var charCode = (evt.which) ? evt.which : event.keyCode
            if (charCode > 31 && (charCode < 48 || charCode > 57))
                  return false;

            return true;
         }

        $('tr td:nth-child(4) input,tr td:nth-child(5) input').on('keypress',function(e){
            var isNumber = isNumberKey(e);
            if(!isNumber){
                e.preventDefault();
            }
        });
        
        
        /*
        *   SERVER SIDE 
        */

        var $table;

        $.ajax({
            url: '/json/lang_es_datatable.json',
            dataType: 'json',
            async: false,
            success: function (data) {
                $table = $('#tabla-articulos').DataTable({
                    serverSide: true,
                    language: data,
                    processing: true,
                    iDisplayLength: 10,
                    "bLengthChange": false,
                    order: [],
                    ordering: false,
                    ajax: {
                        url: '/productos/registro/serverside',
                        type: 'POST',
                    },
                     drawCallback: function (settings) {
                       
                         if (typeof $table != 'undefined') {
                     
                            $('table#tabla-articulos tbody tr').remove();
                            $('table#tabla-articulos thead tr').remove();
                            $table.clear();
                        }
                        
                   
                        var thead = $('<tr>');
                        thead.append('<th style="width: 180px">Nombre</th>');
                        thead.append('<th style="width: 300px">Descripción</th>');
                        thead.append('<th>Codigo de barras</th>');
                        thead.append('<th class="number">Costo</th>');
                        thead.append('<th class="number">Precio</th>');
                        thead.append('<th class="number">IVA</th>');
                        thead.append('<th style="text-align:center">Opciones</th>');
                        
                         $('table#tabla-articulos thead').append(thead);
                        
                        var productos = settings.json.data;
          
                        //Tbody
           
                        $.each(productos, function () {
                    
                            var producto = this;
                            var tr = $('<tr>').attr('id', this.idarticulovariante);
                            tr.append('<td class="collapse" title="' + this.articulo_nombre + '">' + this.articulo_nombre + '</td>');
                            tr.append('<td id="descripcion" class="collapse" title="' + this.descripcion + '">' + this.descripcion + '</td>');
                            this.articulovariante_codigobarras = this.articulovariante_codigobarras != null ? this.articulovariante_codigobarras : '';
                            tr.append('<td id="articulovariante_codigobarras" style="padding-left: 0; padding-bottom: 10px;" class="input-table"><span style="visibility: hidden">'+this.articulovariante_codigobarras+'</span><input style="margin-top: 24px;" id="codigo_barras-'+this.idarticulovariante+'" name="producto-'+this.idarticulovariante+'[codigobarras]" type="text" value="'+this.articulovariante_codigobarras+'"></td>');
                            if(this.articulovariante_costo == null){
                               
                                tr.append('<td id="articulovariante_costo" class="input-table number"><span style="visibility: hidden">'+this.articulovariante_costo+'</span><input  id="precio-'+this.idarticulovariante+'" name="producto-'+this.idarticulovariante+'[costo]" type="text" value="0"></td>');
                                
                            }else{
                                tr.append('<td id="articulovariante_costo" class="input-table number"><span style="visibility: hidden">'+this.articulovariante_costo+'</span><input  id="precio-'+this.idarticulovariante+'" name="producto-'+this.idarticulovariante+'[costo]" type="text" value="'+parseFloat(this.articulovariante_costo)+'"></td>');
                            }
                            if(this.articulovariante_precio == null){
                               
                                tr.append('<td id="articulovariante_precio" class="input-table number"><span style="visibility: hidden">'+this.articulovariante_precio+'</span><input  id="precio-'+this.idarticulovariante+'" name="producto-'+this.idarticulovariante+'[precio]" type="text" value="0"></td>');
                                
                            }else{
                                tr.append('<td id="articulovariante_precio" class="input-table number"><span style="visibility: hidden">'+this.articulovariante_precio+'</span><input  id="precio-'+this.idarticulovariante+'" name="producto-'+this.idarticulovariante+'[precio]" type="text" value="'+parseFloat(this.articulovariante_precio)+'"></td>');
                            }
               
                            
                            //IVA
                            var td = $('<td>',{id:'iva',class:'number',style:"padding-bottom: 0"});
                            td.append('<span style="visibility: hidden" style="margin-top: 50px;"></span>');
                            td.append('<select id="iva-'+this.idarticulovariante+'" name="producto-'+this.idarticulovariante+'[iva]"> style="display:block"');
                            td.find('select').append('<option value="0">0%</option><option value="16">16%</option>');
                            if(this.articulovariante_iva==null){
                                td.find('select').val(0);
                            }else{
                                td.find('select').val(this.articulovariante_iva);
                            }
                            
                            
                            tr.append(td);
                            //OPTIONS
                            td = $('<td>',{id:'iva',class:'number',style:"padding-left: 50px; padding-right: 50px"});
                            td.append('<a style="padding-left: 30%" data-position="left" data-tooltip="Visualizar" href="#view-modal-articulo-'+this.idarticulovariante+'"><i class="tiny mdi-image-remove-red-eye"></i></a>&nbsp;&nbsp;');
                            td.append('<a class="tooltipped" data-position="left" data-tooltip="Detalles" href="#modal-producto-'+this.idarticulovariante+'-compras"><i class="tiny mdi-action-assignment"></i></a>');
                            td.append('<a class="tooltipped " data-position="right" data-tooltip="Eliminar" href="#delete-modal-articulo-'+this.idarticulovariante+'"><i class="tiny mdi-action-delete"></i></a>');
                            td.append('<a id="productosRegistros" style="width: 50%; height: 30px; margin-top: 15px"class="registrar_producto btn waves-effect waves-light">Guardar<i class="mdi-content-save left"></i></a>')
                            tr.append(td);
                            
                            
                            
                            
                            $('table#tabla-articulos tbody').append(tr);


                        });
                        
                         $('select').material_select();
                         
                         //Modal compras por articulo
                        $('td i.mdi-action-assignment').on('click',function(){
                            var idarticulovariante = $(this).closest('tr').attr('id');
                            var modalName = '#modal-producto-'+idarticulovariante+'-compras';
                            var descripcion = $(this).closest('td').siblings('#descripcion').text();
                            $.get('/productos/precios/comprasbyarticulovariante',
                                {idarticulovariante:idarticulovariante,descripcion:descripcion},
                                function(modal){
                                    $('table').after(modal);
                                    $(modalName).openModal();
                                }
                            );
                        });
                        
                        $('td i.mdi-image-remove-red-eye').on('click',function(){
                                var idarticulovariante = $(this).closest('tr').attr('id');
                                var modalName = '#view-modal-producto-'+idarticulovariante;
                       
                                $.get('/productos/registro/view',
                                    {idarticulovariante:idarticulovariante},
                                    function(modal){
                                        $('table').after(modal);
                                        $(modalName).openModal();
                                    }
                                );
                            });
                            
                             $('td i.mdi-action-delete').on('click',function(){
                                var idarticulovariante = $(this).closest('tr').attr('id');
                                var modalName = '#delete-modal-articulo-'+idarticulovariante;
                                $.get('/productos/registro/eliminar',
                                    {html:true,idarticulovariante:idarticulovariante},
                                    function(modal){
                                        $('table').after(modal);
                                        $(modalName).openModal();
                                    }
                                );
                            });
                            
                            
                            
                            
                            
                             $("#tabla-articulos").tablesorter({headers:{6:{sorter:false},7:{sorter:false},2:{sorter:false}}});
                            $('select').material_select();
                            $('.tooltipped').tooltip({delay: 50});
                            //("#tabla-articulos").filterTable({inputSelector: '#search-container input',minRows:2});
                            //$('.modal-trigger').leanModal();
                            
                            
                            $(".registrar_producto").on('click',function(){
                                
                                var id = $(this).closest('tr').attr('id');

                                var tr = $(this).closest('tr');

                                var idproducto = $(tr).attr('id');
                                var codigo_barras = $(tr).find('td').eq(2).find('input').val();
                                var costo = $(tr).find('td').eq(3).find('input').val();
                                var precio = $(tr).find('td').eq(4).find('input').val();
                                var iva = $(tr).find('td').eq(5).find('select').val();

                                var formData = new FormData();

                                formData.append('idproducto',idproducto);
                                formData.append('articulovariante_codigobarras', codigo_barras);
                                formData.append('articulovariante_costo', costo);
                                formData.append('articulovariante_precio', precio);
                                formData.append('articulovariante_iva', iva);
                                if ($(tr).find('input[type=file]').length > 0) {
                                    formData.append("articulovariante_imagen", document.getElementById('imagen-' + idproducto).files[0]);
                                }



                                $.ajax({
                                    type: "POST",
                                    //url: "<?php $this->url('productos-registro'); ?>",
                                    contentType: false,
                                    processData: false,
                                    data: formData,
                                    jsonpCallback: 'callback',
                                    success: function (data) {

                                        alert("Guardado Exitosamente");

                                    },
                                    error: function (data) {
                                        alert("Guardado Exitosamente");
                                    }
                                });

                                return false;
                            });

                        
                     }
                });
            },
        });
        
    });



    
    
   
    
    
    
    

</script>