<style>
    #movimiento-edit-modal input[type=text]{
        text-align: left;
    }
    
    #movimiento-edit-modal{
        height: 60%;
        width: 80%;
    }
</style>
<div id="movimiento-edit-modal" class="modal">
    <div class="modal-content" id="edit-modal-container">
        <div class="row">
            <fieldset>
                <input name="idcajachica" type="hidden" value="<?php echo $caja['idcajachica']?>">
                <legend>Movimiento</legend>
                <div class="row">
                    <div class="col s3">
                        <div class="input-field">
                            <input name="cajachica_fecha" type="text" value="<?php echo $caja['cajachica_fecha']?>" disabled>
                            <label>Fecha</label>
                        </div>
                    </div>
                    <div class="col s3">
                        <select name="cajachica_tipomoviento">
                            <option value="" disabled selected>Tipo de movimiento *</option>
                            <option value="cargo">Ingreso</option>
                            <option value="abono">Egreso</option>
                        </select>

                    </div>
                    <div class="col s8">
                        <div class="input-field">
                            <input name="idconcepto" type="hidden">
                            <input name="cajachica_concepto" type="text">
                            <label>Concepto *</label>
                        </div>
                        <p id="cajachica_concepto" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                    </div>   
                    <div class="col s4">
                        <div class="input-field">
                            <input name="cajachica_cantidad" value="<?php echo $caja['cajachica_cantidad']?>" type="text">
                            <label>Cantidad *</label>
                        </div>
                        <p id="cajachica_cantidad" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                    </div>
                    <div class="col s6">
                        <div class="input-field">
                            <input name="cajachica_comprobante" value="<?php echo $caja['cajachica_comprobante']?>" type="text">
                            <label>Comprobante</label>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="input-field">
                            <input name="cajachica_pacientedoctor" value="<?php echo $caja['cajachica_pacientedoctor']?>" type="text"  >
                            <label>Paciente/Doctor</label>
                        </div>           
                    </div>
                    <div class="col s8">
                        <div class="input-field">
                            <input name="cajachica_nota" type="text" value="<?php echo $caja['cajachica_nota']?>">
                            <label>Nota</label>
                        </div>           
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="modal-footer">
        <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
        <a href="#!" class="waves-effect waves-light btn guardar"><i class="mdi-content-save left"></i>Guardar</a>       
    </div>
</div>

<script>
   

    $(document).ready(function(){
        
        var $container = $('#movimiento-edit-modal');
        //Encapsulamos

        //Incializamos el select de tipo de movimiento
        $container.find('select[name=cajachica_tipomoviento]').val('<?php echo $caja['cajachica_tipomovimiento']?>');
        $container.find('select[name=cajachica_tipomoviento]').material_select();
         
        //Inicializamos el componente autcomplete de conceptos
        $container.find('input[name=idconcepto]').val('<?php echo $caja['idconceptocajachica']?>');
        $.getJSON(
            '/cajachica/movimientos/getconceptos',
            function(data){
                var conceptos = data;
                $container.find('input[name=cajachica_concepto]').autocomplete({
                     source:conceptos,
                     select: function( event, ui ) {
                          $container.find('input[name=idconcepto]').val(ui.item.value);
                          $(this).val(ui.item.label);
                          event.preventDefault();
                     }
                });
            }
         );
         $container.find('input[name=cajachica_concepto]').val('<?php echo $caja['conceptocajachica_nombre']?>');
        
        //Inicializamos nuestra fecha
        $container.find('input[name=cajachica_fecha]').datepicker({
            dateFormat: "dd-mm-yy"
        });
        

        //Incializamos el input cantidad
        $container.find('input[name=conceptocajachica_descripcion]').on('keydown',function(e){
             -1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault();

        }); 

       
       $container.find('input[type=text]').filter(function(){
            if($(this).val() != ''){
                $(this).siblings('label').addClass('active');
            }
        });
        

    });

</script>