<?php
    $title = 'Dr. '. $medicoForm->get('medico_nombre')->getValue() . ' '. $medicoForm->get('medico_apellidopaterno')->getValue() . ' '. $medicoForm->get('medico_apellidomaterno')->getValue();
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $medicoForm->setAttribute('action', '/catalogos/medico/editar/'.$id);?>
<?php $medicoForm->setAttribute('class', 'hva-form');?>
<?php $medicoForm->prepare();?>
<?php echo $this->form()->openTag($medicoForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_nombre')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_nombre')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_calle')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_calle')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_colonia')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_colonia')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_estado')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_estado')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_apellidopaterno')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_apellidopaterno')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_noexterior')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_noexterior')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_codigopostal')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_codigopostal')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_pais')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_pais')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_apellidomaterno')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_apellidomaterno')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_nointerior')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_nointerior')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_ciudad')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_ciudad')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Télefonos</legend>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_telefono')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_telefono')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_telefonocelular')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_telefonocelular')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Datos referenciales del médico</legend>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formSelect($medicoForm->get('idespecialidad')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_clave')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_clave')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_ssa')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_ssa')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_dgp')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_dgp')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_ae')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_ae')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
</script>