<?php
    $title = 'Dr. '. $medicoForm->get('medico_nombre')->getValue() . ' '. $medicoForm->get('medico_apellidopaterno')->getValue() . ' '. $medicoForm->get('medico_apellidomaterno')->getValue();
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $medicoForm->setAttribute('action', '/catalogos/medico/editar/'.$id);?>
<?php $medicoForm->setAttribute('class', 'hva-form');?>
<?php $medicoForm->setAttribute('enctype', 'multipart/form-data');?>
<?php $medicoForm->prepare();?>
<?php echo $this->form()->openTag($medicoForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_nombre')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_nombre')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_calle')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_calle')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_colonia')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_colonia')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_estado')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_estado')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_apellidopaterno')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_apellidopaterno')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_noexterior')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_noexterior')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_codigopostal')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_codigopostal')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_pais')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_pais')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_apellidomaterno')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_apellidomaterno')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_nointerior')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_nointerior')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_ciudad')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_ciudad')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Télefonos</legend>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_telefono')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_telefono')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_telefonocelular')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_telefonocelular')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Datos referenciales del médico</legend>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formSelect($medicoForm->get('idespecialidad')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_clave')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_clave')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_ssa')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_ssa')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_dgp')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_dgp')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($medicoForm->get('medico_ae')); ?>
                <?php echo $this->formLabel($medicoForm->get('medico_ae')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Fotografia</legend>
        <div class="col s4 offset-s4" style="padding-left: 120px; padding-right: 120px;">
            <img id="medico_imagen" src="<?php echo $medico_imagen?>" width="210" height="210" style="cursor: pointer">
            <input type="file" name="medico_imagen" style="display: none" accept="image/*" value="<?php echo $medico_imagen?>"> 
            <p id="eliminar_imagen" style="text-align: center; display: none"><a href="javascript:void(0)">Eliminar Imagen</a></p>
        </div>
    </fieldset>
</div>
<p style="color: #9e9e9e">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        
        var idmedico = <?php echo $id ?>;
        
        
        $('select').material_select();
        
        $('button[type=submit]').on('click',function(e){
            $('p.input-error-show').remove();
            var error_message = '<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>';
            var isValid = true;
            $(document).find('input[required],select[required]').filter(function(){
                if($(this).val() == ''){
                    $(this).after(error_message);
                    isValid = false;
                }
                
            });
            
            if(!isValid){
                e.preventDefault();
            }
            
        });
        
         //Imagen medico
        var medico_imagen = '<?php echo $medico_imagen?>';
        if(medico_imagen != '/img/empleados/default_profile.jpg'){
            $('p#eliminar_imagen').show();
        }
        $('img#medico_imagen').on('click',function(){
            $('img#medico_imagen + input').trigger('click');
        });
        
        $('img#medico_imagen + input').on('change',function(){
            
            var $input = $(this);
            var photo =  $('img.img#medico_imagen');
            var inputFiles = this.files;
            
            if(inputFiles == undefined || inputFiles.length == 0) return;

            var inputFile = inputFiles[0];
            var reader = new FileReader();

            reader.onload = function(event) {

                $('img#medico_imagen').attr("src", event.target.result);
           
            };
            
            if($('img#medico_imagen + input').val() != ''){
                $('p#eliminar_imagen').show();
            }

            reader.readAsDataURL(inputFile);
        });
        
        $('p#eliminar_imagen').on('click',function(){
             $('img#medico_imagen').attr("src", '/img/empleados/default_profile.jpg');
             $('img#medico_imagen + input').val('');
             $('p#eliminar_imagen').hide();
             $.get('/catalogos/medico/eliminarimagen',
                {id:idmedico}
            );
            
        });
        
        
        
    });
</script>