<?php
    $title = 'Médicos';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<!--<p>
    <a href="<?php echo $this->url('medico', array('action'=>'nuevo'));?>">Nuevo Medico</a>
</p>-->
<div class="row" id="table-header">
    <form class="col s12">
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="#"><i class="mdi-content-add-circle-outline prefix"></i>Nuevo Médico</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-medicos" class="striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Especialidad</th>
            <th >Opciones</th>
        </tr>
    </thead>
    <tbody>
    <?php $direction = 'right'?>
    <?php foreach ($medicos as $medico) : ?>
        <tr>
            <td><?php echo $medico->getMedicoNombre() ?></td>
            <td><?php echo $medico->getMedicoApellidopaterno() ?></td>
            <td><?php echo $medico->getMedicoApellidomaterno() ?></td>
            <td><?php echo $medico->getEspecialidad()->getEspecialidadNombre() ?></td>
            <td>
                <a class="tooltipped" data-position="left" data-tooltip="Visualizar" href='<?php echo "/catalogos/medico/ver/".$medico->getIdMedico()?>'><i class="tiny mdi-image-remove-red-eye"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/catalogos/medico/editar/".$medico->getIdMedico()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped" data-position="right" data-tooltip="Eliminar" href='<?php echo "/catalogos/medico/eliminar/".$medico->getIdMedico()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>

    </tbody>
    
</table>
<script>
$(document).ready(function(){
    
        $("#tabla-medicos").tablesorter({headers:{4:{sorter:false}}}); 
    
}); 
</script>