<?php

$title = 'Médicos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('medico', array('action'=>'nuevo'));?>">Nuevo Medico</a>
</p>

<table class="table">
    <tr>
        <th>ID Especialidad</th>
        <th>Nombre</th>
        <th>Apellido Paterno</th>
        <th>Apellido Materno</th>
        <th>No. Exterior</th>
        <th>No. Interior</th>
        <th>Colonia</th>
        <th>C.P.</th>
        <th>Ciudad</th>
        <th>Estado</th>
        <th>País</th>
        <th>Teléfono</th>
        <th>Celular</th>
        <th>Clave</th>
        <th>GDP</th>
        <th>SSA</th>
        <th>AE</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($Medicos as $medico) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($medico['idespecialidad']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_nombre']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_apellidopaterno']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_apellidomaterno']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_calle']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_noexterior']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_nointerior']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_colonia']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_codigopostal']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_ciudad']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_estado']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_pais']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_telefono']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_telefonocelular']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_clave']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_dgp']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_ssa']);?></td>
            <td><?php echo $this->escapeHtml($medico['medico_ae']);?></td>
            <td>
                <a href="<?php echo $this->url('medico',
                    array('action'=>'editar', 'id' => $medico['idmedico']));?>">Editar</a>
                <a href="<?php echo $this->url('medico',
                    array('action'=>'eliminar', 'id' => $medico['idmedico']));?>">Eliminar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>