<style>
    .movmiento_vacio{
        text-align: center;
    }
    
    .ui-datepicker .ui-datepicker-title select{
        display: inline-block;
    }
    
    div#ui-datepicker-div{
        padding: 0;
        border: 0;
    }
    
</style>
<?php
$title = 'Modificar cita ('.$paciente['paciente_nombre'].' '.$paciente['paciente_ap'].' '.$paciente['paciente_am'].')';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $form->setAttribute('action', '/pacientes/citas/editar/'.$id);?>
<?php $form->setAttribute('class', 'hva-form');?>
<?php $form->prepare();?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">

    <?php if(count($flashMessages)) :?>
        <?php foreach ($flashMessages as $message) :?>
            <div class="card-panel white-text red darken-4"><?php echo $message?></div>
        <?php endforeach;?>
    <?php endif;?>    
    <?php echo $this->formHidden($form->get('idpaciente')); ?>
    <div class="col s3">
        <div class="input-field">
            <?php echo $this->formText($form->get('cita_fecha')); ?>
            <?php echo $this->formLabel($form->get('cita_fecha')); ?>
        </div>
    </div>
    <div class="col s3">
        <div class="input-field">
            <?php echo $this->formText($form->get('cita_hora')); ?>
            <?php echo $this->formLabel($form->get('cita_hora')); ?>
        </div>
    </div>
    <div class="col s6">
        <div class="input-field">
            <?php echo $this->formSelect($form->get('idmedico')); ?>
        </div>
    </div>
    <div class="col s12">
        <div class="input-field">
            <?php echo $this->formTextArea($form->get('cita_descripcion')); ?>
            <?php echo $this->formLabel($form->get('cita_descripcion')); ?>
        </div>
    </div>
</div>
<p style="color: #9e9e9e">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
        $("#fecha").datepicker();
        
        //Inicializamos la fecha
        $('input[name=cita_fecha]').pickadate({
            monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            weekdaysLetter: ['D', 'L', 'M', 'MI', 'J', 'V', 'S'],
            today: 'Hoy',
            close: 'Cerrar',
            clear: 'Eliminar',
            min: new Date(),
           formatSubmit: 'yyyy-mm-dd',
            format: 'dd-mm-yyyy',
        });
        
        //Inicializamos la hora
        $('input[name=cita_hora').lolliclock({autoclose:true});
        
        
    });
</script>