<div id="delete-modal" class="modal ">
    <div class="modal-content" id="delete-modal-container">
        <div class="row" id="delete-modal-header-container">
            <div class="col s5 offset-s4">
                <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <p><?php echo $message ?></p>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
        <a href="#!" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>       
    </div>
</div>