<?php
$title = $pacienteEntity->getPacienteNombre()." ".$pacienteEntity->getPacienteAp()." ".$pacienteEntity->getPacienteAm();
$this->headTitle($title);
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>
<div>
<fieldset>
    <legend>Datos generales del paciente</legend>
    <div class="col s4">
        <div class="label-container">
            <label>Fecha de nacimiento:</label>
            <p><?php echo $pacienteEntity->getPacienteFechanacimiento()?></p>
        </div>
        <div class="label-container">
            <label>Responsable:</label>
            <p><?php echo $pacienteEntity->getPacienteResponsable()?></p>
        </div>
    </div>
    <div class="col s4">
        <div class="label-container">
            <label>Edad:</label>
            <p><?php echo $edad . " años"?></p>
        </div>
        <div class="label-container">
            <label>Teléfono responsable:</label>
            <p><?php echo $pacienteEntity->getPacienteTelefonoresponsable()?></p>
        </div>
    </div>
    <div class="col s4">
        <div class="label-container">
            <label>Sexo:</label>
            <p><?php echo $pacienteEntity->getPacienteSexo()?></p>
        </div>
    </div>
</fieldset>
<br>
<div class="row">
<fieldset>
<legend>Para uso exclusivo del hospital</legend>
<label>Selecciona una acción</label>
<div class="col s12">
    <div id="radioNuevaConsulta" class="col s4">
        <p onclick="javascript:nuevaConsulta();" >
            <input class="with-gap" name="grupo1" type="radio" id="test3"  />
            <label for="test3">Nueva consulta</label>
        </p>
    </div>
    <div id="radioNuevaAdmision" class="col s4">
        <p onclick="javascript:nuevaAdmision();" >
            <input class="with-gap" name="grupo1" type="radio" id="test4"  />
            <label for="test4">Nueva admisión</label>
        </p>
    </div>
</div>
<div id="consulta" class="hiddendiv">
    <?php $consultaForm->prepare();?>
    <?php echo $this->form()->openTag($consultaForm); ?>
    <div class="col s4">
        <div class="input-field">
            <?php echo $this->formHidden($consultaForm->get('idpaciente')->setValue($pacienteEntity->getIdpaciente())); ?>
        </div>
        <div class="input-field">
            <?php echo $this->formSelect($consultaForm->get('idmedico')); ?>
            <span class="red-text hidden" for="idmedico" id="idmedico_error">Debe selecionar un medico.</span><br><br>
            <?php $showError=$this->formElementErrors($consultaForm->get('idmedico'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s4 offset-s4">
        <div class="input-field">
            <?php echo $this->formSelect($consultaForm->get('idconsultorio')); ?>
            <span class="red-text hidden" for="idconsultorio" id="idconsultorio_error">Debe selecionar un consultorio.</span><br><br>
            <?php $showError=$this->formElementErrors($consultaForm->get('idconsultorio'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s12">
        <div class="input-field">
            <?php echo $this->formText($consultaForm->get('consulta_fechaadmision')); ?>
            <?php echo $this->formLabel($consultaForm->get('consulta_fechaadmision')); ?>
            <span class="red-text hidden" for="consulta_fechaadmision" id="fechaadmision_error">Debe selecionar una fecha.</span><br><br>
            <?php $showError=$this->formElementErrors($consultaForm->get('consulta_fechaadmision'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s6">
        <div class="input-field">
            <?php echo $this->formText($consultaForm->get('consulta_diagnostico')); ?>
            <?php echo $this->formLabel($consultaForm->get('consulta_diagnostico')); ?>
            <?php $showError=$this->formElementErrors($consultaForm->get('consulta_diagnostico'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s6">
        <div class="input-field">
            <?php echo $this->formText($consultaForm->get('consulta_observaciones')); ?>
            <?php echo $this->formLabel($consultaForm->get('consulta_observaciones')); ?>
            <?php $showError=$this->formElementErrors($consultaForm->get('consulta_observaciones'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <br>
    <br>
    <div id="botonGuardarConsulta" class="right col s4">
        <button id="guardarConsulta" style="width: 100%; height: 45px; margin-top: 20px;" class="btn waves-effect waves-light" type="submit">Guardar Consulta
            <i class="mdi-content-save left"></i>
        </button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div class="right col s4">
        <button style="width: 100%; height: 45px; margin-top: 20px;" class="btn waves-effect waves-light disabled" type="submit" name="action">Alta Paciente - Consulta
            <i class="mdi-action-accessibility left"></i>
        </button>
    </div>
</div>

<div id="admision" class="hiddendiv">
    <?php $admisionForm->prepare();?>
    <?php echo $this->form()->openTag($admisionForm); ?>
    <div class="col s4">
        <div class="input-field">
            <?php echo $this->formHidden($admisionForm->get('idpaciente')->setValue($pacienteEntity->getIdpaciente())); ?>
        </div>
        <div class="input-field">
            <?php echo $this->formSelect($admisionForm->get('idmedico')); ?>
            <span class="red-text hidden" for="idmedico" id="idmedico_error">Debe selecionar un medico.</span><br><br>
            <?php $showError=$this->formElementErrors($admisionForm->get('idmedico'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s4 offset-s4">
        <div class="input-field">
            <?php echo $this->formSelect($admisionForm->get('idcuarto')); ?>
            <span class="red-text hidden" for="idcuarto" id="idcuarto_error">Debe selecionar un cuarto.</span><br><br>
            <?php $showError=$this->formElementErrors($admisionForm->get('idcuarto'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s12">
        <div class="input-field">
            <?php echo $this->formText($admisionForm->get('admision_fechaadmision')); ?>
            <?php echo $this->formLabel($admisionForm->get('admision_fechaadmision')); ?>
            <span class="red-text hidden" for="admision_fechaadmision" id="fechaadmision_error">Debe selecionar una fecha.</span><br><br>
            <?php $showError=$this->formElementErrors($admisionForm->get('admision_fechaadmision'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s6">
        <div class="input-field">
            <?php echo $this->formText($admisionForm->get('admision_diagnostico')); ?>
            <?php echo $this->formLabel($admisionForm->get('admision_diagnostico')); ?>
            <?php $showError=$this->formElementErrors($admisionForm->get('admision_diagnostico'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="col s6">
        <div class="input-field">
            <?php echo $this->formText($admisionForm->get('admision_observaciones')); ?>
            <?php echo $this->formLabel($admisionForm->get('admision_observaciones')); ?>
            <?php $showError=$this->formElementErrors($admisionForm->get('admision_observaciones'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div id="botonGuardarAdmision" class="right col s4">
        <button id="guardarAdmision" style="width: 100%; height: 45px; margin-top: 20px;" class="btn waves-effect waves-light" type="submit" name="action">Guardar Admisión
            <i class="mdi-content-save left"></i>
        </button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div class="right col s4">
        <button style="width: 100%; height: 45px; margin-top: 20px;" class="btn waves-effect waves-light disabled" type="submit" name="action">Alta Paciente - Admisión
            <i class="mdi-action-accessibility left"></i>
        </button>
    </div>
</div>
</fieldset>
</div>
<div class="row">
    <?php if($pacienteQuery):?>
        <div class="col s4">
            <a style="width: 100%; height: 45px; padding-top: 5px;" class="btn center-align" href="<?php echo $this->url('pacientes')?>ver/<?php echo $pacienteQuery->getIdpaciente()?>"><i class="mdi-editor-insert-comment left"></i>Nueva consula/admisión</a>
        </div>
    <?php endif;?>
</div>
<?php //if($cargoconsultaFlag == true): ?>
<div id="cargos" class="hiddendiv">
<fieldset>
<legend>Cargos al paciente</legend>
<div id="totalSuperior" class="col s9">
    <!-- Aquí agregamos los elementos con javascript -->
</div>
<div id="nuevoCargoArticulo" class=" col s3 offset-s9">
    <a class="tooltipped modal-trigger right" data-position="right" data-tooltip="AgregarCargoconsulta" href='#create-modal-cargoconsulta-articulo'><i class="mdi-content-add-circle-outline prefix"></i>Agregar producto a cuenta</a>
</div>
<!-- Create Modal Structure -->
<div id="create-modal-cargoconsulta-articulo" class="modal bottom-sheet" style="width: 100%; bottom: 15px;">
    <div class="modal-content">
        <h3>Agregar producto a cuenta</h3>
        <div class="row" id="table-header">
            <?php $cargoconsultaForm->prepare();?>
            <?php echo $this->form()->openTag($cargoconsultaForm); ?>
            <div class="input-field">
                <?php echo $this->formHidden($cargoconsultaForm->get('idconsulta')); ?>
            </div>
            <div id="modalCargoconsultaArticulo" class="row">
                <div id="busquedaCargoconsultaArticulo" class="col s5">
                    <div class="input-field col s4 left" id="search-container">
                        <i class="mdi-action-search prefix"></i>
                        <?php echo $this->formText($cargoconsultaForm->get('busquedaArticulo')); ?>
                        <?php echo $this->formLabel($cargoconsultaForm->get('busquedaArticulo')); ?>
                    </div>
                    <div class="col s4">
                        <div class="input-field">
                            <?php echo $this->formSelect($cargoconsultaForm->get('cargoconsultaarticulo_by')); ?>
                            <span class="red-text hidden" for="cargoconsultaarticulo_by" id="cargoconsultaarticulo_by_error">Debe selecionar un tipo de busqueda.</span><br><br>
                        </div>
                    </div>
                    <div class="right col s4">
                        <button id="buscarCargoconsultaArticulo" style="width: 100%; height: 45px; margin-top: 20px;" class="btn light-blue lighten-3 waves-effect waves-light">Buscar</button>
                    </div>
                    <div id="fieldsetCargoconsultaArticulo" class="col s12 hiddendiv">
                        <fieldset>
                            <legend>Artículo</legend>
                            <div id="fieldsetCargoconsultaArticuloEntity" class="left col s8">
                                <!-- Aquí agregamos los elementos con javascript -->
                            </div>
                            <div id="botonGuardarCargoconsultaArticulo" class="right col s4" style="margin-top: 80px;">
                                <button id="guardarCargoconsultaArticulo" class="btn waves-effect waves-light" type="submit">Agregar</button>
                            </div>
                        </fieldset>
                        <br>
                        <br>
                    </div>
                    <div id="tablaCargoconsultaArticulo" class="col s12">
                        <!-- Aquí agregamos los elementos con javascript -->
                    </div>
                </div>
                <div id="tablaCargoconsultaArticuloAgregado" class="col s7">
                    <!-- Aquí agregamos los elementos con javascript -->
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<!-- End Create Modal Structure -->
<div id="cargoconsultaArticuloResult" class="hiddendiv">
    <!-- Aquí agregamos los elementos con javascript -->
</div>
<br>
<br>
<div id="nuevoCargoServicio" class=" col s3 offset-s9">
    <a class="tooltipped modal-trigger right" data-position="right" data-tooltip="AgregarCargoconsulta" href='#create-modal-cargoconsulta-servicio'><i class="mdi-content-add-circle-outline prefix"></i>Agregar servicio a cuenta</a>
</div>
<!-- Create Modal Structure -->
<div id="create-modal-cargoconsulta-servicio" class="modal bottom-sheet" style="width: 100%; bottom: 15px;">
    <div class="modal-content">
        <h3>Agregar servicio a cuenta</h3>
        <div class="row" id="table-header">
            <?php $cargoconsultaForm->prepare();?>
            <?php echo $this->form()->openTag($cargoconsultaForm); ?>
            <div class="input-field">
                <?php echo $this->formHidden($cargoconsultaForm->get('idconsulta')); ?>
            </div>
            <div id="modalCargoconsultaServicio" class="row">
                <div id="busquedaCargoconsultaServicio" class="col s6">
                    <div class="input-field col s4 left" id="search-container">
                        <i class="mdi-action-search prefix"></i>
                        <?php echo $this->formText($cargoconsultaForm->get('busquedaServicio')); ?>
                        <?php echo $this->formLabel($cargoconsultaForm->get('busquedaServicio')); ?>
                    </div>
                    <div class="col s4">
                        <div class="input-field">
                            <?php echo $this->formSelect($cargoconsultaForm->get('cargoconsultaservicio_by')); ?>
                            <span class="red-text hidden" for="cargoconsultaservicio_by" id="cargoconsultaservicio_by_error">Debe selecionar un tipo de busqueda.</span><br><br>
                        </div>
                    </div>
                    <div class="right col s4">
                        <button id="buscarCargoconsultaServicio" style="width: 100%; height: 45px; margin-top: 20px;" class="btn light-blue lighten-3 waves-effect waves-light">Buscar</button>
                    </div>
                    <div id="fieldsetCargoconsultaServicio" class="col s12 hiddendiv">
                        <fieldset>
                            <legend>Servicio</legend>
                            <div id="fieldsetCargoconsultaServicioEntity" class="left col s8">
                                <!-- Aquí agregamos los elementos con javascript -->
                            </div>
                            <div id="botonGuardarCargoconsultaServicio" class="right col s4" style="margin-top: 50px;">
                                <button id="guardarCargoconsultaServicio" class="btn waves-effect waves-light" type="submit">Agregar</button>
                            </div>
                        </fieldset>
                        <br>
                        <br>
                    </div>
                    <div id="tablaCargoconsultaServicio" class="col s12">
                        <!-- Aquí agregamos los elementos con javascript -->
                    </div>
                </div>
                <div id="tablaCargoconsultaServicioAgregado" class="col s6">
                    <!-- Aquí agregamos los elementos con javascript -->
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<!-- End Create Modal Structure -->
<div id="cargoconsultaServicioResult" class="hiddendiv">
    <!-- Aquí agregamos los elementos con javascript -->
</div>
<div class="col s12">
    <div id="botonPagarAnticipo" class="col s2">
        <!-- Aquí agregamos los elementos con javascript -->
    </div>
    <div id="botonGenerarFactura" class="col s3">
        <!-- Aquí agregamos los elementos con javascript -->
    </div>
    <div id="botonGenerarNota" class="col s2">
        <!-- Aquí agregamos los elementos con javascript -->
    </div>
    <div id="totalInferior" class="col s3">
        <!-- Aquí agregamos los elementos con javascript -->
    </div>
</div>
<div class="col s12">
    <div id="botonVerFactura" class="col s3 offset-s2">
        <!-- Aquí agregamos los elementos con javascript -->
    </div>
</div>
</fieldset>
</div>
<?php //endif; ?>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $('select').material_select();
    $("#consulta_fechaadmision").datepicker();
    $("#admision_fechaadmision").datepicker();

    //Cargoconsulta
    $('.modal-trigger').leanModal();
    $("#tabla-cargoconsulta").tablesorter({headers:{5:{sorter:false}}});
    $("#tabla-cargoconsulta").filterTable({inputSelector: '#search-container input',minRows:2});
    $("#tablaCargoconsultaArticulo").tablesorter({headers:{5:{sorter:false}}});
    $("#tablaCargoconsultaArticulo").filterTable({inputSelector: '#search-container input',minRows:2});
});
function nuevaConsulta() {
    if ($('#consulta').hasClass('hiddendiv')){
        $('#consulta').removeClass('hiddendiv')
        $('#admision').addClass('hiddendiv')
        $('#radioNuevaAdmision').addClass('hiddendiv')
    }
}
function nuevaAdmision() {
    if ($('#admision').hasClass('hiddendiv')){
        $('#admision').removeClass('hiddendiv')
        $('#consulta').addClass('hiddendiv')
        $('#radioNuevaConsulta').addClass('hiddendiv')
    }
}

// Validamos formulario Consulta
$('.red-text').hide();
$("#guardarConsulta").click(function() {

    //Obtenemos el valor del selector de medicos
    var idmedico = $("select#idmedico").val();
    //Validamos el campo medico, simplemente miramos que no esté vacío
    if (idmedico == "") {
        if ($('span#idmedico_error').hasClass('hidden')){
            $('span#idmedico_error').removeClass('hidden');
            $("span#idmedico_error").show();
            $("span#idmedico").focus();
        }
        return false;
    }else{
        $('span#idmedico_error').hide();
    }

    //Obtenemos el valor del selector de consultorios
    var idconsultorio = $("select#idconsultorio").val();
    //Validamos el campo medico, simplemente miramos que no esté vacío
    if (idconsultorio == "") {
        if ($('span#idconsultorio_error').hasClass('hidden')){
            $('span#idconsultorio_error').removeClass('hidden');
            $("span#idconsultorio_error").show();
            $("span#idconsultorio").focus();
        }
        return false;
    }else{
        $("span#idconsultorio_error").hide();
    }

    //Obtenemos el valor del campo fechaadmision
    var consulta_fechaadmision = $("input#consulta_fechaadmision").val();

    //Validamos el campo fechaadmision, simplemente miramos que no esté vacío
    if (consulta_fechaadmision == "") {
        if ($('span#fechaadmision_error').hasClass('hidden')){
            $('span#fechaadmision_error').removeClass('hidden');
            $("span#fechaadmision_error").show();
            $("span#consulta_fechaadmision").focus();
        }
        return false;
    }else{
        $("span#fechaadmision_error").hide();
    }

    //Obtenemos el valor del campo idpaciente
    var idpaciente = $("input#idpaciente").val();
    //Obtenemos el valor del campo consulta_diagnostico
    var consulta_diagnostico = $("input#consulta_diagnostico").val();
    //Obtenemos el valor del campo consulta_observaciones
    var consulta_observaciones = $("input#consulta_observaciones").val();

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'idmedico=' + idmedico + '&idconsultorio=' + idconsultorio + '&idpaciente=' + idpaciente + '&consulta_fechaadmision=' + consulta_fechaadmision + '&consulta_diagnostico=' + consulta_diagnostico + '&consulta_observaciones=' + consulta_observaciones;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            $("input#idconsulta").val(JSON.stringify(data.consultaArray.idconsulta));

            if ($('#cargos').hasClass('hiddendiv')){
                $('#cargos').removeClass('hiddendiv')
                $('#botonGuardarConsulta').addClass('hiddendiv')
                $('#cargos').prepend('<div class="card-panel #00086E-text green accent-2 guardado-ajax">Consulta guardada exitosamente</div>')
                $('#cargos').removeClass('hiddendiv')
            }
        }
    });

    return false;
});
$("#guardarAdmision").click(function() {

    //Obtenemos el valor del selector de medicos
    var idmedico = $("select#idmedicoadmision").val();
    //Validamos el campo medico, simplemente miramos que no esté vacío
    if (idmedico == "") {
        if ($('span#idmedico_error').hasClass('hidden')){
            $('span#idmedico_error').removeClass('hidden');
            $("span#idmedico_error").show();
            $("span#idmedico").focus();
        }
        return false;
    }else{
        $('span#idmedico_error').hide();
    }

    //Obtenemos el valor del selector de cuartos
    var idcuarto = $("select#idcuarto").val();
    //Validamos el campo idcuarto, simplemente miramos que no esté vacío
    if (idcuarto == "") {
        if ($('span#idcuarto_error').hasClass('hidden')){
            $('span#idcuarto_error').removeClass('hidden');
            $("span#idcuarto_error").show();
            $("span#idcuarto").focus();
        }
        return false;
    }else{
        $("span#idcuarto_error").hide();
    }

    //Obtenemos el valor del campo fechaadmision
    var admision_fechaadmision = $("input#admision_fechaadmision").val();

    //Validamos el campo fechaadmision, simplemente miramos que no esté vacío
    if (admision_fechaadmision == "") {
        if ($('span#fechaadmision_error').hasClass('hidden')){
            $('span#fechaadmision_error').removeClass('hidden');
            $("span#fechaadmision_error").show();
            $("span#admision_fechaadmision").focus();
        }
        return false;
    }else{
        $("span#fechaadmision_error").hide();
    }

    //Obtenemos el valor del campo idpaciente
    var idpaciente = $("input#idpacienteadmision").val();
    //Obtenemos el valor del campo admision_diagnostico
    var admision_diagnostico = $("input#admision_diagnostico").val();
    //Obtenemos el valor del campo admision_observaciones
    var admision_observaciones = $("input#admision_observaciones").val();

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'idmedico=' + idmedico + '&idcuarto=' + idcuarto + '&idpaciente=' + idpaciente + '&admision_fechaadmision=' + admision_fechaadmision + '&admision_diagnostico=' + admision_diagnostico + '&admision_observaciones=' + admision_observaciones;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            $("input#idadmision").val(JSON.stringify(data.admisionQuery.idadmision));
            if ($('#cargos').hasClass('hiddendiv')){
                $('#cargos').removeClass('hiddendiv')
                $('#botonGuardarAdmision').addClass('hiddendiv')
                $('#cargos').prepend('<div class="card-panel #00086E-text green accent-2 guardado-ajax">Admisión guardada exitosamente</div>')
                $('#cargos').removeClass('hiddendiv')
            }
        }
    });

    return false;
});

$("#buscarCargoconsultaArticulo").click(function() {

    //Obtenemos el valor del selector de lugarinventario
    var busquedaArticulo = $("input#busquedaArticulo").val();

    //Obtenemos el valor del selector de lugarinventario
    var cargoconsultaarticulo_by = $("select#cargoconsultaarticulo_by").val();
    //Validamos el campo idlugarinventario, simplemente miramos que no esté vacío
    if (cargoconsultaarticulo_by == "") {
        if ($('span#cargoconsultaarticulo_by_error').hasClass('hidden')){
            $('span#cargoconsultaarticulo_by_error').removeClass('hidden');
            $("span#cargoconsultaarticulo_by_error").show();
            $("span#cargoconsultaarticulo_by").focus();
        }
        return false;
    }else{
        $("span#cargoconsultaarticulo_by_error").hide();
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'cargoconsultaarticulo_by=' + cargoconsultaarticulo_by + '&busquedaArticulo=' + busquedaArticulo ;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            ordencompradetalleArray = []
            var ordencompradetalleEntity = data.ordencompradetalleArray
            $.each( ordencompradetalleEntity, function( key, value ) {
                ordencompradetalleArray.push({
                    "idordencompradetalle" : value.idordencompradetalle,
                    "idlugarinventario" : value.idlugarinventario,
                    "cargoconsulta_tipo" : value.cargoconsulta_tipo,
                    "cargoconsulta_fecha" : value.cargoconsulta_fecha,
                    "caducidad" : value.ordencompradetalle_caducidad,
                    "existencia" : value.existencia,
                    "articulo" : value.articulo,
                    "descripcion" : value.descripcion,
                    "costo" : value.costo,
                    "salida" : value.salida
                });
            });

            // Creamos nuestra tabla de colecciones
            generaTablaBuscarConsultaArticulo(ordencompradetalleArray);

            // Seleccionamos un item de nuestra tabla de colecciones y construimos la entidad para agregarla como cargoconsulta
            $.each(ordencompradetalleArray, function(keys, values){
                // Si dan clic a una entidad de la colección
                $("#entidadArticulo-"+values.idordencompradetalle).click(function(){
                    if ($('#fieldsetCargoconsultaArticulo').hasClass('hiddendiv')){
                        $('#fieldsetCargoconsultaArticulo').removeClass('hiddendiv')
                    }
                    var br   = document.createElement("br");
                    var br2   = document.createElement("br");
                    var br3   = document.createElement("br");
                    var br4   = document.createElement("br");
                    var br5   = document.createElement("br");
                    // Creamos el input de cantidad de tipo select
                    var divinputCantidad = document.createElement('div');
                    divinputCantidad.className = "input-field";
                    divinputCantidad.setAttribute ( 'id', 'divinputCantidad' );
                    var select = document.createElement('select');
                    select.style.display = "inline";
                    select.style.width = "auto";
                    select.style.height = "auto";
                    select.setAttribute ( 'id', 'cantidad' );
                    // agregamos los valores <option> a seleccionar
                    for($i=1; $i<=values.existencia; $i++){
                        var selectOption = new Option($i,$i);
                        select.appendChild(selectOption);
                    }
                    // agregamos las options en nuestro select
                    divinputCantidad.appendChild(select);

                    // Creamos la entidad textual lista para agregar al cargoconsulta
                    var div = document.getElementById("fieldsetCargoconsultaArticuloEntity");
                    div.innerHTML = div;
                    var textoArticulo = document.createTextNode("Artículo: "+values.articulo);
                    var textoDescripcion = document.createTextNode("Descrpción: "+values.descripcion);
                    var textoCaducidad = document.createTextNode("Caducidad: "+values.caducidad);
                    var textoDisponibleEn = document.createTextNode("Disponible en: "+values.salida);
                    var textoExistencia = document.createTextNode("Existencias: "+values.existencia);
                    var textoCantidad = document.createTextNode("Cantidad: ");
                    div.appendChild(textoArticulo);
                    div.appendChild(br);
                    div.appendChild(textoDescripcion);
                    div.appendChild(br2);
                    div.appendChild(textoCaducidad);
                    div.appendChild(br3);
                    div.appendChild(textoDisponibleEn);
                    div.appendChild(br4);
                    div.appendChild(textoExistencia);
                    div.appendChild(br5);
                    div.appendChild(textoCantidad);
                    div.appendChild(select);

                    // Actializar existencias

                    // El input ordencompradetalle solamente lo necesitamos para actualizar nuestra entidad artículo antes de agregar el cargo.
                    // Si el formulario ya tiene el input de idordencompradetalle lo eliminamos
                    if(document.getElementById('divinputIdordencompradetalle')){
                        var divinputIdordencompradetalleDelete = document.getElementById("divinputIdordencompradetalle");
                        divinputIdordencompradetalleDelete.parentNode.removeChild(divinputIdordencompradetalleDelete);
                    }
                    // Actializar existencias

                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputIdlugarinventario')){
                        var divinputIdlugarinventarioDelete = document.getElementById("divinputIdlugarinventario");
                        divinputIdlugarinventarioDelete.parentNode.removeChild(divinputIdlugarinventarioDelete);
                    }
                    // Si el formulario ya tiene el input de cargoconsulta_tipo lo eliminamos
                    if(document.getElementById('divinputCargoconsultaTipo')){
                        var divinputCargoconsultaTipoDelete = document.getElementById("divinputCargoconsultaTipo");
                        divinputCargoconsultaTipoDelete.parentNode.removeChild(divinputCargoconsultaTipoDelete);
                    }
                    // Si el formulario ya tiene el input de cargoconsulta_fecha lo eliminamos
                    if(document.getElementById('divinputCargoconsultaFecha')){
                        var divinputCargoconsultaFechaDelete = document.getElementById("divinputCargoconsultaFecha");
                        divinputCargoconsultaFechaDelete.parentNode.removeChild(divinputCargoconsultaFechaDelete);
                    }

                    // Creamos nuestro Formulario con los datos a insertar en Cargoconsulta
                    var form = document.getElementById('CargoconsultaForm');
                    // Actializar existencias
                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdordencompradetalle = document.createElement('div');
                    divinputIdordencompradetalle.className = "input-field";
                    divinputIdordencompradetalle.setAttribute ( 'id', 'divinputIdordencompradetalle' );
                    var inputIdordencompradetalle = document.createElement('input');
                    inputIdordencompradetalle.setAttribute ( 'id', 'idordencompradetalle' );
                    inputIdordencompradetalle.setAttribute ( 'type', 'hidden' );
                    inputIdordencompradetalle.setAttribute ( 'name', 'idordencompradetalle' );
                    inputIdordencompradetalle.setAttribute ( 'value', values.idordencompradetalle );
                    divinputIdordencompradetalle.appendChild(inputIdordencompradetalle)
                    // Actializar existencias

                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdlugarinventario = document.createElement('div');
                    divinputIdlugarinventario.className = "input-field";
                    divinputIdlugarinventario.setAttribute ( 'id', 'divinputIdlugarinventario' );
                    var inputIdlugarinventario = document.createElement('input');
                    inputIdlugarinventario.setAttribute ( 'id', 'idlugarinventario' );
                    inputIdlugarinventario.setAttribute ( 'type', 'hidden' );
                    inputIdlugarinventario.setAttribute ( 'name', 'idlugarinventario' );
                    inputIdlugarinventario.setAttribute ( 'value', values.idlugarinventario );
                    divinputIdlugarinventario.appendChild(inputIdlugarinventario)
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaTipo = document.createElement('div');
                    divinputCargoconsultaTipo.className = "input-field";
                    divinputCargoconsultaTipo.setAttribute ( 'id', 'divinputCargoconsultaTipo' );
                    var inputCargoconsultaTipo = document.createElement('input');
                    inputCargoconsultaTipo.setAttribute ( 'id', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaTipo.setAttribute ( 'name', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'value', values.cargoconsulta_tipo );
                    divinputCargoconsultaTipo.appendChild(inputCargoconsultaTipo);
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaFecha = document.createElement('div');
                    divinputCargoconsultaFecha.className = "input-field";
                    divinputCargoconsultaFecha.setAttribute ( 'id', 'divinputCargoconsultaFecha' );
                    var inputCargoconsultaFecha = document.createElement('input');
                    inputCargoconsultaFecha.setAttribute ( 'id', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaFecha.setAttribute ( 'name', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'value', values.cargoconsulta_fecha );
                    divinputCargoconsultaFecha.appendChild(inputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaTipo);
                    form.appendChild(divinputIdlugarinventario);
                    form.appendChild(divinputIdordencompradetalle);
                });
            });
        },
        error: function(){
            $('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar buscar</div>')
        }
    });

    return false;
});

$("#buscarCargoconsultaServicio").click(function() {

    //Obtenemos el valor del selector de lugarinventario
    var busquedaServicio = $("input#busquedaServicio").val();

    //Obtenemos el valor del selector de lugarinventario
    var cargoconsultaservicio_by = $("select#cargoconsultaservicio_by").val();
    //Validamos el campo idlugarinventario, simplemente miramos que no esté vacío
    if (cargoconsultaservicio_by == "") {
        if ($('span#cargoconsultaservicio_by_error').hasClass('hidden')){
            $('span#cargoconsultaservicio_by_error').removeClass('hidden');
            $("span#cargoconsultaservicio_by_error").show();
            $("span#cargoconsultaservicio_by").focus();
        }
        return false;
    }else{
        $("span#cargoconsultaservicio_by_error").hide();
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'cargoconsultaservicio_by=' + cargoconsultaservicio_by + '&busquedaServicio=' + busquedaServicio ;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            servicioArray = []
            var servicioEntity = data.servicioArray
            $.each( servicioEntity, function( key, value ) {
                servicioArray.push({
                    "idservicio" : value.idservicio,
                    "cargoconsulta_tipo" : value.cargoconsulta_tipo,
                    "cargoconsulta_fecha" : value.cargoconsulta_fecha,
                    "servicio_nombre" : value.servicio_nombre,
                    "servicio_descripcion" : value.servicio_descripcion,
                    "servicio_precio" : value.servicio_precio
                });
            });

            // Creamos nuestra tabla de colecciones
            generaTablaBuscarConsultaServicio(servicioArray);

            // Seleccionamos un item de nuestra tabla de colecciones y construimos la entidad para agregarla como cargoconsulta
            $.each(servicioArray, function(keys, values){
                // Si dan clic a una entidad de la colección
                $("#entidadServicio-"+values.idservicio).click(function(){
                    if ($('#fieldsetCargoconsultaServicio').hasClass('hiddendiv')){
                        $('#fieldsetCargoconsultaServicio').removeClass('hiddendiv')
                    }
                    var br   = document.createElement("br");
                    var br2   = document.createElement("br");
                    var br3   = document.createElement("br");
                    var br4   = document.createElement("br");
                    // Creamos el input de cantidad de tipo input
                    var divinputCantidad = document.createElement('div');
                    divinputCantidad.className = "input-field";
                    divinputCantidad.setAttribute ( 'id', 'divinputCantidad' );
                    var inputCantidad = document.createElement('input');
                    inputCantidad.setAttribute ( 'id', 'cantidad' );
                    inputCantidad.style.width = "20%";
                    inputCantidad.type = "number";
                    inputCantidad.min ="1";
                    inputCantidad.max = "999999999";

                    // agregamos las options en nuestro input
                    divinputCantidad.appendChild(inputCantidad);

                    // Creamos la entidad textual lista para agregar al cargoconsulta
                    var div = document.getElementById("fieldsetCargoconsultaServicioEntity");
                    div.innerHTML = div;
                    var textoServicioNombre = document.createTextNode("Servicio: "+values.servicio_nombre);
                    var textoServicioDescripcion = document.createTextNode("Descrpción: "+values.servicio_descripcion);
                    var textoServicioPrecio = document.createTextNode("Costo: "+values.servicio_precio);
                    var textoCargoconsultaFecha = document.createTextNode("Fecha: "+values.cargoconsulta_fecha);
                    var textoCantidad = document.createTextNode("Cantidad: ");
                    div.appendChild(textoServicioNombre);
                    div.appendChild(br);
                    div.appendChild(textoServicioDescripcion);
                    div.appendChild(br2);
                    div.appendChild(textoServicioPrecio);
                    div.appendChild(br3);
                    div.appendChild(textoCargoconsultaFecha);
                    div.appendChild(br4);
                    div.appendChild(textoCantidad);
                    div.appendChild(inputCantidad);

                    // El input idservicio solamente lo necesitamos para actualizar nuestra entidad servicio antes de agregar el cargo.
                    // Si el formulario ya tiene el input de idservicio lo eliminamos
                    if(document.getElementById('divinputIdservicio')){
                        var divinputIdservicioDelete = document.getElementById("divinputIdservicio");
                        divinputIdservicioDelete.parentNode.removeChild(divinputIdservicioDelete);
                    }

                    // Si el formulario ya tiene el input de servicio_nombre lo eliminamos
                    if(document.getElementById('divinputCargoconsultaTipo')){
                        var divinputCargoconsultaTipoDelete = document.getElementById("divinputCargoconsultaTipo");
                        divinputCargoconsultaTipoDelete.parentNode.removeChild(divinputCargoconsultaTipoDelete);
                    }
                    // Si el formulario ya tiene el input de servicio_descripcion lo eliminamos
                    if(document.getElementById('divinputCargoconsultaFecha')){
                        var divinputCargoconsultaFechaDelete = document.getElementById("divinputCargoconsultaFecha");
                        divinputCargoconsultaFechaDelete.parentNode.removeChild(divinputCargoconsultaFechaDelete);
                    }

                    // Creamos nuestro Formulario con los datos a insertar en Cargoconsulta
                    var form = document.getElementById('CargoconsultaForm');
                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdservicio = document.createElement('div');
                    divinputIdservicio.className = "input-field";
                    divinputIdservicio.setAttribute ( 'id', 'divinputIdservicio' );
                    var inputIdservicio = document.createElement('input');
                    inputIdservicio.setAttribute ( 'id', 'idservicio' );
                    inputIdservicio.setAttribute ( 'type', 'hidden' );
                    inputIdservicio.setAttribute ( 'name', 'idservicio' );
                    inputIdservicio.setAttribute ( 'value', values.idservicio );
                    divinputIdservicio.appendChild(inputIdservicio)
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaTipo = document.createElement('div');
                    divinputCargoconsultaTipo.className = "input-field";
                    divinputCargoconsultaTipo.setAttribute ( 'id', 'divinputCargoconsultaTipo' );
                    var inputCargoconsultaTipo = document.createElement('input');
                    inputCargoconsultaTipo.setAttribute ( 'id', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaTipo.setAttribute ( 'name', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'value', values.cargoconsulta_tipo );
                    divinputCargoconsultaTipo.appendChild(inputCargoconsultaTipo);
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaFecha = document.createElement('div');
                    divinputCargoconsultaFecha.className = "input-field";
                    divinputCargoconsultaFecha.setAttribute ( 'id', 'divinputCargoconsultaFecha' );
                    var inputCargoconsultaFecha = document.createElement('input');
                    inputCargoconsultaFecha.setAttribute ( 'id', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaFecha.setAttribute ( 'name', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'value', values.cargoconsulta_fecha );
                    divinputCargoconsultaFecha.appendChild(inputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaTipo);
                    form.appendChild(divinputIdservicio);
                });
            });
        },
        error: function(){
            $('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar buscar</div>')
        }
    });

    return false;
});

function generaTablaBuscarConsultaArticulo(ordencompradetalleArray) {

    // Obtener la referencia del elemento div con id = tablaCargoconsultaArticulo
    var div = document.getElementById("tablaCargoconsultaArticulo");
    div.innerHTML = div;
    // Crea un elemento <table> y un elemento <thead> y <tbody>
    var tabla   = document.createElement("table");
    tabla.className = "hoverable striped";
    var tblHead = document.createElement("thead");
    var tblBody = document.createElement("tbody");
    var thArray = ['Existencias', 'Articulo', 'Descripción', 'Costo', 'Salida']

    // Crea las celdas
    for (var i = 0; i < 1; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <th> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <th>, ubica el elemento <th> al final
            // de la hilera de la tabla
            var celda = document.createElement("th");
            var textoCelda = document.createTextNode(thArray[j]);
            celda.appendChild(textoCelda);
            hilera.appendChild(celda);
        }

        // agrega la hilera al final de la tabla (al final del elemento tblHead)
        tblHead.appendChild(hilera);
    }

    // posiciona el <thead> debajo del elemento <table>
    tabla.appendChild(tblHead);

    // Crea las celdas
    for (var i = 0; i < ordencompradetalleArray.length; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");
        hilera.className = "pointer";
        // Le agregamos un id a la entidad <th>
        hilera.setAttribute('id', 'entidadArticulo-' + ordencompradetalleArray[i]["idordencompradetalle"])

        for (var j = 0; j < thArray.length; j++) {

            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("td");

            if(j == 0){
                var textoCelda = document.createTextNode(ordencompradetalleArray[i]["existencia"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 1){
                var textoCelda = document.createTextNode(ordencompradetalleArray[i]["articulo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 2){
                var textoCelda = document.createTextNode(ordencompradetalleArray[i]["descripcion"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 3){
                var textoCelda = document.createTextNode("$"+ordencompradetalleArray[i]["costo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 4){
                var textoCelda = document.createTextNode(ordencompradetalleArray[i]["salida"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
        }

        // agrega la hilera al final de la tabla (al final del elemento tblbody)
        tblBody.appendChild(hilera);
    }

    // posiciona el <tbody> debajo del elemento <table>
    tabla.appendChild(tblBody);

    // appends <table> into <div>
    div.appendChild(tabla);
}

function generaTablaBuscarConsultaServicio(servicioArray) {

    // Obtener la referencia del elemento div con id = tablaCargoconsultaArticulo
    var div = document.getElementById("tablaCargoconsultaServicio");
    div.innerHTML = div;
    // Crea un elemento <table> y un elemento <thead> y <tbody>
    var tabla   = document.createElement("table");
    tabla.className = "hoverable striped";
    var tblHead = document.createElement("thead");
    var tblBody = document.createElement("tbody");
    var thArray = ['Servicio', 'Descripción', 'Costo']

    // Crea las celdas
    for (var i = 0; i < 1; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <th> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <th>, ubica el elemento <th> al final
            // de la hilera de la tabla
            var celda = document.createElement("th");
            var textoCelda = document.createTextNode(thArray[j]);
            celda.appendChild(textoCelda);
            hilera.appendChild(celda);
        }

        // agrega la hilera al final de la tabla (al final del elemento tblHead)
        tblHead.appendChild(hilera);
    }

    // posiciona el <thead> debajo del elemento <table>
    tabla.appendChild(tblHead);

    // Crea las celdas
    for (var i = 0; i < servicioArray.length; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");
        hilera.className = "pointer";
        // Le agregamos un id a la entidad <th>
        hilera.setAttribute('id', 'entidadServicio-' + servicioArray[i]["idservicio"])

        for (var j = 0; j < thArray.length; j++) {

            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("td");

            if(j == 0){
                var textoCelda = document.createTextNode(servicioArray[i]["servicio_nombre"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 1){
                var textoCelda = document.createTextNode(servicioArray[i]["servicio_descripcion"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 2){
                var textoCelda = document.createTextNode(servicioArray[i]["servicio_precio"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
        }

        // agrega la hilera al final de la tabla (al final del elemento tblbody)
        tblBody.appendChild(hilera);
    }

    // posiciona el <tbody> debajo del elemento <table>
    tabla.appendChild(tblBody);

    // appends <table> into <div>
    div.appendChild(tabla);
}

$("#guardarCargoconsultaArticulo").click(function() {

    // Actializar existencias
    //Obtenemos el valor del selector de consulta
    var idordencompradetalle = $("input#idordencompradetalle").val();
    // Actializar existencias

    //Obtenemos el valor del selector de consulta
    var idconsulta = $("input#idconsulta").val();
    //Obtenemos el valor del selector de lugarinventario
    var idlugarinventario = $("input#idlugarinventario").val();
    //Obtenemos el valor del campo cargoconsulta_tipo
    var cargoconsulta_tipo = $("input#cargoconsulta_tipo").val();
    //Obtenemos el valor del campo cargoconsulta_fecha
    var cargoconsulta_fecha = $("input#cargoconsulta_fecha").val();
    //Obtenemos el valor del campo cantidad
    var cantidad = $("select#cantidad").val();

    if(cantidad == null){
        //$('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text red accent-2 error-modal-ajax">Error al intentar agregar. Ya no hay artículos en existencia.</div>')
        alert("Error al intentar agregar. Ya no hay artículos en existencia");
        return false;
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'idconsulta=' + idconsulta + '&idlugarinventario=' + idlugarinventario + '&cargoconsulta_tipo=' + cargoconsulta_tipo + '&cargoconsulta_fecha=' + cargoconsulta_fecha + '&cantidad=' + cantidad;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            //$('#cargos').prepend('<div class="card-panel #00086E-text green accent-2 guardado-ajax"">Cargo guardada exitosamente</div>')
            //$('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text green accent-2 guardado-modal-ajax"">Cargo agregado exitosamente</div>')
            alert("Cargo agregado exitosamente");

            //console.log(data.cargoconsultaArray);
            cargoconsultaArray = []
            var cargoconsultaEntity = data.cargoconsultaArray
            $.each( cargoconsultaEntity, function( key, value ) {
                cargoconsultaArray.push({
                    "idcargoconsulta" : value.idcargoconsulta,
                    "cantidad" : value.cantidad,
                    "articulo" : value.articulo,
                    "descripcion" : value.descripcion,
                    "salida" : value.salida,
                    "fechahora" : value.fechahora,
                    "costo" : value.costo,
                    "subtotal" : value.subtotal
                });
            });

            if ($('#cargoconsultaArticuloResult').hasClass('hiddendiv')){
                $('#cargoconsultaArticuloResult').removeClass('hiddendiv')
            }

            tablaCargoconsultaArticuloAgregadoModal(cargoconsultaArray);
            tablaCargoconsultaArticuloAgregado(cargoconsultaArray);
            // Refrescamos
            buscarCargoconsultaArticulo(idordencompradetalle);

        },
        error: function(){
            //$('#cargos').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar guardar</div>')
            //$('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text red accent-2 error-modal-ajax">Error al intentar agregar</div>')
            alert("Error al intentar agregar");
        }
    });

    return false;
});

$("#guardarCargoconsultaServicio").click(function() {

    //Obtenemos el valor del selector de consulta
    var idconsulta = $("input#idconsulta").val();
    //Obtenemos el valor del selector de lugarinventario
    var idservicio = $("input#idservicio").val();
    //Obtenemos el valor del campo cargoconsulta_tipo
    var cargoconsulta_tipo = $("input#cargoconsulta_tipo").val();
    //Obtenemos el valor del campo cargoconsulta_fecha
    var cargoconsulta_fecha = $("input#cargoconsulta_fecha").val();
    //Obtenemos el valor del campo cantidad
    var cantidad = $("input#cantidad").val();

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'idconsulta=' + idconsulta + '&idservicio=' + idservicio + '&cargoconsulta_tipo=' + cargoconsulta_tipo + '&cargoconsulta_fecha=' + cargoconsulta_fecha + '&cantidad=' + cantidad;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            //$('#cargos').prepend('<div class="card-panel #00086E-text green accent-2 guardado-ajax"">Cargo guardada exitosamente</div>')
            //$('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text green accent-2 guardado-modal-ajax"">Cargo agregado exitosamente</div>')
            alert("Cargo agregado exitosamente");

            //console.log(data.cargoconsultaArray);
            cargoconsultaArray = []
            var cargoconsultaEntity = data.cargoconsultaArray
            $.each( cargoconsultaEntity, function( key, value ) {
                cargoconsultaArray.push({
                    "idcargoconsulta" : value.idcargoconsulta,
                    "status" : value.status,
                    "cantidad" : value.cantidad,
                    "servicio" : value.servicio,
                    "descripcion" : value.descripcion,
                    "costo" : value.costo,
                    "subtotal" : value.subtotal,
                    "fechahora" : value.fechahora
                });
            });

            if ($('#cargoconsultaServicioResult').hasClass('hiddendiv')){
                $('#cargoconsultaServicioResult').removeClass('hiddendiv')
            }

            tablaCargoconsultaServicioAgregadoModal(cargoconsultaArray);
            tablaCargoconsultaServicioAgregado(cargoconsultaArray);
            // Refrescamos
            buscarCargoconsultaServicio(idservicio);

        },
        error: function(){
            //$('#cargos').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar guardar</div>')
            //$('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text red accent-2 error-modal-ajax">Error al intentar agregar</div>')
            alert("Error al intentar agregar");
        }
    });

    return false;
});

$("#guardarCargoadmisionArticulo").click(function() {

    //Obtenemos el valor del selector de admision
    var idadmision = $("input#idadmision").val();
    //Obtenemos el valor del selector de servicio
    var idservicio = $("select#idservicio").val();
    //Validamos el campo idservicio, simplemente miramos que no esté vacío
    if (idservicio == "") {
        if ($('span#idservicio_error').hasClass('hidden')){
            $('span#idservicio_error').removeClass('hidden');
            $("span#idservicio_error").show();
            $("span#idservicio").focus();
        }
        return false;
    }else{
        $("span#idservicio_error").hide();
    }

    //Obtenemos el valor del campo cargoadmision_tipo
    var cargoadmision_tipo = $("input#cargoadmision_tipo").val();

    //Obtenemos el valor del campo cargoadmision_fecha
    var cargoadmision_fecha = $("input#cargoadmision_fecha").val();
    //Validamos el campo cargoadmision_fecha, simplemente miramos que no esté vacío
    if (cargoadmision_fecha == "") {
        if ($('span#cargoadmision_fecha_error').hasClass('hidden')){
            $('span#cargoadmision_fecha_error').removeClass('hidden');
            $("span#cargoadmision_fecha_error").show();
            $("span#cargoadmision_fecha").focus();
        }
        return false;
    }else{
        $("span#cargoadmision_fecha_error").hide();
    }

    //Obtenemos el valor del campo cantidad
    var cargoadmision_cantidad = $("input#cargoadmision_cantidad").val();
    //Validamos el campo cantidad, simplemente miramos que no esté vacío
    if (cargoadmision_cantidad == "") {
        if ($('span#ccargoadmision_antidad_error').hasClass('hidden')){
            $('span#cargoadmision_cantidad_error').removeClass('hidden');
            $("span#cargoadmision_cantidad_error").show();
            $("span#cargoadmision_cantidad").focus();
        }
        return false;
    }else{
        $("span#cargoadmision_cantidad_error").hide();
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'idadmision=' + idadmision + '&idservicio=' + idservicio + '&cargoadmision_tipo=' + cargoadmision_tipo + '&cargoadmision_fecha=' + cargoadmision_fecha + '&cargoadmision_cantidad=' + cargoadmision_cantidad;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        data: dataString,
        success: function() {
            $("#create-modal-cargoadmision").hide();
            //$('#cargos').prepend('<div class="card-panel #00086E-text green accent-2 guardado-ajax">Cargo guardada exitosamente</div>')
        },
        error: function(){
            //$('#cargos').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar guardar</div>')
        }
    });

    return false;
});
$("#guardarCargoadmisionServicio").click(function() {

    //Obtenemos el valor del selector de admision
    var idadmision = $("input#idadmision").val();
    //Obtenemos el valor del selector de servicio
    var idservicio = $("select#idservicio").val();
    //Validamos el campo idservicio, simplemente miramos que no esté vacío
    if (idservicio == "") {
        if ($('span#idservicio_error').hasClass('hidden')){
            $('span#idservicio_error').removeClass('hidden');
            $("span#idservicio_error").show();
            $("span#idservicio").focus();
        }
        return false;
    }else{
        $("span#idservicio_error").hide();
    }

    //Obtenemos el valor del campo cargoadmision_tipo
    var cargoadmision_tipo = $("input#cargoadmision_tipo").val();

    //Obtenemos el valor del campo cargoadmision_fecha
    var cargoadmision_fecha = $("input#cargoadmision_fecha").val();
    //Validamos el campo cargoadmision_fecha, simplemente miramos que no esté vacío
    if (cargoadmision_fecha == "") {
        if ($('span#cargoadmision_fecha_error').hasClass('hidden')){
            $('span#cargoadmision_fecha_error').removeClass('hidden');
            $("span#cargoadmision_fecha_error").show();
            $("span#cargoadmision_fecha").focus();
        }
        return false;
    }else{
        $("span#cargoadmision_fecha_error").hide();
    }

    //Obtenemos el valor del campo cantidad
    var cargoadmision_cantidad = $("input#cargoadmision_cantidad").val();
    //Validamos el campo cantidad, simplemente miramos que no esté vacío
    if (cargoadmision_cantidad == "") {
        if ($('span#ccargoadmision_antidad_error').hasClass('hidden')){
            $('span#cargoadmision_cantidad_error').removeClass('hidden');
            $("span#cargoadmision_cantidad_error").show();
            $("span#cargoadmision_cantidad").focus();
        }
        return false;
    }else{
        $("span#cargoadmision_cantidad_error").hide();
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'idadmision=' + idadmision + '&idservicio=' + idservicio + '&cargoadmision_tipo=' + cargoadmision_tipo + '&cargoadmision_fecha=' + cargoadmision_fecha + '&cargoadmision_cantidad=' + cargoadmision_cantidad;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        data: dataString,
        success: function() {
            $("#create-modal-cargoadmision").hide();
            //$('#cargos').prepend('<div class="card-panel #00086E-text green accent-2 guardado-ajax">Cargo guardada exitosamente</div>')
        },
        error: function(){
            //$('#cargos').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar guardar</div>')
        }
    });

    return false;
});

// Esta función no está en uso
function anticipoTotalStatus(cargoconsultaArray){
    var divRow   = document.createElement("div");
    divRow.className = "row";
    var divCols9   = document.createElement("div");
    divCols9.className = "col s9";
    var spanTotal   = document.createElement("span");
    spanTotal.className = "left";
    var spanAnticipo   = document.createElement("span");
    spanAnticipo.style = "margin-left: 40px;";
    var spanStatus   = document.createElement("span");
    spanStatus.style = "margin-left: 40px;";
    var divCols3   = document.createElement("div");
    divCols3.className = "col s3";
    var a = document.createElement("a");
    a.className = "tooltipped right";
    a.setAttribute ( 'data-position', 'right' );
    a.setAttribute ( 'data-tooltip', 'Editar' );
    a.setAttribute ( 'href', '#view-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
}
function tablaCargoconsultaArticuloAgregadoModal(cargoconsultaArray) {

    // Obtener la referencia del elemento div con id = tablaCargoconsultaArticuloAgregado
    var div = document.getElementById("tablaCargoconsultaArticuloAgregado");
    div.innerHTML = div;
    // Creamos el elemento <table>
    var tabla   = document.createElement("table");
    // Agregamos clases el elemento <table>
    tabla.className = "hoverable striped";
    // Creamos el elemento <thead>
    var tblHead = document.createElement("thead");
    // Creamos el elemento <tbody>
    var tblBody = document.createElement("tbody");

    // Creamos un array con las columnas de nuestra tabla
    var thArray = ['Cantidad', 'Articulo', 'Descripción', 'Salida', 'Fecha/hora', 'Costo', 'Subtotal', 'Opciones']

    // Crea las celdas
    for (var i = 0; i < 1; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("th");
            var textoCelda = document.createTextNode(thArray[j]);
            celda.appendChild(textoCelda);
            hilera.appendChild(celda);
        }

        // agrega la hilera al final de la tabla (al final del elemento tblHead)
        tblHead.appendChild(hilera);
    }

    // posiciona el <thead> debajo del elemento <tbody>
    tabla.appendChild(tblHead);

    // Crea las celdas
    for (var i = 0; i < cargoconsultaArray.length; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("td");

            if(j == 0){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["cantidad"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 1){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["articulo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 2){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["descripcion"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 3){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["salida"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 4){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["fechahora"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 5){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["costo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 6){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["subtotal"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 7){
                var link1 = document.createElement("a");
                link1.className = "tooltipped modal-trigger";
                link1.setAttribute ( 'data-position', 'left' );
                link1.setAttribute ( 'data-tooltip', 'Visualizar' );
                link1.setAttribute ( 'href', '#view-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var vista = document.createElement("i");
                vista.className = "tiny mdi-image-remove-red-eye";
                var link2 = document.createElement("a");
                link2.className = "tooltipped";
                link2.setAttribute ( 'data-position', 'right' );
                link2.setAttribute ( 'data-tooltip', 'Editar' );
                link2.setAttribute ( 'href', '#edit-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var editar = document.createElement("i");
                editar.className = "tiny mdi-action-assignment";
                var link3 = document.createElement("a");
                link3.className = "tooltipped";
                link3.setAttribute ( 'data-position', 'right' );
                link3.setAttribute ( 'data-tooltip', 'Eliminar' );
                link3.setAttribute ( 'href', '#delete-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var eliminar = document.createElement("i");
                eliminar.className = "tiny mdi-action-delete";
                celda.appendChild(link1);
                celda.appendChild(vista);
                celda.appendChild(link2);
                celda.appendChild(editar);
                celda.appendChild(link3);
                celda.appendChild(eliminar);
                hilera.appendChild(celda);
            }
        }

        // agrega la hilera al final de la tabla (al final del elemento tblbody)
        tblBody.appendChild(hilera);
    }

    // posiciona el <tbody> debajo del elemento <table>
    tabla.appendChild(tblBody);

    // appends <table> into <body>
    div.appendChild(tabla);

}
function tablaCargoconsultaServicioAgregadoModal(cargoconsultaArray) {

    // Obtener la referencia del elemento div con id = tablaCargoconsultaServicioAgregado
    var div = document.getElementById("tablaCargoconsultaServicioAgregado");
    div.innerHTML = div;
    // Creamos el elemento <table>
    var tabla   = document.createElement("table");
    // Agregamos clases el elemento <table>
    tabla.className = "hoverable striped";
    // Creamos el elemento <thead>
    var tblHead = document.createElement("thead");
    // Creamos el elemento <tbody>
    var tblBody = document.createElement("tbody");

    // Creamos un array con las columnas de nuestra tabla
    var thArray = ['Cantidad', 'Servicio', /*'Descripción',*/ 'Costo', 'Subtotal', 'Fecha/hora', 'Opciones']

    // Crea las celdas
    for (var i = 0; i < 1; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("th");
            var textoCelda = document.createTextNode(thArray[j]);
            celda.appendChild(textoCelda);
            hilera.appendChild(celda);
        }

        // agrega la hilera al final de la tabla (al final del elemento tblHead)
        tblHead.appendChild(hilera);
    }

    // posiciona el <thead> debajo del elemento <tbody>
    tabla.appendChild(tblHead);

    // Crea las celdas
    for (var i = 0; i < cargoconsultaArray.length; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("td");

            if(j == 0){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["cantidad"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 1){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["servicio"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            /*
            if(j == 2){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["descripcion"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            */
            if(j == 2){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["costo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 3){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["subtotal"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 4){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["fechahora"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 5){
                var link1 = document.createElement("a");
                link1.className = "tooltipped modal-trigger";
                link1.setAttribute ( 'data-position', 'left' );
                link1.setAttribute ( 'data-tooltip', 'Visualizar' );
                link1.setAttribute ( 'href', '#view-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var vista = document.createElement("i");
                vista.className = "tiny mdi-image-remove-red-eye";
                var link2 = document.createElement("a");
                link2.className = "tooltipped";
                link2.setAttribute ( 'data-position', 'right' );
                link2.setAttribute ( 'data-tooltip', 'Editar' );
                link2.setAttribute ( 'href', '#edit-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var editar = document.createElement("i");
                editar.className = "tiny mdi-action-assignment";
                var link3 = document.createElement("a");
                link3.className = "tooltipped";
                link3.setAttribute ( 'data-position', 'right' );
                link3.setAttribute ( 'data-tooltip', 'Eliminar' );
                link3.setAttribute ( 'href', '#delete-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var eliminar = document.createElement("i");
                eliminar.className = "tiny mdi-action-delete";
                celda.appendChild(link1);
                celda.appendChild(vista);
                celda.appendChild(link2);
                celda.appendChild(editar);
                celda.appendChild(link3);
                celda.appendChild(eliminar);
                hilera.appendChild(celda);
            }
        }

        // agrega la hilera al final de la tabla (al final del elemento tblbody)
        tblBody.appendChild(hilera);
    }

    // posiciona el <tbody> debajo del elemento <table>
    tabla.appendChild(tblBody);

    // appends <table> into <body>
    div.appendChild(tabla);

}
function buscarCargoconsultaArticulo(idordencompradetalle){

    //Obtenemos el valor del selector de lugarinventario
    var busquedaArticulo = $("input#busquedaArticulo").val();

    //Obtenemos el valor del selector de lugarinventario
    var cargoconsultaarticulo_by = $("select#cargoconsultaarticulo_by").val();
    //Validamos el campo cargoconsultaarticulo_by, simplemente miramos que no esté vacío
    if (cargoconsultaarticulo_by == "") {
        if ($('span#cargoconsultaarticulo_by_error').hasClass('hidden')){
            $('span#cargoconsultaarticulo_by_error').removeClass('hidden');
            $("span#cargoconsultaarticulo_by_error").show();
            $("span#cargoconsultaarticulo_by").focus();
        }
        return false;
    }else{
        $("span#cargoconsultaarticulo_by_error").hide();
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'cargoconsultaarticulo_by=' + cargoconsultaarticulo_by + '&busquedaArticulo=' + busquedaArticulo ;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            ordencompradetalleArray = []
            var ordencompradetalleEntity = data.ordencompradetalleArray;
            $.each( ordencompradetalleEntity, function( key, value ) {
                ordencompradetalleArray.push({
                    "idordencompradetalle" : value.idordencompradetalle,
                    "idlugarinventario" : value.idlugarinventario,
                    "cargoconsulta_tipo" : value.cargoconsulta_tipo,
                    "cargoconsulta_fecha" : value.cargoconsulta_fecha,
                    "caducidad" : value.ordencompradetalle_caducidad,
                    "existencia" : value.existencia,
                    "articulo" : value.articulo,
                    "descripcion" : value.descripcion,
                    "costo" : value.costo,
                    "salida" : value.salida
                });
            });

            // Creamos nuestra tabla de colecciones
            generaTablaBuscarConsultaArticulo(ordencompradetalleArray);

            // Seleccionamos un item de nuestra tabla de colecciones y construimos la entidad para agregarla como cargoconsulta
            $.each(ordencompradetalleArray, function(keys, values){

                // Mantenemos el foco en el artículo que se esta agregando
                if(idordencompradetalle == values.idordencompradetalle){
                    if ($('#fieldsetCargoconsultaArticulo').hasClass('hiddendiv')){
                        $('#fieldsetCargoconsultaArticulo').removeClass('hiddendiv')
                    }
                    var br   = document.createElement("br");
                    var br2   = document.createElement("br");
                    var br3   = document.createElement("br");
                    var br4   = document.createElement("br");
                    var br5   = document.createElement("br");
                    // Creamos el input de cantidad de tipo select
                    var divinputCantidad = document.createElement('div');
                    divinputCantidad.className = "input-field";
                    divinputCantidad.setAttribute ( 'id', 'divinputCantidad' );
                    var select = document.createElement('select');
                    select.style.display = "inline";
                    select.style.width = "auto";
                    select.style.height = "auto";
                    select.setAttribute ( 'id', 'cantidad' );
                    // agregamos los valores <option> a seleccionar
                    for($i=1; $i<=values.existencia; $i++){
                        var selectOption = new Option($i,$i);
                        select.appendChild(selectOption);
                    }
                    // agregamos las options en nuestro select
                    divinputCantidad.appendChild(select);

                    // Creamos la entidad textual lista para agregar al cargoconsulta
                    var div = document.getElementById("fieldsetCargoconsultaArticuloEntity");
                    div.innerHTML = div;
                    var textoArticulo = document.createTextNode("Artículo: "+values.articulo);
                    var textoDescripcion = document.createTextNode("Descrpción: "+values.descripcion);
                    var textoCaducidad = document.createTextNode("Caducidad: "+values.caducidad);
                    var textoDisponibleEn = document.createTextNode("Disponible en: "+values.salida);
                    var textoExistencia = document.createTextNode("Existencias: "+values.existencia);
                    var textoCantidad = document.createTextNode("Cantidad: ");
                    div.appendChild(textoArticulo);
                    div.appendChild(br);
                    div.appendChild(textoDescripcion);
                    div.appendChild(br2);
                    div.appendChild(textoCaducidad);
                    div.appendChild(br3);
                    div.appendChild(textoDisponibleEn);
                    div.appendChild(br4);
                    div.appendChild(textoExistencia);
                    div.appendChild(br5);
                    div.appendChild(textoCantidad);
                    div.appendChild(select);

                    // Actializar existencias

                    // El input ordencompradetalle solamente lo necesitamos para actualizar nuestra entidad artículo antes de agregar el cargo.
                    // Si el formulario ya tiene el input de idordencompradetalle lo eliminamos
                    if(document.getElementById('divinputIdordencompradetalle')){
                        var divinputIdordencompradetalleDelete = document.getElementById("divinputIdordencompradetalle");
                        divinputIdordencompradetalleDelete.parentNode.removeChild(divinputIdordencompradetalleDelete);
                    }
                    // Actializar existencias

                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputIdlugarinventario')){
                        var divinputIdlugarinventarioDelete = document.getElementById("divinputIdlugarinventario");
                        divinputIdlugarinventarioDelete.parentNode.removeChild(divinputIdlugarinventarioDelete);
                    }
                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputCargoconsultaTipo')){
                        var divinputCargoconsultaTipoDelete = document.getElementById("divinputCargoconsultaTipo");
                        divinputCargoconsultaTipoDelete.parentNode.removeChild(divinputCargoconsultaTipoDelete);
                    }
                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputCargoconsultaFecha')){
                        var divinputCargoconsultaFechaDelete = document.getElementById("divinputCargoconsultaFecha");
                        divinputCargoconsultaFechaDelete.parentNode.removeChild(divinputCargoconsultaFechaDelete);
                    }
                    // Creamos nuestro Formulario con los datos a insertar en Cargoconsulta
                    var form = document.getElementById('CargoconsultaForm');

                    // Actializar existencias
                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdordencompradetalle = document.createElement('div');
                    divinputIdordencompradetalle.className = "input-field";
                    divinputIdordencompradetalle.setAttribute ( 'id', 'divinputIdordencompradetalle' );
                    var inputIdordencompradetalle = document.createElement('input');
                    inputIdordencompradetalle.setAttribute ( 'id', 'idordencompradetalle' );
                    inputIdordencompradetalle.setAttribute ( 'type', 'hidden' );
                    inputIdordencompradetalle.setAttribute ( 'name', 'idordencompradetalle' );
                    inputIdordencompradetalle.setAttribute ( 'value', values.idordencompradetalle );
                    divinputIdordencompradetalle.appendChild(inputIdordencompradetalle)
                    // Actializar existencias

                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdlugarinventario = document.createElement('div');
                    divinputIdlugarinventario.className = "input-field";
                    divinputIdlugarinventario.setAttribute ( 'id', 'divinputIdlugarinventario' );
                    var inputIdlugarinventario = document.createElement('input');
                    inputIdlugarinventario.setAttribute ( 'id', 'idlugarinventario' );
                    inputIdlugarinventario.setAttribute ( 'type', 'hidden' );
                    inputIdlugarinventario.setAttribute ( 'name', 'idlugarinventario' );
                    inputIdlugarinventario.setAttribute ( 'value', values.idlugarinventario );
                    divinputIdlugarinventario.appendChild(inputIdlugarinventario)
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaTipo = document.createElement('div');
                    divinputCargoconsultaTipo.className = "input-field";
                    divinputCargoconsultaTipo.setAttribute ( 'id', 'divinputCargoconsultaTipo' );
                    var inputCargoconsultaTipo = document.createElement('input');
                    inputCargoconsultaTipo.setAttribute ( 'id', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaTipo.setAttribute ( 'name', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'value', values.cargoconsulta_tipo );
                    divinputCargoconsultaTipo.appendChild(inputCargoconsultaTipo);
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaFecha = document.createElement('div');
                    divinputCargoconsultaFecha.className = "input-field";
                    divinputCargoconsultaFecha.setAttribute ( 'id', 'divinputCargoconsultaFecha' );
                    var inputCargoconsultaFecha = document.createElement('input');
                    inputCargoconsultaFecha.setAttribute ( 'id', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaFecha.setAttribute ( 'name', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'value', values.cargoconsulta_fecha );
                    divinputCargoconsultaFecha.appendChild(inputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaTipo);
                    form.appendChild(divinputIdlugarinventario);
                    form.appendChild(divinputIdordencompradetalle);
                }

                // Si dan clic a una entidad de la colección
                $("#entidadArticulo-"+values.idordencompradetalle).click(function(){
                    if ($('#fieldsetCargoconsultaArticulo').hasClass('hiddendiv')){
                        $('#fieldsetCargoconsultaArticulo').removeClass('hiddendiv')
                    }
                    var br   = document.createElement("br");
                    var br2   = document.createElement("br");
                    var br3   = document.createElement("br");
                    var br4   = document.createElement("br");
                    var br5   = document.createElement("br");
                    // Creamos el input de cantidad de tipo select
                    var divinputCantidad = document.createElement('div');
                    divinputCantidad.className = "input-field";
                    divinputCantidad.setAttribute ( 'id', 'divinputCantidad' );
                    var select = document.createElement('select');
                    select.style.display = "inline";
                    select.style.width = "auto";
                    select.style.height = "auto";
                    select.setAttribute ( 'id', 'cantidad' );
                    // agregamos los valores <option> a seleccionar
                    for($i=1; $i<=values.existencia; $i++){
                        var selectOption = new Option($i,$i);
                        select.appendChild(selectOption);
                    }
                    // agregamos las options en nuestro select
                    divinputCantidad.appendChild(select);

                    // Creamos la entidad textual lista para agregar al cargoconsulta
                    var div = document.getElementById("fieldsetCargoconsultaArticuloEntity");
                    div.innerHTML = div;
                    var textoArticulo = document.createTextNode("Artículo: "+values.articulo);
                    var textoDescripcion = document.createTextNode("Descrpción: "+values.descripcion);
                    var textoCaducidad = document.createTextNode("Caducidad: "+values.caducidad);
                    var textoDisponibleEn = document.createTextNode("Disponible en: "+values.salida);
                    var textoExistencia = document.createTextNode("Existencias: "+values.existencia);
                    var textoCantidad = document.createTextNode("Cantidad: ");
                    div.appendChild(textoArticulo);
                    div.appendChild(br);
                    div.appendChild(textoDescripcion);
                    div.appendChild(br2);
                    div.appendChild(textoCaducidad);
                    div.appendChild(br3);
                    div.appendChild(textoDisponibleEn);
                    div.appendChild(br4);
                    div.appendChild(textoExistencia);
                    div.appendChild(br5);
                    div.appendChild(textoCantidad);
                    div.appendChild(select);

                    // Actializar existencias

                    // El input ordencompradetalle solamente lo necesitamos para actualizar nuestra entidad artículo antes de agregar el cargo.
                    // Si el formulario ya tiene el input de idordencompradetalle lo eliminamos
                    if(document.getElementById('divinputIdordencompradetalle')){
                        var divinputIdordencompradetalleDelete = document.getElementById("divinputIdordencompradetalle");
                        divinputIdordencompradetalleDelete.parentNode.removeChild(divinputIdordencompradetalleDelete);
                    }
                    // Actializar existencias

                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputIdlugarinventario')){
                        var divinputIdlugarinventarioDelete = document.getElementById("divinputIdlugarinventario");
                        divinputIdlugarinventarioDelete.parentNode.removeChild(divinputIdlugarinventarioDelete);
                    }
                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputCargoconsultaTipo')){
                        var divinputCargoconsultaTipoDelete = document.getElementById("divinputCargoconsultaTipo");
                        divinputCargoconsultaTipoDelete.parentNode.removeChild(divinputCargoconsultaTipoDelete);
                    }
                    // Si el formulario ya tiene el input de idlugarinventario lo eliminamos
                    if(document.getElementById('divinputCargoconsultaFecha')){
                        var divinputCargoconsultaFechaDelete = document.getElementById("divinputCargoconsultaFecha");
                        divinputCargoconsultaFechaDelete.parentNode.removeChild(divinputCargoconsultaFechaDelete);
                    }
                    // Creamos nuestro Formulario con los datos a insertar en Cargoconsulta
                    var form = document.getElementById('CargoconsultaForm');

                    // Actializar existencias
                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdordencompradetalle = document.createElement('div');
                    divinputIdordencompradetalle.className = "input-field";
                    divinputIdordencompradetalle.setAttribute ( 'id', 'divinputIdordencompradetalle' );
                    var inputIdordencompradetalle = document.createElement('input');
                    inputIdordencompradetalle.setAttribute ( 'id', 'idordencompradetalle' );
                    inputIdordencompradetalle.setAttribute ( 'type', 'hidden' );
                    inputIdordencompradetalle.setAttribute ( 'name', 'idordencompradetalle' );
                    inputIdordencompradetalle.setAttribute ( 'value', values.idordencompradetalle );
                    divinputIdordencompradetalle.appendChild(inputIdordencompradetalle)
                    // Actializar existencias

                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdlugarinventario = document.createElement('div');
                    divinputIdlugarinventario.className = "input-field";
                    divinputIdlugarinventario.setAttribute ( 'id', 'divinputIdlugarinventario' );
                    var inputIdlugarinventario = document.createElement('input');
                    inputIdlugarinventario.setAttribute ( 'id', 'idlugarinventario' );
                    inputIdlugarinventario.setAttribute ( 'type', 'hidden' );
                    inputIdlugarinventario.setAttribute ( 'name', 'idlugarinventario' );
                    inputIdlugarinventario.setAttribute ( 'value', values.idlugarinventario );
                    divinputIdlugarinventario.appendChild(inputIdlugarinventario)
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaTipo = document.createElement('div');
                    divinputCargoconsultaTipo.className = "input-field";
                    divinputCargoconsultaTipo.setAttribute ( 'id', 'divinputCargoconsultaTipo' );
                    var inputCargoconsultaTipo = document.createElement('input');
                    inputCargoconsultaTipo.setAttribute ( 'id', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaTipo.setAttribute ( 'name', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'value', values.cargoconsulta_tipo );
                    divinputCargoconsultaTipo.appendChild(inputCargoconsultaTipo);
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaFecha = document.createElement('div');
                    divinputCargoconsultaFecha.className = "input-field";
                    divinputCargoconsultaFecha.setAttribute ( 'id', 'divinputCargoconsultaFecha' );
                    var inputCargoconsultaFecha = document.createElement('input');
                    inputCargoconsultaFecha.setAttribute ( 'id', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaFecha.setAttribute ( 'name', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'value', values.cargoconsulta_fecha );
                    divinputCargoconsultaFecha.appendChild(inputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaTipo);
                    form.appendChild(divinputIdlugarinventario);
                    form.appendChild(divinputIdordencompradetalle);
                });
            });
        },
        error: function(){
            $('#modalCargoconsultaArticulo').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar buscar</div>')
        }
    });

    return false;
};
function buscarCargoconsultaServicio(idservicio){

    //Obtenemos el valor del selector de lugarinventario
    var busquedaServicio = $("input#busquedaServicio").val();

    //Obtenemos el valor del selector de lugarinventario
    var cargoconsultaservicio_by = $("select#cargoconsultaservicio_by").val();
    //Validamos el campo idlugarinventario, simplemente miramos que no esté vacío
    if (cargoconsultaservicio_by == "") {
        if ($('span#cargoconsultaservicio_by_error').hasClass('hidden')){
            $('span#cargoconsultaservicio_by_error').removeClass('hidden');
            $("span#cargoconsultaservicio_by_error").show();
            $("span#cargoconsultaservicio_by").focus();
        }
        return false;
    }else{
        $("span#cargoconsultaservicio_by_error").hide();
    }

    //Construimos la variable que se guardará en el data del Ajax para pasar a la url que procesará los datos
    var dataString = 'cargoconsultaservicio_by=' + cargoconsultaservicio_by + '&busquedaServicio=' + busquedaServicio ;

    $.ajax({
        type: "POST",
        url: "<?php $this->url('pacientes', array('action'=>'ver', 'id' => $pacienteEntity->getIdpaciente()));?>",
        dataType : 'json',
        data: dataString,
        jsonpCallback: 'callback',
        success: function(data) {
            servicioArray = []
            var servicioEntity = data.servicioArray
            $.each( servicioEntity, function( key, value ) {
                servicioArray.push({
                    "idservicio" : value.idservicio,
                    "cargoconsulta_tipo" : value.cargoconsulta_tipo,
                    "cargoconsulta_fecha" : value.cargoconsulta_fecha,
                    "servicio_nombre" : value.servicio_nombre,
                    "servicio_descripcion" : value.servicio_descripcion,
                    "servicio_precio" : value.servicio_precio
                });
            });

            // Creamos nuestra tabla de colecciones
            generaTablaBuscarConsultaServicio(servicioArray);

            // Seleccionamos un item de nuestra tabla de colecciones y construimos la entidad para agregarla como cargoconsulta
            $.each(servicioArray, function(keys, values){
                // Mantenemos el foco en el servicio que se esta agregando
                if(idservicio == values.idservicio){
                    if ($('#fieldsetCargoconsultaServicio').hasClass('hiddendiv')){
                        $('#fieldsetCargoconsultaServicio').removeClass('hiddendiv')
                    }
                    var br   = document.createElement("br");
                    var br2   = document.createElement("br");
                    var br3   = document.createElement("br");
                    var br4   = document.createElement("br");
                    // Creamos el input de cantidad de tipo input
                    var divinputCantidad = document.createElement('div');
                    divinputCantidad.className = "input-field";
                    divinputCantidad.setAttribute ( 'id', 'divinputCantidad' );
                    var inputCantidad = document.createElement('input');
                    inputCantidad.setAttribute ( 'id', 'cantidad' );
                    inputCantidad.style.width = "20%";
                    inputCantidad.type = "number";
                    inputCantidad.min ="1";
                    inputCantidad.max = "999999999";
                    divinputCantidad.appendChild(inputCantidad);

                    // Creamos la entidad textual lista para agregar al cargoconsulta
                    var div = document.getElementById("fieldsetCargoconsultaServicioEntity");
                    div.innerHTML = div;
                    var textoServicioNombre = document.createTextNode("Servicio: "+values.servicio_nombre);
                    var textoServicioDescripcion = document.createTextNode("Descrpción: "+values.servicio_descripcion);
                    var textoServicioPrecio = document.createTextNode("Costo: "+values.servicio_precio);
                    var textoCargoconsultaFecha = document.createTextNode("Fecha: "+values.cargoconsulta_fecha);
                    var textoCantidad = document.createTextNode("Cantidad: ");
                    div.appendChild(textoServicioNombre);
                    div.appendChild(br);
                    div.appendChild(textoServicioDescripcion);
                    div.appendChild(br2);
                    div.appendChild(textoServicioPrecio);
                    div.appendChild(br3);
                    div.appendChild(textoCargoconsultaFecha);
                    div.appendChild(br4);
                    div.appendChild(textoCantidad);
                    div.appendChild(inputCantidad);

                    // El input idservicio solamente lo necesitamos para actualizar nuestra entidad servicio antes de agregar el cargo.
                    // Si el formulario ya tiene el input de idservicio lo eliminamos
                    if(document.getElementById('divinputIdservicio')){
                        var divinputIdservicioDelete = document.getElementById("divinputIdservicio");
                        divinputIdservicioDelete.parentNode.removeChild(divinputIdservicioDelete);
                    }

                    // Si el formulario ya tiene el input de servicio_nombre lo eliminamos
                    if(document.getElementById('divinputCargoconsultaTipo')){
                        var divinputCargoconsultaTipoDelete = document.getElementById("divinputCargoconsultaTipo");
                        divinputCargoconsultaTipoDelete.parentNode.removeChild(divinputCargoconsultaTipoDelete);
                    }
                    // Si el formulario ya tiene el input de servicio_descripcion lo eliminamos
                    if(document.getElementById('divinputCargoconsultaFecha')){
                        var divinputCargoconsultaFechaDelete = document.getElementById("divinputCargoconsultaFecha");
                        divinputCargoconsultaFechaDelete.parentNode.removeChild(divinputCargoconsultaFechaDelete);
                    }

                    // Creamos nuestro Formulario con los datos a insertar en Cargoconsulta
                    var form = document.getElementById('CargoconsultaForm');
                    // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                    var divinputIdservicio = document.createElement('div');
                    divinputIdservicio.className = "input-field";
                    divinputIdservicio.setAttribute ( 'id', 'divinputIdservicio' );
                    var inputIdservicio = document.createElement('input');
                    inputIdservicio.setAttribute ( 'id', 'idservicio' );
                    inputIdservicio.setAttribute ( 'type', 'hidden' );
                    inputIdservicio.setAttribute ( 'name', 'idservicio' );
                    inputIdservicio.setAttribute ( 'value', values.idservicio );
                    divinputIdservicio.appendChild(inputIdservicio)
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaTipo = document.createElement('div');
                    divinputCargoconsultaTipo.className = "input-field";
                    divinputCargoconsultaTipo.setAttribute ( 'id', 'divinputCargoconsultaTipo' );
                    var inputCargoconsultaTipo = document.createElement('input');
                    inputCargoconsultaTipo.setAttribute ( 'id', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaTipo.setAttribute ( 'name', 'cargoconsulta_tipo' );
                    inputCargoconsultaTipo.setAttribute ( 'value', values.cargoconsulta_tipo );
                    divinputCargoconsultaTipo.appendChild(inputCargoconsultaTipo);
                    // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                    var divinputCargoconsultaFecha = document.createElement('div');
                    divinputCargoconsultaFecha.className = "input-field";
                    divinputCargoconsultaFecha.setAttribute ( 'id', 'divinputCargoconsultaFecha' );
                    var inputCargoconsultaFecha = document.createElement('input');
                    inputCargoconsultaFecha.setAttribute ( 'id', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'type', 'hidden' );
                    inputCargoconsultaFecha.setAttribute ( 'name', 'cargoconsulta_fecha' );
                    inputCargoconsultaFecha.setAttribute ( 'value', values.cargoconsulta_fecha );
                    divinputCargoconsultaFecha.appendChild(inputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaFecha);
                    form.appendChild(divinputCargoconsultaTipo);
                    form.appendChild(divinputIdservicio);
                }

                // Si dan clic a una entidad de la colección

                // Seleccionamos un item de nuestra tabla de colecciones y construimos la entidad para agregarla como cargoconsulta
                $.each(servicioArray, function(keys, values){
                    // Si dan clic a una entidad de la colección
                    $("#entidadServicio-"+values.idservicio).click(function(){
                        if ($('#fieldsetCargoconsultaServicio').hasClass('hiddendiv')){
                            $('#fieldsetCargoconsultaServicio').removeClass('hiddendiv')
                        }
                        var br   = document.createElement("br");
                        var br2   = document.createElement("br");
                        var br3   = document.createElement("br");
                        var br4   = document.createElement("br");
                        // Creamos el input de cantidad de tipo input
                        var divinputCantidad = document.createElement('div');
                        divinputCantidad.className = "input-field";
                        divinputCantidad.setAttribute ( 'id', 'divinputCantidad' );
                        var inputCantidad = document.createElement('input');
                        inputCantidad.setAttribute ( 'id', 'cantidad' );
                        inputCantidad.style.width = "20%";
                        inputCantidad.type = "number";
                        inputCantidad.min ="1";
                        inputCantidad.max = "999999999";
                        divinputCantidad.appendChild(inputCantidad);

                        // Creamos la entidad textual lista para agregar al cargoconsulta
                        var div = document.getElementById("fieldsetCargoconsultaServicioEntity");
                        div.innerHTML = div;
                        var textoServicioNombre = document.createTextNode("Servicio: "+values.servicio_nombre);
                        var textoServicioDescripcion = document.createTextNode("Descrpción: "+values.servicio_descripcion);
                        var textoServicioPrecio = document.createTextNode("Costo: "+values.servicio_precio);
                        var textoCargoconsultaFecha = document.createTextNode("Fecha: "+values.cargoconsulta_fecha);
                        var textoCantidad = document.createTextNode("Cantidad: ");
                        div.appendChild(textoServicioNombre);
                        div.appendChild(br);
                        div.appendChild(textoServicioDescripcion);
                        div.appendChild(br2);
                        div.appendChild(textoServicioPrecio);
                        div.appendChild(br3);
                        div.appendChild(textoCargoconsultaFecha);
                        div.appendChild(br4);
                        div.appendChild(textoCantidad);
                        div.appendChild(inputCantidad);

                        // El input idservicio solamente lo necesitamos para actualizar nuestra entidad servicio antes de agregar el cargo.
                        // Si el formulario ya tiene el input de idservicio lo eliminamos
                        if(document.getElementById('divinputIdservicio')){
                            var divinputIdservicioDelete = document.getElementById("divinputIdservicio");
                            divinputIdservicioDelete.parentNode.removeChild(divinputIdservicioDelete);
                        }

                        // Si el formulario ya tiene el input de servicio_nombre lo eliminamos
                        if(document.getElementById('divinputCargoconsultaTipo')){
                            var divinputCargoconsultaTipoDelete = document.getElementById("divinputCargoconsultaTipo");
                            divinputCargoconsultaTipoDelete.parentNode.removeChild(divinputCargoconsultaTipoDelete);
                        }
                        // Si el formulario ya tiene el input de servicio_descripcion lo eliminamos
                        if(document.getElementById('divinputCargoconsultaFecha')){
                            var divinputCargoconsultaFechaDelete = document.getElementById("divinputCargoconsultaFecha");
                            divinputCargoconsultaFechaDelete.parentNode.removeChild(divinputCargoconsultaFechaDelete);
                        }

                        // Creamos nuestro Formulario con los datos a insertar en Cargoconsulta
                        var form = document.getElementById('CargoconsultaForm');
                        // Creamos el input de idlugarinventario y le seteamos el valor que le corresponde
                        var divinputIdservicio = document.createElement('div');
                        divinputIdservicio.className = "input-field";
                        divinputIdservicio.setAttribute ( 'id', 'divinputIdservicio' );
                        var inputIdservicio = document.createElement('input');
                        inputIdservicio.setAttribute ( 'id', 'idservicio' );
                        inputIdservicio.setAttribute ( 'type', 'hidden' );
                        inputIdservicio.setAttribute ( 'name', 'idservicio' );
                        inputIdservicio.setAttribute ( 'value', values.idservicio );
                        divinputIdservicio.appendChild(inputIdservicio)
                        // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                        var divinputCargoconsultaTipo = document.createElement('div');
                        divinputCargoconsultaTipo.className = "input-field";
                        divinputCargoconsultaTipo.setAttribute ( 'id', 'divinputCargoconsultaTipo' );
                        var inputCargoconsultaTipo = document.createElement('input');
                        inputCargoconsultaTipo.setAttribute ( 'id', 'cargoconsulta_tipo' );
                        inputCargoconsultaTipo.setAttribute ( 'type', 'hidden' );
                        inputCargoconsultaTipo.setAttribute ( 'name', 'cargoconsulta_tipo' );
                        inputCargoconsultaTipo.setAttribute ( 'value', values.cargoconsulta_tipo );
                        divinputCargoconsultaTipo.appendChild(inputCargoconsultaTipo);
                        // Creamos el input de cargoconsulta_tipo y le seteamos el valor que le corresponde
                        var divinputCargoconsultaFecha = document.createElement('div');
                        divinputCargoconsultaFecha.className = "input-field";
                        divinputCargoconsultaFecha.setAttribute ( 'id', 'divinputCargoconsultaFecha' );
                        var inputCargoconsultaFecha = document.createElement('input');
                        inputCargoconsultaFecha.setAttribute ( 'id', 'cargoconsulta_fecha' );
                        inputCargoconsultaFecha.setAttribute ( 'type', 'hidden' );
                        inputCargoconsultaFecha.setAttribute ( 'name', 'cargoconsulta_fecha' );
                        inputCargoconsultaFecha.setAttribute ( 'value', values.cargoconsulta_fecha );
                        divinputCargoconsultaFecha.appendChild(inputCargoconsultaFecha);
                        form.appendChild(divinputCargoconsultaFecha);
                        form.appendChild(divinputCargoconsultaTipo);
                        form.appendChild(divinputIdservicio);
                    });
                });
            });
        },
        error: function(){
            $('#modalCargoconsultaServicio').prepend('<div class="card-panel #00086E-text red accent-2 guardado-ajax">Error al intentar buscar</div>')
        }
    });

    return false;
};
function tablaCargoconsultaArticuloAgregado(cargoconsultaArray) {

    // Obtener la referencia del elemento div con id = cargoconsultaArticuloResult
    var div = document.getElementById("cargoconsultaArticuloResult");
    div.innerHTML = div;
    // Crea un elemento <table> y un elemento <tbody>
    var tabla   = document.createElement("table");
    tabla.className = "hoverable striped";
    var tblHead = document.createElement("thead");
    var tblBody = document.createElement("tbody");

    var thArray = ['Cantidad', 'Articulo', 'Descripción', 'Salida', 'Fecha/hora', 'Costo', 'Subtotal', 'Opciones']

    // Crea las celdas
    for (var i = 0; i < 1; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("th");
            var textoCelda = document.createTextNode(thArray[j]);
            celda.appendChild(textoCelda);
            hilera.appendChild(celda);
        }

        // agrega la hilera al final de la tabla (al final del elemento tblHead)
        tblHead.appendChild(hilera);
    }

    // posiciona el <thead> debajo del elemento <tbody>
    tabla.appendChild(tblHead);

    // Crea las celdas
    for (var i = 0; i < cargoconsultaArray.length; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("td");

            if(j == 0){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["cantidad"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 1){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["articulo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 2){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["descripcion"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 3){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["salida"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 4){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["fechahora"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 5){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["costo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 6){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["subtotal"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 7){
                var link1 = document.createElement("a");
                link1.className = "tooltipped modal-trigger";
                link1.setAttribute ( 'data-position', 'left' );
                link1.setAttribute ( 'data-tooltip', 'Visualizar' );
                link1.setAttribute ( 'href', '#view-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var vista = document.createElement("i");
                vista.className = "tiny mdi-image-remove-red-eye";
                var link2 = document.createElement("a");
                link2.className = "tooltipped";
                link2.setAttribute ( 'data-position', 'right' );
                link2.setAttribute ( 'data-tooltip', 'Editar' );
                link2.setAttribute ( 'href', '#edit-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var editar = document.createElement("i");
                editar.className = "tiny mdi-action-assignment";
                var link3 = document.createElement("a");
                link3.className = "tooltipped";
                link3.setAttribute ( 'data-position', 'right' );
                link3.setAttribute ( 'data-tooltip', 'Eliminar' );
                link3.setAttribute ( 'href', '#delete-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var eliminar = document.createElement("i");
                eliminar.className = "tiny mdi-action-delete";
                celda.appendChild(link1);
                celda.appendChild(vista);
                celda.appendChild(link2);
                celda.appendChild(editar);
                celda.appendChild(link3);
                celda.appendChild(eliminar);
                hilera.appendChild(celda);
            }
        }

        // agrega la hilera al final de la tabla (al final del elemento tblbody)
        tblBody.appendChild(hilera);
    }

    // posiciona el <tbody> debajo del elemento <table>
    tabla.appendChild(tblBody);

    // appends <table> into <body>
    div.appendChild(tabla);

}

function tablaCargoconsultaServicioAgregado(cargoconsultaArray) {

    // Obtener la referencia del elemento div con id = cargoconsultaServicioResult
    var div = document.getElementById("cargoconsultaServicioResult");
    div.innerHTML = div;
    // Crea un elemento <table> y un elemento <tbody>
    var tabla   = document.createElement("table");
    tabla.className = "hoverable striped";
    var tblHead = document.createElement("thead");
    var tblBody = document.createElement("tbody");

    var thArray = ['Cantidad', 'Servicio', 'Descripción', 'Costo', 'Subtotal', 'Fecha/hora', 'Opciones']

    // Crea las celdas
    for (var i = 0; i < 1; i++) {
        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("th");
            var textoCelda = document.createTextNode(thArray[j]);
            celda.appendChild(textoCelda);
            hilera.appendChild(celda);
        }

        // agrega la hilera al final de la tabla (al final del elemento tblHead)
        tblHead.appendChild(hilera);
    }

    // posiciona el <thead> debajo del elemento <tbody>
    tabla.appendChild(tblHead);

    var subTotal = 0;
    var anticipoCantidad = 0;
    var status = null;
    // Crea las celdas
    for (var i = 0; i < cargoconsultaArray.length; i++) {

        subTotal = subTotal+parseFloat(cargoconsultaArray[i]["subtotal"]);
        status = cargoconsultaArray[i]["status"];

        // Crea las hileras de la tabla
        var hilera = document.createElement("tr");

        for (var j = 0; j < thArray.length; j++) {
            // Crea un elemento <td> y un nodo de texto, haz que el nodo de
            // texto sea el contenido de <td>, ubica el elemento <td> al final
            // de la hilera de la tabla
            var celda = document.createElement("td");

            if(j == 0){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["cantidad"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 1){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["servicio"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 2){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["descripcion"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 3){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["costo"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 4){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["subtotal"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 5){
                var textoCelda = document.createTextNode(cargoconsultaArray[i]["fechahora"]);
                celda.appendChild(textoCelda);
                hilera.appendChild(celda);
            }
            if(j == 6){
                var link1 = document.createElement("a");
                link1.className = "tooltipped modal-trigger";
                link1.setAttribute ( 'data-position', 'left' );
                link1.setAttribute ( 'data-tooltip', 'Visualizar' );
                link1.setAttribute ( 'href', '#view-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var vista = document.createElement("i");
                vista.className = "tiny mdi-image-remove-red-eye";
                var link2 = document.createElement("a");
                link2.className = "tooltipped";
                link2.setAttribute ( 'data-position', 'right' );
                link2.setAttribute ( 'data-tooltip', 'Editar' );
                link2.setAttribute ( 'href', '#edit-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var editar = document.createElement("i");
                editar.className = "tiny mdi-action-assignment";
                var link3 = document.createElement("a");
                link3.className = "tooltipped";
                link3.setAttribute ( 'data-position', 'right' );
                link3.setAttribute ( 'data-tooltip', 'Eliminar' );
                link3.setAttribute ( 'href', '#delete-modal-cargoconsulta-'+cargoconsultaArray[i]["idcargoconsulta"] );
                var eliminar = document.createElement("i");
                eliminar.className = "tiny mdi-action-delete";
                celda.appendChild(link1);
                celda.appendChild(vista);
                celda.appendChild(link2);
                celda.appendChild(editar);
                celda.appendChild(link3);
                celda.appendChild(eliminar);
                hilera.appendChild(celda);
            }
        }

        // agrega la hilera al final de la tabla (al final del elemento tblbody)
        tblBody.appendChild(hilera);
    }

    // posiciona el <tbody> debajo del elemento <table>
    tabla.appendChild(tblBody);

    // appends <table> into <body>
    div.appendChild(tabla);

    subTotalResponse(cargoconsultaArray)

}

function subTotalResponse(cargoconsultaArray) {

    var subTotal = 0;
    var anticipoCantidad = 0;
    var status = null;
    // Crea las celdas
    for (var i = 0; i < cargoconsultaArray.length; i++) {

        subTotal = subTotal+parseFloat(cargoconsultaArray[i]["subtotal"]);
        status = cargoconsultaArray[i]["status"];
    }

    var divTotalSuperior = document.getElementById("totalSuperior");
    divTotalSuperior.innerHTML = divTotalSuperior;
    var divSubTotal = document.createElement('div');
    divSubTotal.className = "col s3";
    var divAnticipo = document.createElement('div');
    divAnticipo.className = "col s3";
    var divStatus = document.createElement('div');
    divStatus.className = "col s3";
    var textoSubTotal = document.createTextNode(" Total: $"+subTotal+" MXN");
    var editar = document.createElement("i");
    editar.className = "tiny mdi-action-assignment pointer";
    editar.setAttribute ( 'id', 'pagarAnticipo' );
    var textoAnticipo = document.createTextNode("Anticipo: "+anticipoCantidad+" MXN");
    var textoStatus = document.createTextNode("Status: "+status);
    divSubTotal.appendChild(textoSubTotal);
    divAnticipo.appendChild(textoAnticipo);
    divAnticipo.appendChild(editar);
    divStatus.appendChild(textoStatus);
    divTotalSuperior.appendChild(divSubTotal);
    divTotalSuperior.appendChild(divAnticipo);
    divTotalSuperior.appendChild(divStatus);

    var divTotalInferior = document.getElementById("totalInferior");
    divTotalInferior.innerHTML = divTotalInferior;
    var h4 = document.createElement('h4')
    h4.className = "right-align";
    var textoServicioTotal = document.createTextNode("Total: $"+subTotal+" MXN");
    h4.appendChild(textoServicioTotal)
    divTotalInferior.appendChild(h4)

    var divbotonPagarAnticipo = document.getElementById("botonPagarAnticipo");
    divbotonPagarAnticipo.innerHTML = divbotonPagarAnticipo;
    var buttonPagarAnticipo = document.createElement('button')
    buttonPagarAnticipo.setAttribute ( 'id', 'buttonPagarAnticipo' );
    buttonPagarAnticipo.style.width = "100%";
    buttonPagarAnticipo.style.height = "45px";
    buttonPagarAnticipo.style.marginTop = "20px";
    buttonPagarAnticipo.className = "btn waves-effect waves-light";
    buttonPagarAnticipo.setAttribute ( 'type', 'submit' );
    var textoButtonPagarAnticipo = document.createTextNode("Pagar/Anticipo");
    buttonPagarAnticipo.appendChild(textoButtonPagarAnticipo)
    divbotonPagarAnticipo.appendChild(buttonPagarAnticipo)

    var divbotonGenerarFactura = document.getElementById("botonGenerarFactura");
    divbotonGenerarFactura.innerHTML = divbotonGenerarFactura;
    var buttonGenerarFactura = document.createElement('button')
    buttonGenerarFactura.setAttribute ( 'id', 'buttonGenerarFactura' );
    buttonGenerarFactura.style.width = "100%";
    buttonGenerarFactura.style.height = "45px";
    buttonGenerarFactura.style.marginTop = "20px";
    buttonGenerarFactura.className = "btn waves-effect waves-light disabled";
    buttonGenerarFactura.setAttribute ( 'type', 'submit' );
    var textoButtonGenerarFactura = document.createTextNode("Generar Factura");
    buttonGenerarFactura.appendChild(textoButtonGenerarFactura)
    divbotonGenerarFactura.appendChild(buttonGenerarFactura)

    var divbotonGenerarNota = document.getElementById("botonGenerarNota");
    divbotonGenerarNota.innerHTML = divbotonGenerarNota;
    var buttonGenerarNota = document.createElement('button')
    buttonGenerarNota.setAttribute ( 'id', 'buttonGenerarNota' );
    buttonGenerarNota.style.width = "100%";
    buttonGenerarNota.style.height = "45px";
    buttonGenerarNota.style.marginTop = "20px";
    buttonGenerarNota.className = "btn waves-effect waves-light disabled";
    buttonGenerarNota.setAttribute ( 'type', 'submit' );
    var textoButtonGenerarNota = document.createTextNode("Generar Nota");
    buttonGenerarNota.appendChild(textoButtonGenerarNota)
    divbotonGenerarNota.appendChild(buttonGenerarNota)

    var divbotoVerFactura = document.getElementById("botonVerFactura");
    divbotoVerFactura.innerHTML = divbotoVerFactura;
    var buttonVerFactura = document.createElement('button')
    buttonVerFactura.setAttribute ( 'id', 'buttonVerFactura' );
    buttonVerFactura.style.width = "100%";
    buttonVerFactura.style.height = "45px";
    buttonVerFactura.className = "left btn waves-effect waves-light disabled";
    buttonVerFactura.setAttribute ( 'type', 'submit' );
    var textoButtonVerFactura = document.createTextNode("Ver Factura");
    buttonVerFactura.appendChild(textoButtonVerFactura)
    divbotoVerFactura.appendChild(buttonVerFactura)

}

function eliminarTabla(){
    var parrafo = document.getElementById("cargoconsultaArticuloResult");
    parrafo.parentNode.removeChild(parrafo);
}
</script>