<?php
$title = 'Eliminar variante';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete?</p>
<table class="table">
    <tr>
        <th>ID Articulovariante</th>
        <th>Código de Barras</th>
        <th>Costo</th>
        <th>Precio</th>
        <th>IVA</th>
        <th>Imagen</th>
        <th>Mínimo</th>
        <th>Máximo</th>
        <th>Re-orden</th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($articulovariante['idarticulo']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_codigobarras']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_costo']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_precio']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_iva']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_imagen']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_minimo']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_maximo']);?></td>
        <td><?php echo $this->escapeHtml($articulovariante['articulovariante_reorden']);?></td>
    </tr>
</table>
<?php
$url = $this->url('articulovariante', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $articulovariante['idarticulovariante']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>