<?php
$title = 'Variantes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row" id="table-header">
    <form class="col s12">
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="<?php echo $this->url('articulovariante', array('action'=>'nuevo'));?>"><i class="mdi-content-add-circle-outline prefix"></i>Nueva Variante de un Artículo</a>
            </div>
            <div class="input-field col s4 offset-s2" id="search-container">
                <i class="mdi-action-search prefix"></i>
                <input id="icon_prefix" type="text">
                <label for="icon_prefix">Buscar</label>
            </div>
        </div>
    </form>
</div>
<table id="tabla-articulovariante" class="striped">
    <thead>
        <tr>
            <th>ID Articulovariante</th>
            <th>ID Articulo</th>
            <th>Código de Barras</th>
            <th>Costo</th>
            <th>Precio</th>
            <th>IVA</th>
            <th>Imagen</th>
            <th>Mínimo</th>
            <th>Máximo</th>
            <th>Re-orden</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
    <?php $direction = 'right'?>
    <?php foreach ($articulosvariantes as $articulovariante) : ?>
        <tr>
            <td><?php echo $articulovariante->getIdarticulovariante() ?></td>
            <td><?php echo $articulovariante->getIdarticulo() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteCodigobarras() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteCosto() ?></td>
            <td><?php echo $articulovariante->getArticulovariantePrecio() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteIva() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteImagen() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteMinimo() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteMaximo() ?></td>
            <td><?php echo $articulovariante->getArticulovarianteReorden() ?></td>
            <td>
                <a class="tooltipped" data-position="left" data-tooltip="Visualizar" href='<?php echo "/catalogos/articulovariante/ver/".$articulovariante->getIdArticulovariante()?>'><i class="tiny mdi-image-remove-red-eye"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/catalogos/articulovariante/editar/".$articulovariante->getIdArticulovariante()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Eliminar" href='<?php echo "/catalogos/articulovariante/eliminar/".$articulovariante->getIdArticulovariante()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>

    </tbody>
</table>
<script>
    $(document).ready(function(){

        $("#tabla-articulovariante").tablesorter({headers:{4:{sorter:false}}});

    });
</script>
