<?php
$title = 'Eliminar lugar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete?</p>
<table id="tabla-productos" class="striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $this->escapeHtml($lugar['lugar_nombre']);?></td>
            <td><?php echo $this->escapeHtml($lugar['lugar_descripcion']);?></td>
        </tr>
    </tbody>
</table>
<br>
<br>
<?php
$url = $this->url('lugar', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $lugar['idlugar']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>