<?php
$title = 'Lugares';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="<?php echo $this->url('lugar', array('action'=>'nuevo'));?>"><i class="mdi-content-add-circle-outline prefix"></i>Nuevo Lugar</a>
            </div>
            <div class="input-field col s4 offset-s2" id="search-container">
                <i class="mdi-action-search prefix"></i>
                <input id="icon_prefix" type="text">
                <label for="icon_prefix">Buscar</label>
            </div>
        </div>
    </form>
</div>
<table id="tabla-productos" class="striped">
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Descripción</th>
    </tr>
    </thead>
    <tbody>
    <?php $direction = 'right'?>
    <?php foreach ($lugares as $lugar) : ?>
        <tr>
            <td><?php echo $lugar->getLugarNombre() ?></td>
            <td><?php echo $lugar->getLugarDescripcion() ?></td>
            <td>
                <a class="tooltipped" data-position="left" data-tooltip="Visualizar" href='<?php echo "/catalogos/lugar/ver/".$lugar->getIdLugar()?>'><i class="tiny mdi-image-remove-red-eye"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/catalogos/lugar/editar/".$lugar->getIdLugar()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Eliminar" href='<?php echo "/catalogos/lugar/eliminar/".$lugar->getIdLugar()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>

    </tbody>

</table>
<script>
    $(document).ready(function(){

        $("#tabla-productos").tablesorter({headers:{5:{sorter:false}}});

    });
</script>