<?php
$title = 'Nuevo Lugar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form = $this->lugarForm;
$form->setAttribute('action', $this->url('lugar', array('action' => 'nuevo')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idlugar'));?>
<fieldset>
    <legend>Datos Generales</legend>
    <div class="input-field col s8">
        <?php  echo $this->formText($form->get('lugar_nombre')); ?>
        <?php  echo $this->formLabel($form->get('lugar_nombre'));
        $showError=$this->formElementErrors($form->get('lugar_nombre'));
        if(!empty($showError)):?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php echo $showError; ?>
            </div>
        <?php endif;?>
    </div>
    <div class="input-field col s6">
        <?php  echo $this->formText($form->get('lugar_descripcion')); ?>
        <?php  echo $this->formLabel($form->get('lugar_descripcion'));
        $showError=$this->formElementErrors($form->get('lugar_descripcion'));
        if(!empty($showError)):?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php echo $showError; ?>
            </div>
        <?php endif;?>
    </div>
</fieldset>
<br>
<br>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<!--
<div class="right input-field col s2 offset-s10">
    <?php //echo $this->formSubmit($form->get('submit')); ?>
</div>
-->
<?php
//echo $this->formCollection($LugarForm);

echo $this->form()->closeTag();

?>
<script>
    $(document).ready(function() {
        $('select').material_select();
        $('.modal-trigger').leanModal();
    });
</script>