<?php
$title = 'Nuevo Servicio';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $servicioForm->setAttribute('action', '/servicios/nuevo');?>
<?php $servicioForm->setAttribute('class', 'hva-form');?>
<?php $servicioForm->prepare();?>
<?php echo $this->form()->openTag($servicioForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_nombre')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_nombre')); ?>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_descripcion')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_descripcion')); ?>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_precio')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_precio')); ?>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formSelect($servicioForm->get('servicio_iva')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
    
        $('button[type=submit]').on('click',function(e){
            $('p.input-error-show').remove();
            var error_message = '<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>';
            var isValid = true;
            $(document).find('input[required],select[required]').filter(function(){
                if($(this).val() == ''){
                    $(this).after(error_message);
                    isValid = false;
                }
                
            });
            
            if(!isValid){
                e.preventDefault();
            }
            
        });
</script>