<?php
$title = 'Nuevo Servicio';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $servicioForm->setAttribute('action', '/servicios/nuevo');?>
<?php $servicioForm->setAttribute('class', 'hva-form');?>
<?php $servicioForm->prepare();?>
<?php echo $this->form()->openTag($servicioForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_nombre')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_nombre')); ?>
                <?php $showError=$this->formElementErrors($servicioForm->get('servicio_nombre'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_descripcion')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_descripcion')); ?>
                <?php $showError=$this->formElementErrors($servicioForm->get('servicio_descripcion'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_costo')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_costo')); ?>
                <?php $showError=$this->formElementErrors($servicioForm->get('servicio_costo'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_precio')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_precio')); ?>
                <?php $showError=$this->formElementErrors($servicioForm->get('servicio_precio'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($servicioForm->get('servicio_iva')); ?>
                <?php echo $this->formLabel($servicioForm->get('servicio_iva')); ?>
                <?php $showError=$this->formElementErrors($servicioForm->get('servicio_iva'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
</script>