<?php echo $this->doctype(); ?>
<style>

</style>
<html lang="en" style="height: 100%">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('HVA '. $this->translate('Hospital Valle de Atemajac'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <!--Let browser know website is optimized for mobile-->
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <!--Import materialize.css-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
        ->prependStylesheet($this->basePath('css/lolliclock.css'))
        //->prependStylesheet($this->basePath('css/timepicki.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/materialize.css'))
        ->prependStylesheet($this->basePath('css/multiple.css'))
                ->prependStylesheet($this->basePath('css/token_input/token-input.css'));
    
    
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        
        ->prependFile($this->basePath('js/jquery.tokeninput.js'), 'text/javascript')
        ->prependFile($this->basePath('js/jquery-ui-1-10-1.js'), 'text/javascript')
        ->prependFile($this->basePath('js/lolliclock.js'), 'text/javascript')
        //->prependFile($this->basePath('js/timepicki.js'), 'text/javascript')
        ->prependFile($this->basePath('js/formcache.min.js'), 'text/javascript')
        ->prependFile($this->basePath('js/filterTable.js'), 'text/javascript')
        ->prependFile($this->basePath('js/tablesorter.js'), 'text/javascript')
        ->prependFile($this->basePath('js/materialize.js'), 'text/javascript')
        ->prependFile($this->basePath('js/comprasreports.js'), 'text/javascript')
        ->prependFile($this->basePath('js/multiple.js'), 'text/javascript')
        ->prependFile($this->basePath('js/accounting.js'), 'text/javascript')
        ->prependFile($this->basePath('js/jquery.min.js'), 'text/javascript');
    
    
    ?>

</head>
<body>
<div class="row" id="main-container">
    <div id="topmenu-container " class="row z-depth-1" style="margin-bottom: 0px">
        <div class="col s1 ">
            <img id="logo-navbar"class="responsive-img" src="/img/logo_login.jpg">
        </div>
        <div class="col s9" id="module_list">
            <ul>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_pacientes'>Pacientes <i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_ventas'>Venta al publico<i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_productos'>Productos<i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_compras'>Compras<i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_almacen'>Almacen <i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_bancos'>Bancos <i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_caja'>Caja<i class="mdi-hardware-keyboard-arrow-down"></i></a></li>  
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_catalogos'>Catalogos <i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_empleados'>Empleados <i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_facturacion'>Facturacion<i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
                <li><a href="/notasremision" >Notas de remisión</a></li>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_reportes'>Reportes<i class="mdi-hardware-keyboard-arrow-down"></i></a></li>
            </ul>
        </div>
        <div class="col s2" id="navbar_profile-container">
            <a href="javascript:void(0)" id="navbar_profile" data-activates='dropdown_profile'>
                <div class="row" style="margin-bottom: 9px;">
                    <div class="col s4" style="margin-top: 15px;">
                        <?php if(!is_null($_SESSION["empleado_session"]["empleado_info"]["empleado_imagen"])) :?>
                            <img style="height: 32px; width: 100%" class="responsive-img circle" src="<?php echo $_SESSION["empleado_session"]["empleado_info"]["empleado_imagen"]?>">
                        <?php else :?>
                            <img class="responsive-img circle" src="/img/profile/default_user.jpg">
                        <?php endif;?>
                    </div>

                    <div class="col s8" style="padding-top: 13px;">
                        <div><?php echo $_SESSION["empleado_session"]["empleado_info"]["empleado_nombre"].' '.$_SESSION["empleado_session"]["empleado_info"]["empleado_apellidopaterno"]?><i class="mdi-hardware-keyboard-arrow-down"></i></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="row" id="workspace-container">
        <div class="col s12">
            <?php echo $this->content?>
        </div>
    </div>
<!--    <div class="row z-depth-1" id="footer-container">
        <div class="col s12" id="footer">
            <p>Hospital del Valle de Atemajac - &copy Todos los derechos reservados 2015 </p>
        </div>
    </div>-->
</div>
    
    <!-- Dropdown Facturacion -->
<ul id='dropdown_facturacion' class='dropdown-content'>
    <li><a href="/facturacion/emitidas">Facturas emitidas</a></li>
    <li class="divider"></li>
    <li><a href="/facturacion/canceladas">Facturas canceladas</a></li>
    <li class="divider"></li>
    <li><a href="/facturacion/facturar">Generar factura</a></li>
</ul>

<!-- Dropdown Catalogos -->
<ul id='dropdown_reportes' class='dropdown-content'>
    <li><a href="/reportes/ingresos">Reporte de ingresos</a></li>
    <li class="divider"></li>
    <li><a href="/pacientes/historico">Reporte de consultas/admisiones</a></li>
    <li class="divider"></li>
    <li><a href="/reportes/general">Reporte general</a></li>
    <li class="divider"></li>
</ul>

<ul id='dropdown_ventas' class='dropdown-content'>
    <li><a href="/venta">Mis ventas</a></li>
    <li class="divider"></li>
    <li><a href="/venta/asignar">Nueva venta</a></li>
    <li class="divider"></li>
</ul>

<ul id='dropdown_catalogos' class='dropdown-content'>
    <li style="min-width: 150px"><a href="/catalogos/articulo">Productos</a></li>
    <li class="divider"></li>
    <li><a href="/catalogos/proveedor">Proveedores</a></li>
    <li class="divider"></li>
    <li><a href="/catalogos/cuarto">Cuartos</a></li>
    <li class="divider"></li>
    <li><a href="/consultorio">Consultorios</a></li>
    <li class="divider"></li>
    <li><a href="/catalogos/especialidad">Especialidades</a></li>
    <li class="divider"></li>
    <li><a href="/catalogos/medico">Medicos</a></li>
    <li class="divider"></li>
    <li><a href="/servicios">Servicios</a></li>
</ul>
<!-- Dropdown  Pacientes -->
<ul id='dropdown_pacientes' class='dropdown-content'>
    <li><a href="<?php echo $this->url('pacientes', array('action'=>'listar'));?>">Listado de Pacientes</a></li>
    <li class="divider"></li>
    <li><a href="<?php echo $this->url('pacientes', array('action'=>'actuales'));?>">Pacientes Actuales</a></li>
    <li class="divider"></li>
    <li><a href="<?php echo $this->url('pacientes', array('action'=>'nuevo'));?>">Admisión de pacientes</a></li>
    <li class="divider"></li>
    <li><a href="/pacientes/historicos">Historico de pacientes</a></li>
    <li class="divider"></li>
    <li><a href="/pacientes/citas">Citas</a></li>
    <li class="divider"></li>
    <li><a href="/pacientes/agendarcita">Agendar cita</a></li>
</ul>
<!-- Dropdown  Productos -->
<ul id='dropdown_productos' class='dropdown-content'>
    <li><a href="/productos">Productos</a></li>
    <li class="divider"></li>
    <!--<li><a href="/productos/precios">Definir precios</a></li>-->
    <li class="divider"></li>
    <li><a href="/productos/reorden/definir">Definir punto de reorden</a></li>
    <li class="divider"></li>
    <li><a href="/productos/reorden">Productos en punto de reorden</a></li>
    <li class="divider"></li>
    <li><a href="/productos/existencias">Definir existencias</a></li>
    <li class="divider"></li>
    <li><a href="/productos/registro">Registro de productos</a></li>
</ul>
<!-- Dropdown  Compras -->
<ul id='dropdown_compras' class='dropdown-content'>
    <li><a href="/compras">Compras</a></li>
    <li class="divider"></li>
    <li><a href="/compras/nuevo">Nueva compra</a></li>
</ul>
<!-- Dropdown  Almacen -->
<ul id='dropdown_almacen' class='dropdown-content'>
    <li><a href="/catalogos/lugar">Almacenes</a></li>
    <li class="divider"></li>
    <li><a href="/catalogos/lugar/nuevo">Nuevo almacen</a></li>
    <li class="divider"></li>
    <li><a href="/almacen/transferencias">Transferencias</a></li>
    <li class="divider"></li>
    <li><a href="/almacen/transferencias/nuevo">Nueva transferencia</a></li>
</ul>
<!-- Dropdown  bancos -->
<ul id='dropdown_bancos' class='dropdown-content'>
    <li><a href="/bancos/concepto">Conceptos</a></li>
    <li class="divider"></li>
    <li><a href="/bancos/concepto/nuevo">Nuevo concepto</a></li>
    <li class="divider"></li>
    <li><a href="/bancos/movimientos">Movimientos</a></li>
</ul>
<!-- Dropdown  Almacen -->
<ul id='dropdown_caja' class='dropdown-content'>
    <li><a href="/cajachica/concepto">Conceptos</a></li>
    <li class="divider"></li>
    <li><a href="/cajachica/concepto/nuevo">Nuevo concepto</a></li>
    <li class="divider"></li>
    <li><a href="/cajachica/movimientos">Movimientos</a></li>
</ul>
<!-- Dropdown  Empleados -->
<ul id='dropdown_empleados' class='dropdown-content'>
    <li><a href="/empleados">Empleados</a></li>
    <li class="divider"></li>
    <li><a href="/empleados/nuevo">Nuevo empleado</a></li>
</ul>

<ul id='dropdown_profile' class='dropdown-content' style="top: 14px;">
    <li><a href="#!">Ver Perfil</a></li>
    <li class="divider"></li>
    <li>
        <a href="/auth/out">Cerrar sesión</a>
    </li>
</ul>
</body>
</html>
<script type="text/javascript">
    var windowsHeigh = $(window).outerHeight(true);
    var containerHeigh = $("#main-container").outerHeight(true);
    if(windowsHeigh>containerHeigh){
        $("div#footer-container").css('position','absolute');
    }
    $('.navbar_dropdown').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: false, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: false // Displays dropdown below the button
    });
    $('#navbar_profile').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: true, // Does not change width of dropdown to that of the activator
        hover: false, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: false // Displays dropdown below the button
    });
</script>
