<?php echo $this->doctype(); ?>

<html lang="en" style="height: 100%">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('HVA '. $this->translate('Hospital Valle de Atemajac'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!--Let browser know website is optimized for mobile-->
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <!--Import materialize.css-->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css')) 
                ->prependStylesheet($this->basePath('css/materialize.css'));
            ?>                                                               

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/materialize.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.min.js'), 'text/javascript');
            
        ?>

    </head>
    <body style="position: relative">
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
    <script type="text/javascript">
        $(document).ready(function(){
            var screenHeight = $("html").height();
            var loginContainerHeigh = $("#login-container").height();
            if(screenHeight>loginContainerHeigh){
                var margin = (screenHeight - loginContainerHeigh) / 2 ;
                $("body").css('top',margin);
            }
        });
    </script>
</html>
