<?php
    $title = 'Transferencias';
    $this->headTitle($title);
    setlocale(LC_MONETARY, 'en_US');
      
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/almacen/transferencias/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nueva trasferencia</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-transferencias" class="striped">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Remitente</th>
            <th >Receptor</th>
            <th >Cantidad de articulos</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody> 
    <?php foreach($transferencias as $transferencia) : ?>
  
        <tr id="<?php echo  $transferencia['id']?>">
            <td><?php  echo $transferencia['fecha']?></td>
            <td><?php  echo $transferencia['remitente']?></td>
            <td><?php  echo $transferencia['receptor'] ?></td>
            <td><?php  echo $transferencia['cantidad']?></td>
            <td>
            
                <a id="transferencia_detalles"class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href='javascript:void(0)'><i class="tiny mdi-image-remove-red-eye"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/almacen/transferencias/editar/".$transferencia['id']?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-transferencia-".$transferencia['id']?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
        <!-- Delete Modal Structure -->
        <div id="delete-modal-transferencia-<?php echo $transferencia['id']?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar la transferencia con ID '". $transferencia['id']."' ?"?></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/almacen/transferencias/eliminar/<?php echo $transferencia['id']?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>       
            </div>
        </div>
        <!-- End Delete Modal Structure -->   
    <?php endforeach; ?>
    </tbody>
</table>
<script>
$(document).ready(function(){
    
    $('.modal-trigger').leanModal();
    $("#tabla-transferencias").tablesorter({headers:{0:{sorter:false},4:{sorter:false}}});
    $("#tabla-transferencias").filterTable({inputSelector: '#search-container input',minRows:1});
    
    /*
     * Evento preview
     */
    
    $('a#transferencia_detalles').on('click',function(){
        var id = $(this).closest('tr').attr('id');
        var modalName = '#modal-preview-'+id;
        $.get(
            '/almacen/transferencias/transferenciadetalles',
            {id:id},
            function(data){
                $('table').after(data);
                $(modalName).openModal();
            }
        );
    });
   
}); 
</script>