<div id="enviar" class="modal">    
    <div class="modal-content">
        <h4>Enviar factura por correo electronico</h4>
    </div>
    <div class="row">
        <span id="idfactura" style="display: none"><?php echo $id?></span>
        <div class="col s12 input-field">
             <label>Correo electronico registrado</label>
            <select name='email_static'>
                <?php foreach ($emails as $key => $value) :?>
                    <option value="<?php echo $value?>"><?php echo $value?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="col s12">
            <p>
                <input type="checkbox" id="email_switch" />
                <label for="email_switch">Enviar a una cuenta de correo electronico distinta</label>
            </p>
            <div id="email_container" style="display: none">
                <div class="input-field">
                    <input name="email_dinamic" type="email" class="validate" required>
                    <label >Correo electronico</label>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
        <a id="btn_enviar" href="#!" class="waves-effect waves-light btn editar">Enviar</a>
     </div>
</div>
<script>
    $(document).ready(function() {
        $('select').material_select();
        
        $('#email_switch').on('click',function(){
            var checked = $(this).prop('checked');
            if(checked){
                $('#email_container').show();
            }else{
                $('#email_container').hide();
            }
        });
        
        $('#btn_enviar').on('click',function(e){
                $('p.input-error-show').remove();
                var error_message = '<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>';
                var invalid_message = '<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Correo electronico invalido</p>';
                var isValid = true;
                $(document).find('input[required]:visible').filter(function(){
                if($(this).val() == ''){
                    $(this).after(error_message);
                    isValid = false;
                }else{
                    //validamos que sea un email valido
                    var emialTxt = $(this).val();
                    if(!validateEmail(emialTxt)){
                        $(this).after(invalid_message);
                        isValid = false;
                    }
                }
                
            });
            if(!isValid){
                e.preventDefault();
            }else{
             
             var checked = $('#email_switch').prop('checked');
             
             var email = '';
             if(checked){
                 email = $('input[name=email_dinamic]').val();
             }else{
                 email = $('select[name=email_static]').val();
             }
             
             $.ajax({
                 url:'/facturacion/emitidas/enviar',
                 method: 'POST',
                 dataType: 'json',
                 data: {email:email,id:$('#idfactura').text()},
                 success: function(data){
                     $('.modal').closeModal();
                     $('.modal').remove();
                     alert(data.msg);
                 }
             });
             

            }
            
        });
        
        
        function validateEmail(sEmail) {
            var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
            if (filter.test(sEmail)) {
                return true;
            }
            else {
                return false;
            }
        }
        
    });
   

</script>