<?php
    $title = 'Facturas emitidas';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>
        <?php if(count($flashErrorMessages)) :?>
            <?php foreach ($flashErrorMessages as $message) :?>
                <div class="card-panel white-text red darken-4"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>        
        <div class="row" style="position: relative">
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-empleados" class="table striped">
    <thead>
        <tr>
            <th>Fecha</th>
            <th># Movimiento</th>
            <th>UUID</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($collection as $entity) :?>
        <tr id="<?php echo $entity['id']?>">
            <td><?php echo $entity['fecha']?></td>
            <td><?php echo $entity['movimiento']?></td>
            <td><?php echo $entity['uuid']?></td>
            <td>
                <a download href="/tmp/xml/<?php echo $entity['movimiento'].'.xml'?>"><img src="/img/icons/xml_icon.png"></a>
                &nbsp;&nbsp;
                <a href="/tmp/pdf/<?php echo $entity['movimiento'].'.pdf'?>"><img src="/img/icons/pdf_icon.png"></a>
                &nbsp;&nbsp;
                <a id="enviar" href="javascript:void(0)"><img src="/img/icons/mail_icon.png"></a>
                &nbsp;&nbsp;
                <a class="modal-trigger" href="#cancel-modal-factura-<?php echo $entity['id']?>">Cancelar</a>
            </td>
        </tr>
         <!-- Delete Modal Structure -->
        <div id="cancel-modal-factura-<?php echo $entity['id']?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea cancelar la factura seleccionada   ?" ?></p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/facturacion/facturar/cancelar/<?php echo $entity['id']?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Cancelar</a>
              
            </div>
        </div>
        <!-- End Delete Modal Structure -->
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(document).ready(function(){
         $("#tabla-empleados").tablesorter({headers:{3:{sorter:false}}});
         $("#tabla-empleados").filterTable({inputSelector: '#search-container input',minRows:1});
         $('.modal-trigger').leanModal();
         $('.money').filter(function(){
             var text = $(this).text();
             var money = accounting.formatMoney(text);
             $(this).text(money);
        });
        
        $('a#enviar').on('click',function(){
            
            var id = $(this).closest('tr').attr('id');
            
            $.ajax({
                url:'/facturacion/emitidas/enviar',
                data: {id:id},
                success: function(data){
                   var source = $('<div>' + data + '</div>');
                   $('table').after(source);
                   source.find('.modal').openModal();
                   
                }
            });
        });
        
}); 
</script>