<?php
    $title = 'Unidad de medida: '.$udmForm->get('udm_nombre')->getValue();
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $udmForm->setAttribute('action', '/catalogos/udm/editar/'.$id);?>
<?php $udmForm->setAttribute('class', 'hva-form');?>
<?php $udmForm->prepare();?>
<?php echo $this->form()->openTag($udmForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($udmForm->get('udm_nombre')); ?>
                    <?php echo $this->formLabel($udmForm->get('udm_nombre')); ?>
                </div>
                <p id="udm_nombre" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formText($udmForm->get('udm_descripcion')); ?>
                    <?php echo $this->formLabel($udmForm->get('udm_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<p style="color: #9e9e9e">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {        
        //Utilizamos plugin de cache para almacenar los valores del formunlario en cache en caso de error
        //$('#ArticuloForm'   ).formcache();
        
        //Inicializamos el select de materialize
         $('select').material_select();
        

           //Validacion de campos obligatorios 
        $(document).on('click', 'form button[type=submit]', function(e) {
            $('p.input-error').hide();
            var isValid = true;
            //console.log($('select[name=idtipo]').val());
            if(!$('input[name=udm_nombre]').val().length){
               isValid = false;
               $('p#udm_nombre').show();
               e.preventDefault(); 
            }
            
        });
          

    });
</script>
