<?php

$title = 'Lista de udms';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('udm', array('action'=>'nuevo'));?>">Nuevo UDM</a>
</p>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($udms as $udm) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($udm['udm_nombre']);?></td>
            <td><?php echo $this->escapeHtml($udm['udm_descripcion']);?></td>
            <td>
                <a href="<?php echo $this->url('udm',
                    array('action'=>'editar', 'id' => $udm['idudm']));?>">Editar</a>
                <a href="<?php echo $this->url('udm',
                    array('action'=>'eliminar', 'id' => $udm['idudm']));?>">Eliminar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>