<?php
    $title = 'Unidad de medida';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/catalogos/udm/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nueva unidad de medida</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-udms" class="striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($udms as $udm) : ?>
        <tr>
            <td><?php echo $udm->getUdmNombre() ?></td>
            <td><?php echo $udm->getUdmDescripcion() ?></td>
            <td>
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/catalogos/udm/editar/".$udm->getIdUdm()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-udm-".$udm->getIdUdm()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
         <!-- End preview Modal Structure -->
        <!-- Delete Modal Structure -->
        <div id="delete-modal-udm-<?php echo $udm->getIdudm()?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar la unidad de medida: '". $udm->getUdmNombre(). "' de su catalogo?" ?></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/catalogos/udm/eliminar/<?php echo $udm->getIdUdm()?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>       
            </div>
        </div>
        <!-- End Delete Modal Structure -->
    <?php endforeach; ?>
    </tbody>
</table>
<script>
$(document).ready(function(){
        $("#tabla-udms").tablesorter({headers:{2:{sorter:false}}});
        $("#tabla-udms").filterTable({inputSelector: '#search-container input',minRows:1});
        $('.modal-trigger').leanModal();
}); 
</script>