<?php
$title = 'Nuevo UDM';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(!$Error){
    $UDMForm->setAttribute('action', $this->url('udm', array('action' => 'nuevo')));
    $UDMForm->prepare();

    echo $this->form()->openTag($UDMForm);
    echo $this->formCollection($UDMForm);
    echo $this->form()->closeTag();
}else{
    foreach ($Error as $errorValue){
        echo $errorValue;
    }
}