<?php
    $title = 'Nueva especialidad médica';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $especialidadForm->setAttribute('action', '/catalogos/especialidad/nuevo');?>
<?php $especialidadForm->setAttribute('class', 'hva-form');?>
<?php $especialidadForm->prepare();?>
<?php echo $this->form()->openTag($especialidadForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($especialidadForm->get('especialidad_nombre')); ?>
                    <?php echo $this->formLabel($especialidadForm->get('especialidad_nombre')); ?>
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="input-field">
                <?php echo $this->formText($especialidadForm->get('especialidad_descripcion')); ?>
                <?php echo $this->formLabel($especialidadForm->get('especialidad_descripcion')); ?>
            </div>
        </div>
    </fieldset>
</div>
<p style="color: rgb(158, 158, 158); margin-top: 0px; padding-left: 24px;">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script>
    var error_message =  $('<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>');
    
    $(document).on('click', 'form button[type=submit]', function(e) {
        $('p.input-error-show').remove();
        var isValid = true;
        //console.log($('select[name=idtipo]').val());
        if(!$('input[name=especialidad_nombre]').val().length){
           isValid = false;
           $('input[name=especialidad_nombre]').after(error_message);
           e.preventDefault(); 
        }
            
    });

</script>