<?php
    $title = 'Nueva Especialidad Medica';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $especialidadForm->setAttribute('action', '/catalogos/especialidad/nuevo');?>
<?php $especialidadForm->setAttribute('class', 'hva-form');?>
<?php $especialidadForm->prepare();?>
<?php echo $this->form()->openTag($especialidadForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($especialidadForm->get('especialidad_nombre')); ?>
                    <?php echo $this->formLabel($especialidadForm->get('especialidad_nombre')); ?>
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="input-field">
                <?php echo $this->formText($especialidadForm->get('especialidad_descripcion')); ?>
                <?php echo $this->formLabel($especialidadForm->get('especialidad_descripcion')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
