<?php
$title = 'Editar propiedad';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
if(!$Error){

    $PropiedadForm = $this->PropiedadForm;
    $PropiedadForm->setAttribute('action', $this->url(
        'propiedad',
        array(
            'action' => 'editar',
            'id'     => $this->id,
        )
    ));
    $PropiedadForm->prepare();

    echo $this->form()->openTag($PropiedadForm);
    echo $this->form()->openTag($PropiedadForm);
    echo $this->formHidden($PropiedadForm->get('idpropiedad'));
    echo $this->formRow($PropiedadForm->get('idarticulo'));
    echo $this->formRow($PropiedadForm->get('propiedad_nombre'));
    echo $this->formSubmit($PropiedadForm->get('submit'));
    //echo $this->formCollection($PropiedadForm);
    echo $this->form()->closeTag();
}else{
    foreach ($Error as $errorValue){
        echo $errorValue;
    }
}