<?php

$title = 'Mis Artículos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('propiedad', array('action'=>'nuevo'));?>">Nuevo Propiedad</a>
</p>

<table class="table">
    <tr>
        <th>ID Articulo</th>
        <th>Nombre</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($Propiedads as $propiedad) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($propiedad['idarticulo']);?></td>
            <td><?php echo $this->escapeHtml($propiedad['propiedad_nombre']);?></td>
            <td>
                <a href="<?php echo $this->url('propiedad',
                    array('action'=>'editar', 'id' => $propiedad['idpropiedad']));?>">Editar</a>
                <a href="<?php echo $this->url('propiedad',
                    array('action'=>'eliminar', 'id' => $propiedad['idpropiedad']));?>">Eliminar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>