<?php
    $title = 'Conceptos';
    $this->headTitle($title);
   
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/bancos/concepto/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nuevo concepto</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-bancos" class="striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody> 
    <?php foreach($collection as $entity) : ?>
        <tr id="<?php echo  $entity['idbancotransaccion']?>">
            <td><?php  echo $entity['bancotransaccion_nombre']?></td>
            <td><?php  echo $entity['bancotransaccion_descripcion']?></td>
            <td>
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/bancos/concepto/editar/".$entity['idbancotransaccion']?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-".$entity['idbancotransaccion']?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
        <!-- Delete Modal Structure -->
        <div id="delete-modal-<?php echo $entity['idbancotransaccion']?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar el concepto '". $entity['bancotransaccion_nombre']."' ?"?></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/bancos/concepto/eliminar/<?php echo $entity['idbancotransaccion']?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>       
            </div>
        </div>
        <!-- End Delete Modal Structure -->   
    <?php endforeach; ?>
    </tbody>
</table>
<script>
$(document).ready(function(){
    
    $('.modal-trigger').leanModal();
    $("#tabla-bancos").tablesorter({headers:{2:{sorter:false}}});
    $("#tabla-bancos").filterTable({inputSelector: '#search-container input',minRows:1}); 
}); 
</script>