<?php
    $title = 'Nuevo Rol';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $form->setAttribute('action', '/empleados/roles/nuevo');?>
<?php $form->setAttribute('class', 'hva-form');?>
<?php $form->prepare();?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s6">
                <div class="input-field">
                    <?php echo $this->formText($form->get('rol_nombre')); ?>
                    <?php echo $this->formLabel($form->get('rol_nombre')); ?>
                </div>
                <p id="rol_nombre" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formTextarea($form->get('rol_descripcion')); ?>
                    <?php echo $this->formLabel($form->get('rol_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Asignacion de modulos</legend>
        <div class="row">
            <div class="col s12">
                <?php foreach ($modulos as $moduloKey => $moduloValue) :?>
                    <p>
                        <input type="checkbox" class="filled-in" id="modulo-<?php echo $moduloKey?>" name="modulos[]" value="<?php echo $moduloKey?>"/>
                        <label for="modulo-<?php echo $moduloKey?>"><?php echo $moduloValue?></label>
                    </p>
                <?php endforeach;?>
            </div>
        </div>
    </fieldset>
</div>
<p style="color: #9e9e9e">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script>
    
    $(document).ready(function(){
        //Validacion de campos obligatorios 
        $(document).on('click', 'form button[type=submit]', function(e) {

            var isValid = true;
            if(!$('input[name=rol_nombre]').val().length){
               isValid = false;
               $('p#rol_nombre').show();
               
            }
            
            if(!isValid){
                e.preventDefault(); 
            }

        });
        
    });
    
        
</script>