<?php
    $title = 'Empleados';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/empleados/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nuevo Empleado</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-empleados" class="striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Usuario</th>
            <th>Correo Electronico</th>
            <th>Rol</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($empleados as $empleado) : ?>
        <tr>
            <td><?php echo $empleado['nombre'] ?></td>
            <td><?php echo $empleado['usuario'] ?></td>
            <td><?php echo $empleado['email'] ?></td>
            <td><?php echo $empleado['rol'] ?></td>
            <td>
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/empleados/editar/".$empleado['id']?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-empleado-".$empleado['id']?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
        <!-- Delete Modal Structure -->
        <div id="delete-modal-empleado-<?php echo $empleado['id']?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar el empleado '". $empleado['nombre']. "' del sistema?" ?></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/empleados/eliminar/<?php echo $empleado['id']?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>       
            </div>
        </div>
        <!-- End Delete Modal Structure -->
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(document).ready(function(){
          $("#tabla-empleados").tablesorter({headers:{3:{sorter:false}}});
          $("#tabla-empleados").filterTable({inputSelector: '#search-container input',minRows:1});
         $('.modal-trigger').leanModal();
}); 
</script>