<?php
$title = 'Consultorio: '. $consultorioForm->get('consultorio_nombre')->getValue();
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $consultorioForm->setAttribute('action', '/consultorio/editar/'.$id);?>
<?php $consultorioForm->setAttribute('class', 'hva-form');?>
<?php $consultorioForm->prepare();?>
<?php echo $this->form()->openTag($consultorioForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_nombre')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_nombre')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_descripcion')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_descripcion')); ?>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_extension')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_extension')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formCheckbox($consultorioForm->get('consultorio_enuso')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_enuso')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
