<?php
$title = 'Consultorio: '. $consultorioForm->get('consultorio_nombre')->getValue();
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $consultorioForm->setAttribute('action', '/consultorio/editar/'.$id);?>
<?php $consultorioForm->setAttribute('class', 'hva-form');?>
<?php $consultorioForm->prepare();?>
<?php echo $this->form()->openTag($consultorioForm); ?>

<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_nombre')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_nombre')); ?>
            </div>
        </div>
        <div class="col s3">
           <label for="consultorio_enuso">¿En uso?</label>
                <div class="input-field checkbox">
                    <div class="switch">
                        <label>
                          No
                          <?php if($consultorio_enuso) :?>
                                <input type="checkbox" name="consultorio_enuso" checked>
                          <?php else :?>
                                <input type="checkbox" name="consultorio_enuso">
                          <?php endif;?>
                          <span class="lever"></span>
                          Si
                        </label>
                    </div>
                </div>
        </div>
        <div class="col s3">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_extension')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_extension')); ?>
            </div>
        </div>
        <div class="col s12">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_descripcion')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_descripcion')); ?>
            </div>
            <?php /*
                <label>
                    <?php echo $this->formCheckbox($consultorioForm->get('consultorio_enuso')); ?>
                    <?php echo $this->formLabel($consultorioForm->get('consultorio_enuso')); ?>
                </label>
                */ ?>
        </div>
    </fieldset>
</div>
<p style="color: rgb(158, 158, 158); margin-top: 0px; padding-left: 24px;">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
        $(document).find('button').on('click',function(e){
            $('p.input-error-show').remove();
            var error_message = '<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>';
            var isValid = true;
            $(document).find('input[required],select[required]').filter(function(){
                if($(this).val() == ''){
                    $(this).after(error_message);
                    isValid = false;
                }
                
            });
            
            if(!isValid){
                e.preventDefault();
            }
            
        });
    });
     
</script>
