<?php
$title = 'Nuevo Consultorio';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $consultorioForm->setAttribute('action', '/consultorio/nuevo');?>
<?php $consultorioForm->setAttribute('class', 'hva-form');?>
<?php $consultorioForm->prepare();?>
<?php echo $this->form()->openTag($consultorioForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_nombre')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_nombre')); ?>
                <?php $showError=$this->formElementErrors($consultorioForm->get('consultorio_nombre'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_descripcion')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_descripcion')); ?>
                <?php $showError=$this->formElementErrors($consultorioForm->get('consultorio_descripcion'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <?php echo $this->formText($consultorioForm->get('consultorio_extension')); ?>
                <?php echo $this->formLabel($consultorioForm->get('consultorio_extension')); ?>
                <?php $showError=$this->formElementErrors($consultorioForm->get('consultorio_extension'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
            <div class="input-field">
                <span class="grey-text" style="margin-left: 40px;">¿En uso?</span>
                <div class="switch">
                    <label>
                        No
                        <?php echo $this->formCheckbox($consultorioForm->get('consultorio_enuso')); ?>
                        <span class="lever"></span>
                        Si
                    </label>
                    <?php $showError=$this->formElementErrors($consultorioForm->get('consultorio_enuso'));
                    if(!empty($showError)):
                        ?>
                        <div class="center-align col right" style="color: #e57373">
                            <i class="mdi-content-report prefix"></i>
                        </div>
                        <div class="center-align col s11 offset-s1" style="color: #e57373">
                            <?php
                            echo $showError;
                            ?>
                        </div>
                    <?php  endif;?>
                </div>
                <?php /*
                <label>
                    <?php echo $this->formCheckbox($consultorioForm->get('consultorio_enuso')); ?>
                    <?php echo $this->formLabel($consultorioForm->get('consultorio_enuso')); ?>
                </label>
                */ ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
</script>