    <?php
    $title = "Tipo: ". $tipoForm->get('tipo_nombre')->getValue();
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $tipoForm->setAttribute('action', '/catalogos/articulo/tipo/editar/'.$id);?>
<?php $tipoForm->setAttribute('class', 'hva-form');?>
<?php $tipoForm->prepare();?>
<?php echo $this->form()->openTag($tipoForm); ?>
<?php echo $this->form()->openTag($tipoForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($tipoForm->get('tipo_nombre')); ?>
                    <?php echo $this->formLabel($tipoForm->get('tipo_nombre')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formText($tipoForm->get('tipo_descripcion')); ?>
                    <?php echo $this->formLabel($tipoForm->get('tipo_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>