<?php
$title = 'Nuevo Tipo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(!$Error){
    $TipoForm->setAttribute('action', $this->url('tipo', array('action' => 'nuevo')));
    $TipoForm->prepare();

    echo $this->form()->openTag($TipoForm);
    echo $this->formCollection($TipoForm);
    echo $this->form()->closeTag();
}else{
    foreach ($Error as $errorValue){
        echo $errorValue;
    }
}