<div id="<?php echo $modalName?>" class="modal">    
    <div class="modal-content">
        <div class="row">
            <div class="col s12" style="padding-top: 20px;">
                <h4><?php echo 'Factura: #'.$modal['no_factura']?></h4>
                <h6><?php echo 'Proveedor: '.$modal['proveedor'] ?></h6>
            </div>
        </div>
        <div class="row">
            <fieldset>
                <legend>Estatus de compra</legend>
                <div class="col s4">
                    <div class="label-container">
                        <label>Fecha:</label>
                        <p><?php echo $modal['fecha'] ?></p>
                    </div>
                </div>
                <div class="col s4">
                    <div class="label-container">
                        <label>Fecha a pagar:</label>
                        <p><?php echo $modal['fechaapagar'] ?></p>
                    </div>
                </div>
                <div class="col s4">
                    <div class="label-container">
                        <label>Estatus:</label>
                        <p><?php echo $modal['status'] ?></p>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="row">
            <fieldset>
                <legend>Detalles de compra</legend>
                
                <table class="striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Cantidad</th>
                            <th>Descripcion</th>
                            <th>Costo</th>
                            <th>Importe</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $count = 1 ?>
                        <?php foreach ($modal['detalles'] as $detalle) :?>
                            <tr>
                                <td><?php echo $count?></td>
                                <td><?php echo $detalle['cantidad']?></td>
                                <td><?php echo $detalle['descripcion']?></td>
                                <td><?php echo '$'.$detalle['costo']?></td>
                                <td><?php echo '$'.$detalle['importe']?></td>
                            </tr>
                            <?php $count++;?>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <div class="col s12">
                    <div class="label-container">
                        <p style="font-size: 16px; float: right"><?php echo '$ '.$modal['importe'] ?></p>
                        <label style="font-weight: bold; font-size: 16px; float: right">Total:</label>  
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
        <a href='<?php echo "/compras/editar/".$modal['id'] ?>' class="waves-effect waves-light btn editar"><i class="mdi-action-assignment left"></i>Editar</a>
     </div>
</div>