<div id="view-modal-articulo-<?php echo $modal['id']?>" class="modal preview-articulos-registro">
    <div class="modal-content">
        <div class="row">
            <div class="col s2">
                <img width="100" height="100" src="<?php if(is_null($modal['product_photo']) || empty($modal['product_photo']) ){echo '/img/productos/no-image.png';}else{echo $modal['product_photo'];}?>">
            </div>
            <div class="col s10" style="padding-top: 20px;">
                <h6><?php echo $modal['product_name']?></h6>
                <h6><?php echo $modal['product_codigo']?></h6>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
    </div>
</div> 