<style>
    [type="checkbox"]:not(:checked), [type="checkbox"]:checked {
        left: initial;
        position: initial;
    }
    
    .ui-datepicker .ui-datepicker-title select{
        display: inline-block;
    }
    
    div#ui-datepicker-div{
        padding: 0;
        border: 0;
    }
</style>
<?php
    $title = 'Compras';
    $this->headTitle($title);
    setlocale(LC_MONETARY, 'en_US');
      
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div id="compras-list">
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/compras/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nueva compra</a>
            </div>
              <div id="search-container" class="input-field col s4 offset-s2" style="top: 215px;">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
    <div class="row" style="margin-bottom: -50px;" id="filter-container">
<div class="col s6" style="top: -26px;">
    <fieldset>
        <legend>Filtros</legend>
        <div class="row">
            <div class="col s12">
                <input type="hidden" name="idproveedor">
                <label>Por proveedor</label>
                <select multiple="multiple" class="browser-default" id="proveedor_filter">
                </select>
            </div>
        </div>

            <div class="row">
                <div class="col s6">
                    <label>Desde</label>
                    <input type="text" id="fecha_filter_from">
                </div>
                <label>Hasta</label>
                <div class="col s6">
                    <input type="text" id="fecha_filter_to">
                </div>
            </div>
        </div>

    </fieldset>
</div>
<table id="tabla-ordenes" class="striped">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Proveedor</th>
            <th >Monto</th>
            <th >Factura</th>
            <th>Pagada</th>
            <th>Fecha de pago</th>
            <th>Folio</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody> 
    <?php foreach($compras as $compra) : ?>
        <?php 
            $orden_fecha = new DateTime($compra->getOrdencompraFecha());
            $fechaJS = $orden_fecha->format('m/d/Y');
            $orden_fecha = $orden_fecha->format('d/m/Y');
                
            $orden_fechapago = $compra->getOrdencompraFechaapagar();
            if(!is_null($orden_fechapago)){
                 $orden_fechapago = new DateTime($compra->getOrdencompraFecha());
                $orden_fechapago = $orden_fechapago->format('d/m/Y');
            }
            
            
            $orden_factura = $compra->getOrdencompraFacturapdf();
            if(is_null($orden_factura) || empty($orden_factura)){
                $orden_factura = 'N/D';
            }else{
                $orden_factura = '<a target="_blank" href="'.$orden_factura.'"><img id="orden_facturapdf" src="/img/compras/pdf_default.png"><a>';
            }
            
            $orden_pagada = $compra->getOrdencompraStatus();
            if($orden_pagada == 'pagada')
                $orden_pagada = 'Si';
            elseif ($orden_pagada == 'no pagada') 
                $orden_pagada = 'No';
 
        ?>
        <?php $c = new Ordencompra(); $c?>
        <tr id="<?php echo  $compra->getIdOrdenCompra()?>">
            <td data-time="<?php echo $fechaJS ?>"><?php  echo $orden_fecha?></td>
            <td  class="proveedor_nombre" id="<?php echo $compra->getProveedor()->getIdproveedor()?>"><?php  echo $compra->getProveedor()->getProveedorNombre() ?></td>
            <td><?php  echo '$ ' .$compra->getOrdencompraImporte()?></td>
            <td><?php  echo $orden_factura ?></td>
            <td><?php  echo $orden_pagada ?></td>
            <td><?php  echo $orden_fechapago ?></td>
            <td><?php  echo $compra->getOrdenCompraNofactura() ?></td>
            <td>
            
                <a id="order_detalles"class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href='javascript:void(0)'><i class="tiny mdi-image-remove-red-eye"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/compras/editar/".$compra->getIdOrdenCompra()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-compra-".$compra->getIdOrdenCompra()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
        <!-- Delete Modal Structure -->
        <div id="delete-modal-compra-<?php echo $compra->getIdOrdenCompra()?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar la compra '". $compra->getOrdencompraNofactura(). "' de su proveedor ". $compra->getProveedor()->getProveedorNombre().'?'?></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/compras/eliminar/<?php echo $compra->getIdOrdenCompra()?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>       
            </div>
        </div>
        <!-- End Delete Modal Structure -->   
    <?php endforeach; ?>
    </tbody>
</table>
<script>
$(document).ready(function(){
        $('.modal-trigger').leanModal();
        $("#tabla-ordenes").tablesorter({headers:{3:{sorter:false},6:{sorter:false},7:{sorter:false}}});
        $("#tabla-ordenes").filterTable({inputSelector: '#search-container input',minRows:1});
        $('#compras-list').comprasreports();

    $("a#order_detalles").on('click',function(e){
        
        var idOrden = $(this).closest('tr').attr('id');
        var modalName = '#modal-order-'+idOrden+'-detalles';
        $.get(window.location.pathname+'/compradetalle',
            {idorden:idOrden},
            function(modal){
                $('table').after(modal);
                $(modalName).openModal();
            }
        );  
        
        
    });
}); 
</script>