<?php
    $title = 'Nueva compra';
    $this->headTitle($title);
    
    //Fecha
    $fecha = new DateTime();
    
    $fecha = $fecha->format('d/m/Y');
?>
<style>
    table.ui-datepicker-calendar {
        //display: none;
    }
    
    .ui-datepicker .ui-datepicker-title select{
        display: inline-block;
    }
    
    div#ui-datepicker-div{
        padding: 0;
        border: 0;
    }
    
    .ui-datepicker .ui-datepicker-prev, .ui-datepicker .ui-datepicker-next{
        //display: none;
    }
    
    .ui-widget-header{
/*        background: #E1F5FE;
        border: solid 1px #405C95;
        color: #405C95;*/
    }
    
    .ui-datepicker-title select{
        //height: 30px;
    }
</style>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" style="margin-bottom: 0px;">
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <input id="orden_fecha" name="orden_fecha" type="text" value="<?php echo $fecha?>">
                        <label for="orden_fecha">Fecha</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field">
                        <input id="orden_fechaapagar" name="orden_fechaapagar" type="text">
                        <label for="orden_fechaapagar">Fecha a pagar</label>                
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="input-field">
                            <input name="proveedor" type="text" id="proveedor_autocomplete">
                            <label for="proveedor">Proveedor *</label>
                            <input type="hidden" id="idproveedor" >
                            
                        </div>
                        <p id="orden_proveedor" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                    </div>
                </div>
            </fieldset>
        </div> 
    </div>
    <div class="col s6">
        <div class="row">
            <fieldset>
                <div class="col s6">
                    <div class="input-field">
                        <input id="orden_folio" type="text">
                        <label>Folio *</label>
                    </div>
                     <p id="orden_folio" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>  
                </div>
                <div class="col s6">
                    <div class="input-field">
                        <select name="orden_status" id="orden_status">
                            <option value="pagada">Si</option>
                            <option value="no pagada">No</option>
                        </select>
                        <label for="orden_status" class="active">Pagada</label>
                    </div>
                </div>
                <div class="col s12" style="display: none">
                    <div class="input-field">
                        <select  id="select_lugares">
                            <?php foreach ($almacenes as $almacen) :?>
                            <option value="<?php echo $almacen['idlugar']?>"><?php echo $almacen['lugar_nombre'];?></option>
                            <?php endforeach;?>
                        </select>
                        <label for="orden_status" class="active">Almacen destino</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input name="producto" type="text" id="productos_autocomplete">
                             <label for="productos">Productos</label>
                            <input type="hidden" id="idproducto">
                            <input type="hidden" id="producto_precio">
                            <input type="hidden" id="producto_costo">
                            <input type="hidden" id="producto_iva">
                        </div>
                    </div>
                    <div class="col s1" style="margin-top: 31px; padding-right: 21px; margin-right: 0px; margin-left: -21px;">
                        <i id="addproduct" style="color: #050661; cursor: pointer"class="small mdi-content-add-box"></i>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>
<p style="color: rgb(158, 158, 158); margin-top: 0px; padding-left: 24px;">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s12">
        <table id="order-items" class="table-inputs bordered ordertable">
            <thead>
                <th>Cajas</th>
                <th>Productos</th>
                <th>Costo caja</th>
                <th style="width: 280px">Producto</th>
                <th>Caducidad</th>
                <th>Costo unitario</th>
                <th>Precio venta</th>
                <th>IVA</th>
                <th>Subtotal</th>
                <th>Almacen</th>
                <th>Opciones</th>
            </thead>
            <tbody>
            </tbody>
        </table>
        <div class="row">
            <div class="col s12 ordersubtotal-container" style="background: #e1f5fe"> 
                <p style="font-size: 16px; float: right; padding-right: 24px;">Subtotal: <span id="order-subtotal">0.00</span>
            </div>
            <div class="col s12 orderiva-container" style="background: #e1f5fe"> 
                <p style="font-size: 16px; float: right; padding-right: 24px;">IVA: <span id="iva">0.00</span>
            </div>
            <div class="col s12 ordertotal-container">
                <p style="font-size: 16px; float: right; padding-right: 24px;">Total: <span id="total">0.00</span>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s6">
        <fieldset>
            <legend>Factura PDF</legend>
            <div class="file-field input-field">
                <input class="file-path validate" type="text"/>
                <div class="btn">
                  <span>PDF</span>
                  <input id="orden_pdf" name="pdf" type="file" accept=".pdf"/>
                </div>
            </div>
        </fieldset>       
    </div>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button id="save_order" style="width: 100%; height: 45px; margin-top: 15px"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<script>

    $(document).ready(function(){

        //Inicializamos el autocomplete de fecha a pagar
        $('input#orden_fechaapagar').datepicker({
            changeDay: true,
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            monthNamesShort: [ "Ene ", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" ],
   
        });
        
        $('input#orden_fecha').datepicker({
            changeDay: true,
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            monthNamesShort: [ "Ene ", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep","Oct", "Nov", "Dic" ],
                                          
                            });

         
        updateIVA();
        updateSubtotal();
        updateTotal();
         
        var proveedores;
        var productos;
        var lugares;
    
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproveedores',
            async: false,
            success: function (data) {
                proveedores = data;
            }
        });
        
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url:'/compras/getproductos',
            async: false,
            success: function (data) {
                productos = data;
            }
        });

        
        $('#proveedor_autocomplete').autocomplete({
            source:proveedores,
            select: function( event, ui ) {
                $('#idproveedor').val(ui.item.value);
                $(this).val(ui.item.label);
                event.preventDefault();
            }
        });
        
        $('#productos_autocomplete').autocomplete({
            source:productos,
            select: function( event, ui ) {
     
                $('#producto_costo').val(ui.item.costo);
                $('#producto_iva').val(ui.item.iva);
                $('#producto_precio').val(ui.item.precio);
                $('#idproducto').val(ui.item.value);
                $(this).val(ui.item.label);
                event.preventDefault();
            }
        });
//        
        
        
        //evento add product
        $('#addproduct').on('click',function(){
            if($('#productos_autocomplete').val() != ''){
                
                
                
                var idproduct = $('#idproducto').val();
                var tr = $('<tr>').attr('id',idproduct);
                var td_cantidad = $('<td id="cantidad"><span style="visibility:hidden">1</span><input type="number" min="1" value="1"></td>').appendTo(tr);
                var td_prodcaja = $('<td id="prodcaja"><input type="text"></td>').appendTo(tr);
                var td_costocaja = $('<td id="costocaja"><input type="text"></td>').appendTo(tr);
                var td_producto = $('<td id="producto" style="padding-left: 12px;">'+$('#productos_autocomplete').val()+'</td>').appendTo(tr);
                var td_caducidad = $('<td class="datepicker" id="caducidad" style="padding-left: 12px;"><span style="visibility: hidden"></span><input class="input-datepicker" type="text"></td>').appendTo(tr);
                var td_costo = $('<td id="costo" ><span style="visibility: hidden"></span><input type="text"  value="'+$('#producto_costo').val()+'" readonly></td>').appendTo(tr);
                var td_precio = $('<td id="precio" ><span style="visibility: hidden"></span><input type="text" value="'+$('#producto_precio').val()+'"></td>').appendTo(tr);
                var td_iva = $('<td data-iva="'+$('#producto_iva').val()+'" id="iva" style="padding-left: 12px;">'+formatMoney(0,'$')+'</td>').appendTo(tr);
                var td_subtotal = $('<td id="subtotal" style="padding-left: 12px;">'+formatMoney(0,'$')+'</td>').appendTo(tr);
                // ALMACEN POR REGISTRO
                var select_alamacen = $('select#select_lugares').eq(0).clone();
                var td_almacen = $('<td id="almacen">').append(select_alamacen);
                td_almacen.find('select').show();
                td_almacen.appendTo(tr);
                var td_opciones = $('<td><a id="delete_item" style="margin-left: 4px;" class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href="javascript:void(0)"><i class="tiny mdi-action-delete"></i></a></td>').appendTo(tr);
                //var td_opciones = $('<td><a id="show_item" class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href="#view-modal-articulo-'+$('#idproducto').val()+'"><i class="tiny mdi-image-remove-red-eye"></i></a>&nbsp;&nbsp;<a id="delete_item" style="margin-left: 4px;" class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href="javascript:void(0)"><i class="tiny mdi-action-delete"></i></a></td>').appendTo(tr);
                
                //Damos formato de dinero a a los input
                
                //EVento cantidad
                td_cantidad.find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
                    
                td_cantidad.find('input').on('change',function(){
                   //modifcamos el subtotal
                   var costo = parseInt($(this).closest('tr').find('#costo input').val());
                   var prodcaja = parseInt($(this).closest('tr').find('#prodcaja input').val());
                   var costocaja = parseInt($(this).closest('tr').find('#costocaja input').val());
                   var costounit = costocaja / prodcaja;
                   var cantidad = parseInt($(this).val());
                   
                   var new_subtotal2 =   ($(this).val()*costocaja)/(prodcaja*$(this).val());
                   var new_subtotal = new_subtotal2 *$(this).val()*prodcaja;
                    
                   $(this).closest('tr').find('#costo').text(formatMoney(new_subtotal2,'$'));
                   $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                    
                   //CALCULO DE IVA
                   var iva = parseFloat('0.'+$(this).closest('tr').find('#iva').attr('data-iva'));
                   var iva_producto = cantidad*prodcaja*costounit*iva;
                   //SET IVA
                   $(this).closest('tr').find('#iva').text(formatMoney(iva_producto,'$'));
                  
                   //$(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                   
                   updateIVA();
                   updateSubtotal();
                   updateTotal();
                  
 
                });
                            
                td_prodcaja.find('input').on('change',function(){
                    
                    //modifcamos el subtotal
                    var cantidad = parseInt($(this).closest('tr').find('#cantidad input').val());
                    var costo = parseInt($(this).closest('tr').find('#costo input').val());
                    var prodcaja = parseInt($(this).closest('tr').find('#prodcaja input').val());
                    var costocaja = parseInt($(this).closest('tr').find('#costocaja input').val());
                     var costounit = costocaja / prodcaja;
                    
                    var new_subtotal2 =   (cantidad*costocaja)/(cantidad*$(this).val());
                    var new_subtotal = new_subtotal2 *$(this).val()*cantidad;
                    $(this).closest('tr').find('#costo').text(formatMoney(new_subtotal2,'$'));
                    $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                    
                     //CALCULO DE IVA
                   var iva = parseFloat('0.'+$(this).closest('tr').find('#iva').attr('data-iva'));
                   var iva_producto = cantidad*prodcaja*costounit*iva;
                   //SET IVA
                   $(this).closest('tr').find('#iva').text(formatMoney(iva_producto,'$'));
                     
                    
                    //$(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));
                    
                     updateIVA();
                     updateSubtotal();
                     updateTotal();
                   

                });
                
                td_costocaja.find('input').on('change',function(){
                    //modifcamos el subtotal
                    var cantidad = parseInt($(this).closest('tr').find('#cantidad input').val());
                    var costo = parseInt($(this).closest('tr').find('#costo input').val());
                    var prodcaja = parseInt($(this).closest('tr').find('#prodcaja input').val());
                    var costocaja = parseInt($(this).closest('tr').find('#costocaja input').val());
                    var costounit = costocaja / prodcaja;

                    var new_subtotal2 =   ($(this).val()*cantidad)/(prodcaja*cantidad);
                    var new_subtotal = new_subtotal2 *cantidad*prodcaja;
                    $(this).closest('tr').find('#costo').text(formatMoney(new_subtotal2,'$'));
                    $(this).closest('tr').find('#subtotal').text(formatMoney(new_subtotal,'$'));

                    //CALCULO DE IVA
                   var iva = parseFloat('0.'+$(this).closest('tr').find('#iva').attr('data-iva'));
                   var iva_producto = cantidad*prodcaja*costounit*iva;
                   //SET IVA
                   $(this).closest('tr').find('#iva').text(formatMoney(iva_producto,'$'));
                     
                    
                    updateIVA();
                    updateSubtotal();
                    updateTotal();

                });
                                
                //EVento precio
                td_precio.find('input').on('keydown', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
                        
               //evento delete
               td_opciones.find('#delete_item').on('click',function(){
                   //Eliminamos el datepicker
                   td_caducidad.find('input').datepicker( "destroy" );
                   $(this).closest('tr').remove();
                   
                    updateIVA();
                    updateSubtotal();
                    updateTotal();   
               });
               
               //Evento show item
               td_opciones.find('#show_item').on('click',function(){
                   var idproduct = tr.attr('id');
                   var modalName = '#view-modal-articulo-'+idproduct;
                   var productName = td_producto.text();
                   $.get('/compras/getarticulobyid',
                        {idarticulovariante:idproduct,product_name:productName},
                        function(modal){
                            $('table').after(modal);
                            $(modalName).openModal();
                        }
                    ); 
                   
               })
 
               $('tbody').append(tr);
  
                //Evento caducidad
               $('input.input-datepicker').on('focus',function(){
                   //Cambiamos los estilos;
                   $('table.ui-datepicker-calendar').css('display','none');
                    var $this = $(this);
                     if(!$this.data('datepicker')) {
                        $this.removeClass("hasDatepicker");
                        $(this).datepicker({
                            changeMonth: true,
                            changeYear: true,
                            dateFormat: 'mm/yy',
                            defaultDate: '01/01/20',
                            monthNamesShort: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ],
                            onClose: function(dateText, inst) { 
                                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                                $(this).datepicker('setDate', new Date(year, month, 1));
                                //mantenemos los estilos;
                                $('table.ui-datepicker-calendar').css('display','none');
                            },
                        });
                        $this.datepicker("show");
                     }
                   
                });
                
                
               
                $('#productos_autocomplete').val('');
                
                //updateTotal();
                //updateIVA();
      
            }else{
                alert('No hay productos por agregar');
            }
        });
        
        //Evento Save
        $('#save_order').on('click',function(e){
            //Valida los campos requeridos
            var isValid = true;
            
            if($('#proveedor_autocomplete').val() == ''){
                isValid = false;
                $('p#orden_proveedor').show();
            }else{
                $('p#orden_proveedor').hide();
            }
            
            if($('input#orden_folio').val() == ''){
                isValid = false;
                $('p#orden_folio').show();
            }else{
                $('p#orden_folio').hide();
            }
            
            if(isValid){
              //Verificamos que almenos se tenga un item
              var rowCount = $('tbody').children().length;
              
              if(rowCount >= 1){
                  
                  //PDF
                  var orden_facturapdf = null;

                  if($('input[name=pdf]').val() != ''){
                    
                    var inputFile = document.getElementById('orden_pdf');
                    var file = inputFile.files[0];
                    var data = new FormData();
                    data.append('archivo',file);
                    $.ajax({
                        url:'/compras/uploadcomprapdf',
                        type:'POST',
                        contentType:false,
                        data:data,
                        processData:false,
                        cache:false,
                        async: false,
                        success: function (data) {
                            var response = JSON.parse(data);
                            orden_facturapdf = response.compra_facturapdf;
                        }  
                    });
  
                 }
                  
                  //Guardamos la informacion de la orden en un objeto
                  var orden = { 
                      orden_facturapdf:orden_facturapdf,
                      orden_fecha:$('input#orden_fecha').val(),
                      orden_folio: $('input#orden_folio').val(),
                      orden_proveedor : $('input#idproveedor').val(),
                      orden_status : $('select[name=orden_status]').val(),
                      //orden_lugar : $('select[name=idlugar]').val(),
                      orden_importe: $('#total').text(),
                      orden_iva: $('span#iva').text(),
                      orden_fechaapagar:$('input#orden_fechaapagar').val(),
                      orden_items : new Array(),
                  }
                            
                  //Hacemos un foreach a nuestros items de la orden
                  $.each($('table.ordertable tbody').children(),function(index,element){
                         
                    if($(element).attr('id') !== 'undefined'){
                        var item = {
                            idarticulovariante: $(element).attr('id'),
                            ordencompradetalle_caducidad        : $(element).find('td#caducidad').find('input').val(),
                            ordencompradetalle_cantidad         : parseInt($(element).find('td#cantidad').find('input').val()),
                            ordencompradetalle_productosporcaja : parseInt($(element).find('td#prodcaja').find('input').val()),
                            ordencompradetalle_costocaja        : parseInt($(element).find('td#costocaja').find('input').val()),
                            ordencompradetalle_costo            : (parseInt($(element).find('td#cantidad').find('input').val())*parseInt($(element).find('td#costocaja').find('input').val()))/(parseInt($(element).find('td#cantidad').find('input').val())*parseInt($(element).find('td#prodcaja').find('input').val())),
                            ordencompradetalle_precio           : $(element).find('td#precio').find('input').val(),
                            ordencompradetalle_importe          : $(element).find('td#subtotal').text(),
                            ordencompradetalle_iva              : $(element).find('td#iva').text(),
                            ordencompradetalle_lugar            : $(element).find('td#almacen select').val(),
                        }
                        orden.orden_items.push(item);
                    }
                  });
                  
                  
                $.post('/compras/guardarorden',
                    {orden:orden},
                    function(response){
                       if(response){
                           window.location.replace("/compras");
                       }
                    }
                );
           
              }else{
                  alert('Debe tener por lo menos un item en su factura para guardarla');
              }
            }else{
                e.preventDefault();
            }
            
            
        });
        
        function formatMoney(n, currency) {
            return currency + " " + n.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,");
        }
        
       function updateTotal(){
           var total = 0;
           $.each($('td#subtotal'),function(index,element){
               var subtotalText = $(element).text();

               var split = subtotalText.split('$');
               var subtotal =  split[1];

               subtotal = subtotal.replace(',','');
               total= (parseFloat(total) + parseFloat(subtotal));
               
           });
           
           //SUMAMOS EL IVA
           var ivaText = $('span#iva').text();
           var split = ivaText.split('$');
           var iva =  split[1];
           iva = iva.replace(',','');
           
           total = total + parseFloat(iva);
           
              
           $('#total').text(formatMoney(total,'$'));
           
       }
       
       function updateIVA(){
           var total = 0;
           $.each($('td#iva'),function(index,element){
  
                var ivaText = $(element).text();
                var split = ivaText.split('$');
                var iva =  split[1];
                
                iva = iva.replace(',','');
                total= (parseFloat(total) + parseFloat(iva));
                
                 
           });
           
           $('span#iva').text(formatMoney(total,'$'));
       }
       
       function updateSubtotal(){
           var total = 0;
           $.each($('td#subtotal'),function(index,element){
               var subtotalText = $(element).text();

               var split = subtotalText.split('$');
               var subtotal =  split[1];

               subtotal = subtotal.replace(',','');
               total= (parseFloat(total) + parseFloat(subtotal));
               
           });
           console.log(total);
           $('#order-subtotal').text(formatMoney(total,'$'));
           
       }

    });


</script>