<!-- Delete Modal Structure -->
<span id="idorden" style="visibility: hidden"><?php echo $id ?></span>
<div id="delete-modal-facturapdf-<?php echo $id?>" class="modal ">
    <div class="modal-content" id="delete-modal-container">
        <div class="row" id="delete-modal-header-container">
            <div class="col s5 offset-s4">
                <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <p><?php echo "Esta seguro que desea eliminar la factura de su orden?" ?></p>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
        <a id="remove_factura" href="javascript:void(0)" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>
    </div>
</div>
<script>
    $('a#remove_factura').on('click',function(){
        
        var id = <?php echo $id ?>;
        var modalName = '#delete-modal-facturapdf-'+id;
        
        $.post(
                 '/compras/removefacturapdf',
                 {id: id, html:false},
                 function (response){
                    if(response){
                        $(modalName).closeModal();
                        $('fieldset#pdf-container').find('div').remove();
                        $('fieldset#pdf-container').find('a').remove();
                        $('fieldset#pdf-container').append('<div class="file-field input-field"><input class="file-path validate" type="text"/> <div class="btn"> <span>PDF</span> <input id="orden_pdf" name="pdf" type="file" accept=".pdf"/></div></div>');
                        $.getScript('/js/materialize.js');
                    }
                 }
                 
        );
    });
    
</script>
