<?php
    $title = 'Registro Nueva Cuneta';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $bancoForm->setAttribute('action', '/catalogos/banco/nuevo');?>
<?php $bancoForm->setAttribute('class', 'hva-form');?>
<?php $bancoForm->prepare();?>
<?php echo $this->form()->openTag($bancoForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($bancoForm->get('banco_nombre')); ?>
                    <?php echo $this->formLabel($bancoForm->get('banco_nombre')); ?>
                </div>
            </div>
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($bancoForm->get('banco_cuenta')); ?>
                    <?php echo $this->formLabel($bancoForm->get('banco_cuenta')); ?>
                </div>
            </div>
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($bancoForm->get('banco_balance')); ?>
                    <?php echo $this->formLabel($bancoForm->get('banco_balance')); ?>
                </div>
            </div>
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formText($bancoForm->get('banco_descripcion')); ?>
                    <?php echo $this->formLabel($bancoForm->get('banco_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

  
