<?php
    $title = "Cuarto: ". $cuartoForm->get('cuarto_nombre')->getValue();
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $cuartoForm->setAttribute('action', '/catalogos/cuarto/editar/'.$id);?>
<?php $cuartoForm->setAttribute('class', 'hva-form');?>
<?php $cuartoForm->prepare();?>
<?php echo $this->form()->openTag($cuartoForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s6">
                <div class="input-field">
                    <?php echo $this->formText($cuartoForm->get('cuarto_nombre')); ?>
                    <?php echo $this->formLabel($cuartoForm->get('cuarto_nombre')); ?>
                </div>
            </div>
            <div class="col s3">
                <?php echo $this->formLabel($cuartoForm->get('cuarto_enuso')); ?>
                <div class="input-field checkbox">
                    <div class="switch">
                        <label>
                          No
                          <input type="checkbox" name="cuarto_enuso" value="TRUE">
                          <span class="lever"></span>
                          Si
                        </label>
                    </div>
                </div>
            </div>
            <div class="col s3">
                <div class="input-field">
                    <?php echo $this->formText($cuartoForm->get('cuarto_extension')); ?>
                    <?php echo $this->formLabel($cuartoForm->get('cuarto_extension')); ?>
                </div>
            </div>
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formText($cuartoForm->get('cuarto_descripcion')); ?>
                    <?php echo $this->formLabel($cuartoForm->get('cuarto_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>