<?php
    $title = 'Cuartos';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<!--<p>
    <a href="<?php echo $this->url('cuarto', array('action'=>'nuevo'));?>">Nueva cuarto</a>
</p>-->
<div class="row" id="table-header">
    <div class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/catalogos/cuarto/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nuevo Cuarto</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </div>
</div>
<table id="tabla-cuartos" class="table striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th >¿En uso?</th>
            <th >Extension</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($cuartos as $cuarto) : ?>
        <tr>
            <td><?php echo $cuarto->getCuartoNombre() ?></td>
            <td><?php echo $cuarto->getCuartoDescripcion() ?></td>
            <td><?php if($cuarto->getCuartoEnuso()) echo "SI"; else echo "NO" ?></td>
            <td><?php echo $cuarto->getCuartoExtension() ?></td>
            <td>
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/catalogos/cuarto/editar/".$cuarto->getIdcuarto()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-cuarto-".$cuarto->getIdcuarto()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
        <!-- Delete Modal Structure -->
        <div id="delete-modal-cuarto-<?php echo $cuarto->getIdCuarto()?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar el cuarto ". $cuarto->getCuartoNombre(). " de su catalogo?" ?></p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/catalogos/cuarto/eliminar/<?php echo $cuarto->getIdCuarto()?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>
              
            </div>
        </div>
        <!-- End Delete Modal Structure -->
    <?php endforeach; ?>
    </tbody>
</table>
<script>
$(document).ready(function(){
        $("#tabla-cuartos").tablesorter({headers:{4:{sorter:false},1:{sorter:false}}});
        $("#tabla-cuartos").filterTable({inputSelector: '#search-container input',minRows:1});
        $('.modal-trigger').leanModal();
}); 
</script>