<?php
    $title = 'Generar factura';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div id="facturar-generar">
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
         <div class="col s4">
            <div class="label-container">
               <label>Fecha:</label>
               <p><?php echo $general_info['fecha']?></p>
           </div>
         </div>
        <div class="col s4">
            <div class="label-container">
               <label>#Movimiento:</label>
               <p><?php echo $general_info['id']?></p>
           </div>
         </div>
        <div class="col s4">
            <div class="label-container">
               <label>Paciente:</label>
               <p><?php echo $general_info['paciente']?></p>
           </div>
        </div>
        <div class="col s4">
            <div class="label-container">
               <label>Medico:</label>
               <p><?php echo $general_info['medico']?></p>
           </div>
        </div>
        <div class="col s4">
            <div class="label-container">
               <label>Fecha de pago:</label>
               <p><?php echo $general_info['pagada']?></p>
           </div>
        </div>
        <div class="col s4">
            <div class="label-container">
               <label>Tipo de pago:</label>
               <p><?php echo $general_info['tipo_pago']?></p>
           </div>
        </div>
        <div class="col s4">
            <div class="label-container">
               <label>Total:</label>
               <p class="money"><?php echo $general_info['total']?></p>
           </div>
        </div>
        <div class="col s4">
            <div class="label-container">
               <label>Tipo:</label>
               <p><?php echo $general_info['tipo']?></p>
           </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <a id="new_taxdata" href="javascript:void(0)"><i class="mdi-content-add-circle-outline prefix"></i>Nuevos datos de facturacion</a>
    <fieldset>
         <legend>Datos de facturacion</legend>
         <div id="taxdata" class="col s12">
             <?php foreach ($facturacion_info as $info) :?>
                <p>
                    <input name="datos_facturacion" type="radio" id="<?php echo $info['idpacientefacturacion']?>" />
                    <label for="<?php echo $info['idpacientefacturacion']?>"><?php echo $info['pacientefacturacion_razonsocial'].' - '.$info['pacientefacturacion_rfc']?></label>
                </p>
             <?php endforeach;?>

         </div>
    </fieldset>
</div>
<div class="row">
<div class="col s4 offset-s4">
    <button id="generar" style="width: 100%; height: 45px;"class="btn waves-effect waves-light " name="action">Generar Factura
    </button>
</div>
</div>
</div>
<script src="/js/facturar-generar.js"></script>
<script>
    
    $('.money').filter(function(){
        var text = $(this).text();
        var money = accounting.formatMoney(text);
        $(this).text(money);
    });
    
    $('#facturar-generar').facturarGenerar({
        general_info:<?php echo json_encode($general_info)?>,
    });

</script>    

