<div id="nuevosdatosfacturacion" class="modal">    
    <div class="modal-content">
        <h4>Registrar nuevos datos de facturacion</h4>
    </div>
    <div class="row">
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_razonsocial" required>
                <label>Razon social *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_rfc" required>
                <label>RFC *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_calle" required>
                <label>Calle *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_noexterior" required>
                <label>No. Exterior *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_nointerior">
                <label>No. Interior</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_colonia" required>
                <label>Colonia *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_ciudad" required>
                <label>Ciudad *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_estado" required>
                <label>Estado *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_pais" required>
                <label>Pais *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_codigopostal" required>
                <label>Codigo postal *</label>
            </div>
        </div>
        <div class="col s6">
            <div class="input-field">
                <input type="text" name="pacientefacturacion_email">
                <label>Correo electronico</label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
        <a id="save" href="#!" class="waves-effect waves-light btn editar"><i class="mdi-action-assignment left"></i>Guardar</a>
     </div>
</div>
<script>

   

</script>