<?php
    $title = 'Nuevo Articulo';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $articuloForm->setAttribute('action', '/catalogos/articulo/nuevo');?>
<?php $articuloForm->setAttribute('class', 'hva-form');?>
<?php $articuloForm->prepare();?>
<?php echo $this->form()->openTag($articuloForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s8">
                <div class="input-field">
                    <?php echo $this->formText($articuloForm->get('articulo_nombre')); ?>
                    <?php echo $this->formLabel($articuloForm->get('articulo_nombre')); ?>
                </div>
            </div>
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formSelect($articuloForm->get('idtipo')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formText($articuloForm->get('articulo_descripcion')); ?>
                    <?php echo $this->formLabel($articuloForm->get('articulo_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset>
        <legend>Propiedades</legend>
        <div class="row" id="propiedad_1">
            <div class="col s4">
                <div class="input-field" id="propiedad_nombre_1">
                    <label for="propiedad_nombre">Nombre</label>
                    <input type="text" name="propiedad_1_nombre">
                </div>
            </div>
            <div class="col s4 offset-s4" id="propiedad_1_valor_1">
                <div class="input-field">
                    <label for="propiedad_1_valor_1">Valor</label>
                    <input type="text" name="propiedad_1_valor_1">
                    <a href="javascript:void(0)"><i style="bottom: 0;display: none"class="tiny mdi-action-delete prefix cerrar"></i></a>
                    <p style="display: none"class=input-error>Por favor ingrese un valor</p>
                </div>
            </div>
            <div class="row" id="propiedad_1_valores">
                    
            </div>
            <div class="row">
                <div class="col s4 offset-s8">
                    <button type="button" id="new_property_value" style="width: 100%; height: 45px;"class="btn waves-effect waves-light">Nueva Propiedad
                        <i class="mdi-content-save left"></i>
                    </button>
                </div>
            </div>
        </div>

    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        
        $('#ArticuloForm'   ).formcache();
        
        var propertyCount = 1;
        
        $('select').material_select();
        
        //Eventos
        $('#new_property_value').click(function(){
            
        //Contamos cuantos valores hay por propiedad hasta el momento
        var valuePerPropertyCount = $("#propiedad_"+propertyCount).find('input[name*="valor"]').length;
        
        //Verificamos que los campos del valor no esten vacios
        if($("#propiedad_" + propertyCount + "_valor_"+ valuePerPropertyCount + " input[name=propiedad_"+propertyCount+"_valor_"+valuePerPropertyCount+"]").val() !== ""){
            
            //Escondemos nuestro parrafo de error independientemete si esta o no esta
            $("#propiedad_" + propertyCount + "_valor_"+ valuePerPropertyCount).find('p').hide();
            
            //Construimos nuestros html de nuestro nuevo input
            var divContainer = $('<div class="col s4 offset-s8" id="propiedad_'+propertyCount+'_valor_'+(valuePerPropertyCount+1) +'">');
            
            var inputContainer = $('<div class="input-field">');
            
            //Nuestro Label
            var label = $('<label for="propiedad_'+propertyCount+'_valor_'+(valuePerPropertyCount+1) +'">Valor</label>');
            label.appendTo(inputContainer);
            
            //Nuestro input
            var input = $('<input type="text" name="propiedad_'+propertyCount+'_valor_'+(valuePerPropertyCount+1) +'">');
            input.appendTo(inputContainer);
            
            //Nuestro boton delete
            var deleteInput = $('<a href="javascript:void(0)"><i style="bottom: 0;display: none"class="tiny mdi-action-delete prefix cerrar"></i></a>');
            deleteInput.appendTo(inputContainer);
            
            //Nuestro mensaje en caso de error
            var pError = $('<p style="display: none"class=input-error>Por favor ingrese un valor</p>');
            pError.appendTo(inputContainer);
            
            //Juntamos todo
            divContainer.append(inputContainer);
            //Mostramos nuestro div container, deshabilitamos el de atras y ponemos icono de eliminar;
            $('#propiedad_'+propertyCount+'_valores').append(divContainer);
            
            $('#propiedad_'+propertyCount+'_valor_'+valuePerPropertyCount).find('input').attr('readonly',true);
            
            $('#propiedad_'+propertyCount+'_valor_'+valuePerPropertyCount).find('i').show();
            
            
        }else{
            $('#propiedad_'+propertyCount+'_valor_'+valuePerPropertyCount).find('p').show();
        }
            
        });
        
        
        //Eliminacion de valor
        $(document).on('click','i.mdi-action-delete',function(){
            console.log($(this).closest('div.input-field').parent().remove());
        }); 
        
        
    });
</script>