<?php
    $title = 'Nuevo Articulo';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $articuloForm->setAttribute('action', '/catalogos/articulo/nuevo');?>
<?php $articuloForm->setAttribute('class', 'hva-form');?>
<?php $articuloForm->prepare();?>
<?php echo $this->form()->openTag($articuloForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s8">
                <div class="input-field">
                    <?php echo $this->formText($articuloForm->get('articulo_nombre')); ?>
                    <?php echo $this->formLabel($articuloForm->get('articulo_nombre')); ?>
                </div>
                <p id="articulo_nombre" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            </div>
            <div class="col s4" style="margin-top: 0px;"> 
                <div class="input-field">
                    <?php echo $this->formSelect($articuloForm->get('idtipo')); ?>
                </div>
                <p id="idtipo" class="input-error"> <i class="tiny mdi-alert-error"></i>Por favor seleccine un tipo de articulo</p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="input-field">
                    <?php echo $this->formText($articuloForm->get('articulo_descripcion')); ?>
                    <?php echo $this->formLabel($articuloForm->get('articulo_descripcion')); ?>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<a href="javascript:void(0)" id="new_property" ><i class="mdi-content-add-circle-outline prefix"></i>Agregar propiedad</a>
<br><br>
<div class="row">
    <fieldset id="properties">
        <legend>Propiedades</legend>
        <div class="row" id="propiedad-1">
            <div class="col s4">
                <div class="input-field" id="property_name">
                    <label for="propiedad_nombre">Nombre</label>
                    <input type="text" name="propiedad-1[nombre]">
                </div>
            </div>
            <div class="col s4 offset-s4" id="valores-1">
                <div class="input-field" id="property_values">
                    <label for="propiedad">Valor</label>
                    <input type="text" name="propiedad-1[]">
                    <a href="javascript:void(0)"><i style="bottom: 0;"class="tiny mdi-content-add-circle-outline prefix"></i></a>
                    <p style="display: none"class=input-error>Por favor ingrese un valor</p>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<p style="color: #9e9e9e">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {        
        //Utilizamos plugin de cache para almacenar los valores del formunlario en cache en caso de error
        //$('#ArticuloForm'   ).formcache();
        
        //Inicializamos el select de materialize
        $('select').material_select();
        
        var propertyCount = $('div.row[id|=propiedad]').length;

        ///////////
        //EVENTOS//
        ///////////
        
        //Agregar nueva propiedad
        $(document).on('click','#new_property',function(){
            
            var row = $('<div>'); row.addClass('row'); row.attr('id','propiedad-' + (propertyCount + 1) );
            var colName = $('<div>').addClass('col s4');
            //Clonamos nuestro elemento principal de propiedades
            $.get('/template/porpiedadArticulo.html',function(data){
                var clone = $(data);
                //Agregamos el icono de eliminar
                clone.append(' <a href="javascript:void(0)"><i class="tiny  mdi-navigation-cancel"></i></a>');
                //Reseteamos nuestros imput a blanco y removemos las clases activas
                clone.find('input').val('');
                clone.find('label').removeClass('active');
                //Cmbiamos los nombres de nuestros inputs y nuestro row contenedor
                clone.find('#valores-1').attr('id','valores-'+(propertyCount + 1));
                clone.attr('id','propiedad-' + (propertyCount + 1));
                clone.find('#property_name input').attr('name','propiedad-' + (propertyCount + 1) + '[nombre]');
                clone.find('#property_values input').attr('name','propiedad-' + (propertyCount + 1) + '[]');
                //Lo imprimimos en pantalla y sumamos al contador
                $('fieldset#properties').append('<hr id="'+(propertyCount + 1)+'">');
                $('fieldset#properties').append(clone);
                propertyCount++;
            });
        });
                 
         //cerrar propiedad
         $(document).on('click','i.mdi-navigation-cancel',function(){
            var rowContainer = $(this).closest('div.row[id|=propiedad]');
            var rowId = rowContainer.attr('id').split('-'); rowId= rowId[1] ;
            $('hr#'+rowId).remove();
            rowContainer.remove();
         });
         
         //Nuevos valores
         $(document).on('click','i.mdi-content-add-circle-outline',function(){  
             var rowContainer = $(this).closest('div.row[id|=propiedad]');
             var rowId = rowContainer.attr('id').split('-'); rowId= rowId[1] ;
             
             //Colanamos html para tomar de referencia nuestro nue valor
             $.get('/template/propiedadValorArticulo.html',function(data){
                var clone = $(data);
                //Ajustamos las columns
                clone.removeClass();
                clone.addClass('col s4 offset-s8');
                
                //Cambiamos nombres de nuestros inputs
                clone.find('input').val(''); clone.find('label').removeClass('active');
                clone.find('input').attr('name','propiedad-'+rowId+ '[]');
                
                //Insertamos
                rowContainer.append(clone);
             });
             
              //Remplazamos el icono por el de eliminar
             $(this).removeClass('mdi-content-add-circle-outline');
             $(this).addClass('mdi-action-delete');

         });
         
         //eliminacion de valores
          $(document).on('click','i.mdi-action-delete',function(){
             var rowContainer = $(this).closest('div.row[id|=propiedad]');
             var rowId = rowContainer.attr('id').split('-'); rowId= rowId[1];
             
             $(this).closest('div#property_values').parent().remove(); //Eliminamos
             
             //Ajustamos el offstet del que quede siempre hasta arriba
              var first = $("div#propiedad-"+rowId).find('div#property_values').first();
              first.parent().removeClass('offset-s8').addClass('offset-s4');
          });
          
        //Validacion de campos obligatorios 
        $(document).on('click', 'form button[type=submit]', function(e) {
            $('p.input-error').hide();
            var isValid = true;
            //console.log($('select[name=idtipo]').val());
            if(!$('input[name=articulo_nombre]').val().length){
               isValid = false;
               $('p#articulo_nombre').show();
               e.preventDefault(); 
            }
            
            if($('select[name=idtipo]').val() ===''){
                isValid = false;
                $('p#idtipo').show();
                e.preventDefault(); 
            }

        });
          
          


    });
</script>
