<?php
    $title = 'Facturas canceladas';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-empleados" class="table striped">
    <thead>
        <tr>
            <th>Fecha de cancelacion</th>
            <th># Movimiento</th>
            <th>UUID</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($collection as $entity) :?>
        <tr id="<?php echo $entity['id']?>">
            <td><?php echo $entity['fecha']?></td>
            <td><?php echo $entity['movimiento']?></td>
            <td><?php echo $entity['uuid']?></td>
            <td>
                <a download href="/tmp/xml/<?php echo $entity['movimiento'].'.xml'?>"><img src="/img/icons/xml_icon.png"></a>
                &nbsp;&nbsp;
                <a href="/tmp/pdf/<?php echo $entity['movimiento'].'.pdf'?>"><img src="/img/icons/pdf_icon.png"></a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(document).ready(function(){
         $("#tabla-empleados").tablesorter({headers:{3:{sorter:false}}});
         $("#tabla-empleados").filterTable({inputSelector: '#search-container input',minRows:1});
         $('.modal-trigger').leanModal();
         $('.money').filter(function(){
             var text = $(this).text();
             var money = accounting.formatMoney(text);
             $(this).text(money);
         });
}); 
</script>