<style>
    table.ui-datepicker-calendar {
        display: none;
    }
    
    .ui-datepicker .ui-datepicker-title select{
        display: inline-block;
    }
    
    div#ui-datepicker-div{
        padding: 0;
        border: 0;
    }
    
    .ui-datepicker .ui-datepicker-prev, .ui-datepicker .ui-datepicker-next{
        display: none;
    }
    
    .ui-widget-header{
        background: #E1F5FE;
        border: solid 1px #405C95;
        color: #405C95;
    }
    
    .ui-datepicker-title select{
        height: 30px;
    }
</style>
<div id="<?php echo "add-modal-articulo-".$idarticulovariante?>" class="modal">
  <div class="modal-content">
      <h4><?php echo $articulovariante->getArticulo()->getArticuloNombre() ?></h4>
      <i><h6><?php echo $descripcion?></h6></i>
      <form action="/productos/existencias/addexistencias" method="POST">
      <input type="hidden" name="idarticulovariante" value="<?php echo $idarticulovariante?>">
      <table class="table bordered">
          <thead>
            <th></th>
            <?php foreach($lugares as $lugar) :?>
              <th><?php echo $lugar->getLugarNombre()?></th>
            <?php endforeach;?>
         </thead>
         <tbody>
             <tr>
                 <td>Cantidad</td>
                 <?php foreach($lugares as $lugar) :?>
                 <input name="<?php echo str_replace(' ','',$lugar->getLugarNombre()).'[idlugar]'?>" type="hidden" value="<?php echo $lugar->getIdlugar()?>">
                 <td><input name="<?php echo str_replace(' ','',$lugar->getLugarNombre()).'[cantidad]'?>" type="number"></td>
                 <?php endforeach;?>
             </tr>
             <tr>
                 <td>Caducidad</td>
                 <?php foreach($lugares as $lugar) :?>
                 <td><input class="datepicker" name="<?php echo str_replace(' ','',$lugar->getLugarNombre()).'[caducidad]'?>" type="text"></td>
                 <?php endforeach;?>
             </tr>
         </tbody>
      </table>
      </form>
  </div>
  <div class="modal-footer">
        <a id="save" href="#!" class="btn waves-effect waves-light"><i class="mdi-content-save left"></i>Guardar</a>
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
    </div>
</div>
<script>
$('.datepicker').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'mm/y',
            defaultDate: '01/01/20',
            monthNamesShort: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ],
            onClose: function(dateText, inst) { 
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
            }
        });


        $('a#save').on('click',function(){
            $('form').submit();
        });

</script>