<style>
    table.ui-datepicker-calendar {
        display: none;
    }
    
    .ui-datepicker .ui-datepicker-title select{
        display: inline-block;
    }
    
    div#ui-datepicker-div{
        padding: 0;
        border: 0;
    }
    
    .ui-datepicker .ui-datepicker-prev, .ui-datepicker .ui-datepicker-next{
        display: none;
    }
    
    .ui-widget-header{
        background: #E1F5FE;
        border: solid 1px #405C95;
        color: #405C95;
    }
    
    .ui-datepicker-title select{
        height: 30px;
    }
</style>
<div id="<?php echo $modalName?>" class="modal">
  
  <div class="modal-content">
        <h4><?php echo $modal['lugar_nombre']?></h4>
        <div class="row">
            <div class="col s12">
                <fieldset>
                    <legend>Producto</legend>
                    <p style="color: #00086e;margin: 0"><?php echo $modal['nombre']?></p>
                </fieldset>
                <fieldset>
                    <legend>Descripcion</legend>
                    <p style="color: #00086e;margin: 0"><?php echo $modal['descripcion']?></p>
                </fieldset>
                <fieldset>
                    <legend>Existencias</legend>
                    <p style="color: #00086e;margin: 0"><?php echo $modal['existencias']?></p>
                </fieldset>
                <form action="/productos/existencias/caducidadbylugar" method="POST">
                    <input type="hidden" name="idlugar" value="<?php echo $modal['idlugar']?>">
                    <input type="hidden" name="idarticulovariante" value="<?php echo $modal['id']?>">
                    <div style="margin: 0"class="row">
                        <div class="col s12">
                            <a style="float: right" id="newCaducidad" href="javascript:void(0)"><i style="bottom: 14;"class="mdi-content-add-circle-outline prefix"></i>Agregar nueva existencia</a>
                        </div>
                    </div>
                    <fieldset id="caducidades">
                        <legend>Caducidades</legend>
                        <?php foreach ($modal['caducidad'] as $key => $value) :?>
                        <div class="row" style="margin: 0">
                                <input type="hidden" name="<?php echo 'ocd-'.$value['idordendetallecompra'].'[id]'?>" value="<?php echo $value['idordendetallecompra']?>">
                                <div class="col s4">  
                                    <div class="input-field number">
                                        <label class="active" for="cantidad">Cantidad</label>
                                        <input class="existenacias_cantidad" type="text" name="<?php echo 'ocd-'.$value['idordendetallecompra'].'[cantidad]'?>" value="<?php echo (int)$value['cantidad']?>">
                                        <p class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                                    </div>
                                </div>
                                <div class="col s4">
                                    <div class="input-field">
                                        <label class="active" for="fecha">Fecha</label>
                                        <input class="datepicker" type="text" name="<?php echo 'ocd-'.$value['idordendetallecompra'].'[caducidad]'?>" value="<?php echo $value['caducidad']?>">                               
                                    </div>
                                </div>
                        </div> 
                        <?php endforeach;?>
                    </fieldset>
                </form>
            </div>
        </div>
  </div>
  <div class="modal-footer">
        <a id="save" href="#!" class="btn waves-effect waves-light"><i class="mdi-content-save left"></i>Guardar</a>
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
    </div>
</div>
<script>
    
    $(function() {
	
        $('.datepicker').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'mm/y',
            defaultDate: '01/01/20',
            monthNamesShort: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ],
            onClose: function(dateText, inst) { 
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
            }
        });
        
        
        $('a#save').on('click',function(){
            var flag = true;
            var modal = $(this).closest('div.modal');
            $.each(modal.find('input.existenacias_cantidad'),function(index,element){
                if($(element).val().length <= 0){
                    flag = false;
                    $(this).next('p.input-error').show();
                }
               
            });
       
            if(flag){
                $('form').submit();
            }
            
        });
        
                
        $('a#newCaducidad').click(function(){
            $.get('/template/caducidadModal.html',function(html){
                var source = $('<div>' + html + '</div>');
                var newRow = source.children('div.row');
                var id = $.now();
                
                newRow.find('.datepicker').datepicker({
                    changeMonth: true,
                    changeYear: true,
                    dateFormat: 'mm/y',
                    monthNamesShort: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ],
                    onClose: function(dateText, inst) { 
                        var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                        var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                        $(this).datepicker('setDate', new Date(year, month, 1));
                    }
                });
                
                //El evento deleterow
                newRow.find('i.mdi-navigation-cancel').on('click',function(){
                    newRow.remove();
                });
                
                //Le damos la clase y agregamo el <p> para en caso de error
                newRow.find('input#cantidad').addClass('existenacias_cantidad');
                newRow.find('input#cantidad').after(' <p class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>');
                
                //Le damos nombres a nuestro inputs
                newRow.find('input#cantidad').attr('name','ocd-'+id+'[cantidad]');
                newRow.find('input#caducidad').attr('name','ocd-'+id+'[caducidad]');

                $('fieldset#caducidades').append(newRow);
            })
        });
        
        
              	
    });
    
    
    
</script>