<style>
    .filter-container input[type=text]{
        background-color: #fff;
        border: 1px solid #aaa;
        border-radius: 4px;
        
        color: #444;
        height: 26px;
        line-height: 26px;
        overflow: hidden;
        padding: 0;
        padding-left: 8px;
        text-align: left;
        text-decoration: none;
        white-space: nowrap;
        width: 100%;
        margin: 0;
        font-size: 12px;
    }
    
    .filter-container input[type=text]:focus{
        border: 1px solid #aaa;
        box-shadow: none;
    }
</style>
<?php
$title = 'Reporte de ingresos';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<script src="/js/reportes_ingresos.js"></script>
<div id="report-container">
<div class="filter-container row" >
    
    <div class="col s6">
        <fieldset>
            <legend>Filtros</legend>
            <label>Por fecha</label>
            <div class="row">
                 <div class="col s6" style="padding-left: 0px;">
                     <input placeholder="01-01-2014" type="text" id="fecha_from" autocomplete="off" autocorrect="off" autocapitilize="off" spellcheck="false">
                 </div>
                 <div class="col s6">
                       <input placeholder="31-12-2014" type="text" id="fecha_to" autocomplete="off" autocorrect="off" autocapitilize="off" spellcheck="false">
                 </div>
                <button id="generar_reporte" style="width: 100%; height: 45px; margin-top: 15px"class="btn waves-effect waves-light">Generar reporte
                </button>
             </div>
        </fieldset>
    </div>
</div>

    <table id="tabla-paciente" class="bordered">
        <thead>
            <tr>
                <th>Concepto</th>
                <th>Total</th>
            </tr>
        </thead>    
        <tbody>
            <tr>
                <td>Servicios</td>
                <td id="total_servicios">0.00</td>
            </tr>
             <tr>
                <td>Productos</td>
                <td id="total_productos">0.00</td>
            </tr>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#report-container').ingresosreports();
    });
</script>