<?php
    $title = $proveedorForm->get('proveedor_nombre')->getValue();
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $proveedorForm->setAttribute('action', '/catalogos/proveedor/editar/'.$id);?>
<?php $proveedorForm->setAttribute('class', 'hva-form');?>
<?php $proveedorForm->prepare();?>
<?php echo $this->form()->openTag($proveedorForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($proveedorForm->get('proveedor_nombre')); ?>
                    <?php echo $this->formLabel($proveedorForm->get('proveedor_nombre')); ?>
                </div>
                 <p id="proveedor_nombre" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_contacto')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_contacto')); ?>
            </div>
            <p id="proveedor_contacto" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_direccion')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_direccion')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_direccion2')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_direccion2')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_colonia')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_colonia')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_codigopostal')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_codigopostal')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_ciudad')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_ciudad')); ?>
            </div>
            <p id="proveedor_ciudad" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_estado')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_estado')); ?>
            </div>
            <p id="proveedor_estado" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_pais')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_pais')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_email')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_email')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_telefono')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_telefono')); ?>
                <p id="proveedor_telefono" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_telefonocelular')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_telefonocelular')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_fax')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_fax')); ?>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {        
        //Inicializamos el select de materialize
         $('select').material_select();
        

           //Validacion de campos obligatorios 
        $(document).on('click', 'form button[type=submit]', function(e) {
            $('p.input-error').hide();
            var isValid = true;
            //console.log($('select[name=idtipo]').val());
            if(!$('input[name=proveedor_nombre]').val().length){
               isValid = false;
               $('p#proveedor_nombre').show();
               e.preventDefault(); 
            }
            if(!$('input[name=proveedor_telefono]').val().length){
               isValid = false;
               $('p#proveedor_telefono').show();
               e.preventDefault(); 
            }
            if(!$('input[name=proveedor_contacto]').val().length){
               isValid = false;
               $('p#proveedor_contacto').show();
               e.preventDefault(); 
            }
            if(!$('input[name=proveedor_ciudad]').val().length){
               isValid = false;
               $('p#proveedor_ciudad').show();
               e.preventDefault(); 
            }
            if(!$('input[name=proveedor_estado]').val().length){
               isValid = false;
               $('p#proveedor_estado').show();
               e.preventDefault(); 
            }
            
        });
          

    });
</script>