<?php
$title = 'Eliminar proveedor';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete?</p>
<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Contácto</th>
        <th>Dirección</th>
        <th>Dirección2</th>
        <th>Colonia</th>
        <th>C.P.</th>
        <th>Ciudad</th>
        <th>Estado</th>
        <th>País</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th>Celular</th>
        <th>Fax</th>
    </tr>
        <tr>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_nombre']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_contacto']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_direccion']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_direccion2']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_colonia']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_codigopostal']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_ciudad']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_estado']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_pais']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_email']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_telefono']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_telefonocelular']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_fax']);?></td>
        </tr>
</table>
<?php
$url = $this->url('proveedor', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $proveedor['idproveedor']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>