<?php
    $title = 'Proveedores';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<!--<p>
    <a href="<?php echo $this->url('proveedor', array('action'=>'nuevo'));?>">Nuevo proveedor</a>
</p>-->
<div class="row" id="table-header">
    <form class="col s12">
        <?php if(count($flashMessages)) :?>
            <?php foreach ($flashMessages as $message) :?>
                <div class="card-panel #00086E-text green accent-2"><?php echo $message?></div>
            <?php endforeach;?>
        <?php endif;?>    
        <div class="row" style="position: relative">
            <div class="col s6" id="new-container">
                <a href="/catalogos/proveedor/nuevo"><i class="mdi-content-add-circle-outline prefix"></i>Nuevo Proveedor</a>
            </div>
              <div class="input-field col s4 offset-s2" id="search-container">
              <i class="mdi-action-search prefix"></i>
              <input id="icon_prefix" type="text">
              <label for="icon_prefix">Buscar</label>
            </div>     
        </div>
    </form>
</div>
<table id="tabla-proveedores" class="striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Contacto</th>
            <th>Ciudad</th>
            <th>Telefono</th>
            <th >Opciones</th>
        </tr>
    </thead>
    <tbody>
    <?php $direction = 'right'?>
    <?php foreach ($proveedores as $proveedor) : ?>
        <tr>
            <td><?php echo $proveedor->getProveedorNombre() ?></td>
            <td><?php echo $proveedor->getProveedorContacto() ?></td>
            <td><?php echo $proveedor->getProveedorCiudad().", ". $proveedor->getProveedorEstado()?></td>
            <td class="telefono"><?php echo $proveedor->getProveedorTelefono() ?></td>
            <td>
                <a class="tooltipped modal-trigger" data-position="left" data-tooltip="Visualizar" href='<?php echo "#view-modal-proveedor-".$proveedor->getIdProveedor()?>'><i class="tiny mdi-image-remove-red-eye"></i></a>
                &nbsp;&nbsp;
                <a class="tooltipped" data-position="right" data-tooltip="Editar" href='<?php echo "/catalogos/proveedor/editar/".$proveedor->getIdProveedor()?>'><i class="tiny mdi-action-assignment"></i></a>
                &nbsp;&nbsp;    
                <a class="tooltipped modal-trigger" data-position="right" data-tooltip="Eliminar" href='<?php echo "#delete-modal-proveedor-".$proveedor->getIdProveedor()?>'><i class="tiny mdi-action-delete"></i></a>
            </td>
        </tr>
         <div id="view-modal-proveedor-<?php echo $proveedor->getIdProveedor()?>" class="modal ">
            <div class="modal-content">
              <h4><?php echo $proveedor->getProveedorNombre()?></h4>
              <div class="row">
                  <fieldset>
                      <legend>Datos Generales</legend>
                      <div class="col s4">
                             <div class="label-container">
                                <label>Contacto:</label>
                                <p><?php echo $proveedor->getProveedorContacto()?></p>
                            </div>                  
                             <div class="label-container">
                                <label>Direccion:</label>
                                <p><?php echo $proveedor->getProveedorDireccion()?></p>
                            </div>
                            <div class="label-container">
                                <label>Direccion 2:</label>
                                <p><?php echo $proveedor->getProveedorDireccion2()?></p>
                            </div>
                             <div class="label-container">
                                <label>Colonia:</label>
                                <p><?php echo $proveedor->getProveedorColonia()?></p>
                            </div>
                        </div>
                        <div class="col s4">
                             <div class="label-container">
                                <label>Codigo Postal:</label>
                                <p><?php echo $proveedor->getProveedorCodigopostal()?></p>
                            </div>                  
                             <div class="label-container">
                                <label>Ciudad:</label>
                                <p><?php echo $proveedor->getProveedorCiudad()?></p>
                            </div>
                            <div class="label-container">
                                <label>Estado:</label>
                                <p><?php echo $proveedor->getProveedorEstado()?></p>
                            </div>
                             <div class="label-container">
                                <label>Pais:</label>
                                <p><?php echo $proveedor->getProveedorPais()?></p>
                            </div>
                         </div>
                        <div class="col s4">
                             <div class="label-container">
                                <label>Correo electronico:</label>
                                <p><?php echo $proveedor->getProveedorEmail()?></p>
                            </div>                  
                             <div class="label-container">
                                <label>Telefono:</label>
                                <p><?php echo $proveedor->getProveedorCiudad()?></p>
                            </div>
                            <div class="label-container">
                                <label>Celular:</label>
                                <p><?php echo $proveedor->getProveedorTelefonocelular()?></p>
                            </div>
                             <div class="label-container">
                                <label>Fax:</label>
                                <p><?php echo $proveedor->getProveedorFax()?></p>
                            </div>
                         </div>
                  </fieldset>
              </div>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-action modal-close waves-effect waves-light btn cerrar"><i class="mdi-navigation-close left"></i>Cerrar</a>
              <a href='<?php echo "/catalogos/proveedor/editar/".$proveedor->getIdProveedor()?>' class="waves-effect waves-light btn editar"><i class="mdi-action-assignment left"></i>Editar</a>
            </div>
        </div>
        <!-- Delete Modal Structure -->
        <div id="delete-modal-proveedor-<?php echo $proveedor->getIdProveedor()?>" class="modal ">
            <div class="modal-content" id="delete-modal-container">
                <div class="row" id="delete-modal-header-container">
                    <div class="col s5 offset-s4">
                        <h4><i class="mdi-alert-warning prefix"></i> ATENCION</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <p><?php echo "Esta seguro que desea eliminar al Proveedor: ". $proveedor->getProveedorNombre(). " de su catalogo?" ?></p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <a href='#!' class="waves-effect waves-light btn cerrar modal-close"><i class="mdi-navigation-close left"></i>Cerrar</a>
                <a href="/catalogos/proveedor/eliminar/<?php echo $proveedor->getIdProveedor()?>" class="waves-effect waves-light btn eliminar"><i class="mdi-action-delete left"></i>Eliminar</a>
              
            </div>
        </div>
        <!-- End Delete Modal Structure -->
    <?php endforeach; ?>
    </tbody>
</table>
<script>
$(document).ready(function(){
        $("#tabla-proveedores").tablesorter({headers:{4:{sorter:false},3:{sorter:false}}});
        $("#tabla-proveedores").filterTable({inputSelector: '#search-container input',minRows:1});
        $('.modal-trigger').leanModal();
}); 
</script>