<?php

$title = 'Mis Proveedores';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('proveedor', array('action'=>'nuevo'));?>">Nuevo Proveedor</a>
</p>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Contácto</th>
        <th>Dirección</th>
        <th>Dirección2</th>
        <th>Colonia</th>
        <th>C.P.</th>
        <th>Ciudad</th>
        <th>Estado</th>
        <th>País</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th>Celular</th>
        <th>Fax</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($Proveedores as $proveedor) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_nombre']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_contacto']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_direccion']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_direccion2']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_colonia']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_codigopostal']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_ciudad']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_estado']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_pais']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_email']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_telefono']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_telefonocelular']);?></td>
            <td><?php echo $this->escapeHtml($proveedor['proveedor_fax']);?></td>
            <td>
                <a href="<?php echo $this->url('proveedor',
                    array('action'=>'editar', 'id' => $proveedor['idproveedor']));?>">Editar</a>
                <a href="<?php echo $this->url('proveedor',
                    array('action'=>'eliminar', 'id' => $proveedor['idproveedor']));?>">Eliminar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>