<?php
    $title = 'Nuevo Proveedor';
    $this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php $proveedorForm->setAttribute('action', '/catalogos/proveedor/nuevo');?>
<?php $proveedorForm->setAttribute('class', 'hva-form');?>
<?php $proveedorForm->prepare();?>
<?php echo $this->form()->openTag($proveedorForm); ?>
<div class="row">
    <fieldset>
        <legend>Datos Generales</legend>
        <div class="row">
            <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($proveedorForm->get('proveedor_nombre')); ?>
                    <?php echo $this->formLabel($proveedorForm->get('proveedor_nombre')); ?>
                </div>
                 <p id="proveedor_nombre" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            </div>
             <div class="col s4">
                <div class="input-field">
                    <?php echo $this->formText($proveedorForm->get('proveedor_rfc')); ?>
                    <?php echo $this->formLabel($proveedorForm->get('proveedor_rfc')); ?>
                </div>
                 <p id="proveedor_nombre" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_contacto')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_contacto')); ?>
            </div>
            <p id="proveedor_contacto" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_direccion')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_direccion')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_direccion2')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_direccion2')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_colonia')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_colonia')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_codigopostal')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_codigopostal')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_ciudad')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_ciudad')); ?>
            </div>
            <p id="proveedor_ciudad" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_estado')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_estado')); ?>
            </div>
            <p id="proveedor_estado" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_pais')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_pais')); ?>
            </div>
        </div>
        <div class="col s4">
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_email')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_email')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_telefono')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_telefono')); ?>
                <p id="proveedor_telefono" class="input-error"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>
                
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_telefonocelular')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_telefonocelular')); ?>
            </div>
            <div class="input-field">
                <?php echo $this->formText($proveedorForm->get('proveedor_fax')); ?>
                <?php echo $this->formLabel($proveedorForm->get('proveedor_fax')); ?>
            </div>
        </div>
    </fieldset>
</div>
<p style="color: #9e9e9e">(*) Campos obligatorios</p>
<div class="row">
    <div class="col s4 offset-s4">
        <button style="width: 100%; height: 45px;"class="btn waves-effect waves-light" type="submit" name="action">Guardar
            <i class="mdi-content-save left"></i>
        </button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {        
        //Inicializamos el select de materialize
         $('select').material_select();
        

        $('button[type=submit]').on('click',function(e){
            $('p.input-error-show').remove();
            var error_message = '<p class="input-error-show"> <i class="tiny mdi-alert-error"></i>Este campo no puede ir vacio</p>';
            var isValid = true;
            $(document).find('input[required],select[required]').filter(function(){
                if($(this).val() == ''){
                    $(this).after(error_message);
                    isValid = false;
                }
                
            });
            
            if(!isValid){
                e.preventDefault();
            }
            
        });
        
          

    });
</script>