<?php
$title = 'Nuevo Proveedor';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(!$Error){
    $ProveedorForm->setAttribute('action', $this->url('proveedor', array('action' => 'nuevo')));
    $ProveedorForm->prepare();

    echo $this->form()->openTag($ProveedorForm);
    echo $this->formCollection($ProveedorForm);
    echo $this->form()->closeTag();
}else{
    foreach ($Error as $errorValue){
        echo $errorValue;
    }
}