
<br>
<br>

<a class="waves-effect waves-light btn">Stuff</a>
<a class="waves-effect waves-light btn"><i class="mdi-file-cloud left"></i>button</a>
<a class="waves-effect waves-light btn"><i class="mdi-file-cloud right"></i>button</a>

<br>
<br>

<a class="btn-floating btn-large waves-effect waves-light red"><i class="mdi-content-add"></i></a>

<br>
<br>

<ul>
    <li><a class="btn-floating red"><i class="large mdi-editor-insert-chart"></i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="large mdi-editor-format-quote"></i></a></li>
    <li><a class="btn-floating green"><i class="large mdi-editor-publish"></i></a></li>
    <li><a class="btn-floating blue"><i class="large mdi-editor-attach-file"></i></a></li>
</ul>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red">
        <i class="large mdi-editor-mode-edit"></i>
    </a>
    <ul>
        <li><a class="btn-floating red"><i class="large mdi-editor-insert-chart"></i></a></li>
        <li><a class="btn-floating yellow darken-1"><i class="large mdi-editor-format-quote"></i></a></li>
        <li><a class="btn-floating green"><i class="large mdi-editor-publish"></i></a></li>
        <li><a class="btn-floating blue"><i class="large mdi-editor-attach-file"></i></a></li>
    </ul>
</div>